# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AccountType(StrEnum):
    """
    Loại tài khoản giao dịch: Cash, Margin hoặc Derivative.
    """

    CASH = 'Cash'
    MARGIN = 'Margin'
    DERIVATIVE = 'Derivative'


class Account(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str = Field(
        ..., alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    account_type: AccountType = Field(
        ...,
        alias='accountType',
        description='Loại tài khoản giao dịch: Cash, Margin hoặc Derivative.',
    )
    """Loại tài khoản giao dịch: Cash, Margin hoặc Derivative."""


class GetAccountInfoResponse200(RootModel[list[Account]]):
    root: list[Account]
