# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class TokenResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    token_type: str = Field(..., alias='tokenType', description='Loại token.')
    """Loại token."""

    access_token: str = Field(
        ..., alias='accessToken', description='Access token dùng để gọi API.'
    )
    """Access token dùng để gọi API."""

    expires_at: int = Field(
        ..., alias='expiresAt', description='Thời điểm access token hết hạn.'
    )
    """Thời điểm access token hết hạn."""

    refresh_token: str = Field(
        ...,
        alias='refreshToken',
        description='Refresh token dùng để làm mới access token.',
    )
    """Refresh token dùng để làm mới access token."""

    refresh_expires_at: int = Field(
        ..., alias='refreshExpiresAt', description='Thời điểm refresh token hết hạn.'
    )
    """Thời điểm refresh token hết hạn."""


class OtpResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    message: str = Field(..., description='Thông báo kết quả xử lý yêu cầu OTP.')
    """Thông báo kết quả xử lý yêu cầu OTP."""

    transaction_id: str = Field(
        ...,
        alias='transactionId',
        description='Mã transaction trả về khi tài khoản dùng 2FA loại SmartOTP. \nDùng mã này để gọi `auth/token` sau khi đã phê duyệt trên ứng dụng iBoard. \n**⚠️ Lưu ý: `transactionId` chỉ có hiệu lực trong vòng 30 giây — bạn cần thực hiện\nphê duyệt giao dịch này trên ứng dụng iBoard App Mobile trong thời gian đó. \nSau khi đã phê duyệt trên mobile, cần sử dụng `transactionId` \nđể gọi API `auth/token` để lấy token có quyền đặt lệnh.**',
    )
    """
    Mã transaction trả về khi tài khoản dùng 2FA loại SmartOTP. 
    Dùng mã này để gọi `auth/token` sau khi đã phê duyệt trên ứng dụng iBoard. 
    **⚠️ Lưu ý: `transactionId` chỉ có hiệu lực trong vòng 30 giây — bạn cần thực hiện
    phê duyệt giao dịch này trên ứng dụng iBoard App Mobile trong thời gian đó. 
    Sau khi đã phê duyệt trên mobile, cần sử dụng `transactionId` 
    để gọi API `auth/token` để lấy token có quyền đặt lệnh.**
    """


class IssueTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    api_key: str = Field(
        ..., alias='apiKey', description='API key do SSI/FastConnect cấp cho ứng dụng.'
    )
    """API key do SSI/FastConnect cấp cho ứng dụng."""

    api_secret: str = Field(
        ..., alias='apiSecret', description='API secret tương ứng với apiKey.'
    )
    """API secret tương ứng với apiKey."""

    otp: str | None | MISSING = Field(
        MISSING,
        description='Mã OTP (SMS OTP hoặc SmartOTP) cần phải có nếu bạn muốn token cấp ra có quyền thực hiện giao dịch. Trường hợp chỉ sử dụng để truy vấn dữ liệu (data, query trading) thì không cần truyền OTP.',
    )
    """Mã OTP (SMS OTP hoặc SmartOTP) cần phải có nếu bạn muốn token cấp ra có quyền thực hiện giao dịch. Trường hợp chỉ sử dụng để truy vấn dữ liệu (data, query trading) thì không cần truyền OTP."""

    transaction_id: str | None | MISSING = Field(
        MISSING,
        alias='transactionId',
        description='Mã transaction trả về từ API `auth/requestOtp` khi tài khoản dùng 2FA loại SmartOTP và đã kích hoạt luồng phê duyệt qua ứng dụng iBoard.',
    )
    """Mã transaction trả về từ API `auth/requestOtp` khi tài khoản dùng 2FA loại SmartOTP và đã kích hoạt luồng phê duyệt qua ứng dụng iBoard."""


class RequestOtpRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    api_key: str = Field(
        ..., alias='apiKey', description='API key do SSI/FastConnect cấp.'
    )
    """API key do SSI/FastConnect cấp."""

    api_secret: str = Field(
        ..., alias='apiSecret', description='API secret tương ứng với apiKey.'
    )
    """API secret tương ứng với apiKey."""


class RefreshTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    refresh_token: str = Field(
        ..., alias='refreshToken', description='Refresh token còn hiệu lực.'
    )
    """Refresh token còn hiệu lực."""
