# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: str | MISSING = Field(
        MISSING, description='Mã kết quả hoặc mã xác thực giao dịch.'
    )
    """Mã kết quả hoặc mã xác thực giao dịch."""

    msg: str | MISSING = Field(MISSING, description='Thông báo kết quả xử lý.')
    """Thông báo kết quả xử lý."""
