# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class Side(Enum):
    """
    Chiều mua hoặc bán của lệnh. B (Buy/Mua) hoặc S (Sell/Bán).
    """

    B = 'B'
    S = 'S'


class Type(StrEnum):
    """
    Loại lệnh điều kiện.
    """

    STOP = 'stop'
    STOP_LIMIT = 'stop_limit'
    GTD = 'gtd'
    BULLBEAR = 'bullbear'
    OCO = 'oco'
    TRAILING_STOP = 'trailing_stop'
    TRAILING_STOP_LIMIT = 'trailing_stop_limit'


class PlaceFcoOrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str = Field(
        ...,
        alias='accountNo',
        description='Tài khoản đặt lệnh (tài khoản cơ sở hoặc phái sinh).',
    )
    """Tài khoản đặt lệnh (tài khoản cơ sở hoặc phái sinh)."""

    device_id: str = Field(
        ...,
        alias='deviceId',
        description='Định danh thiết bị thực hiện gửi yêu cầu. Thông thường dùng MAC address hoặc IMEI của thiết bị.',
    )
    """Định danh thiết bị thực hiện gửi yêu cầu. Thông thường dùng MAC address hoặc IMEI của thiết bị."""

    user_agent: str | None | MISSING = Field(
        MISSING,
        alias='userAgent',
        description='Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu.',
    )
    """Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu."""

    client_request_id: str | None | MISSING = Field(
        MISSING,
        alias='clientRequestId',
        description='Định danh lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh lệnh cho khách hàng và trả về response & streaming.',
    )
    """Định danh lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh lệnh cho khách hàng và trả về response & streaming."""

    ip_address: str | None | MISSING = Field(
        MISSING, alias='ipAddress', description='Địa chỉ IP của thiết bị gửi yêu cầu.'
    )
    """Địa chỉ IP của thiết bị gửi yêu cầu."""

    from_: str | None | MISSING = Field(
        MISSING,
        alias='from',
        description='Ngày bắt đầu hiệu lực của lệnh điều kiện, định dạng `YYYY/MM/DD hh:mm:ss`. Mặc định là thời điểm tạo lệnh.',
    )
    """Ngày bắt đầu hiệu lực của lệnh điều kiện, định dạng `YYYY/MM/DD hh:mm:ss`. Mặc định là thời điểm tạo lệnh."""

    to: str | None | MISSING = Field(
        MISSING,
        description='Ngày kết thúc hiệu lực của lệnh điều kiện, định dạng `YYYY/MM/DD hh:mm:ss`. Mặc định là 24h kể từ thời điểm tạo, tối đa 31 ngày kể từ ngày bắt đầu.',
    )
    """Ngày kết thúc hiệu lực của lệnh điều kiện, định dạng `YYYY/MM/DD hh:mm:ss`. Mặc định là 24h kể từ thời điểm tạo, tối đa 31 ngày kể từ ngày bắt đầu."""

    code: str | None | MISSING = Field(
        MISSING,
        description='Mã xác thực OTP hoặc mã PIN dùng để xác thực giao dịch (cần điền nếu token chưa được xác thực kèm với OTP)',
    )
    """Mã xác thực OTP hoặc mã PIN dùng để xác thực giao dịch (cần điền nếu token chưa được xác thực kèm với OTP)"""

    symbol: str | None = Field(
        ...,
        description='Mã chứng khoán hoặc mã hợp đồng phái sinh cần đặt lệnh điều kiện.',
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh cần đặt lệnh điều kiện."""

    side: Side = Field(
        ..., description='Chiều mua hoặc bán của lệnh. B (Buy/Mua) hoặc S (Sell/Bán).'
    )
    """Chiều mua hoặc bán của lệnh. B (Buy/Mua) hoặc S (Sell/Bán)."""

    type: Type = Field(..., description='Loại lệnh điều kiện.')
    """Loại lệnh điều kiện."""

    price: str | None = Field(
        ...,
        description='Giá đặt lệnh. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL).',
    )
    """Giá đặt lệnh. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL)."""

    quantity: int = Field(..., description='Khối lượng muốn đặt lệnh.')
    """Khối lượng muốn đặt lệnh."""

    price_slip: float | None | MISSING = Field(
        MISSING,
        alias='priceSlip',
        description='Khoảng trượt giá (price slippage) cho phép khi thực hiện lệnh.',
    )
    """Khoảng trượt giá (price slippage) cho phép khi thực hiện lệnh."""

    stop_price: float | None | MISSING = Field(
        MISSING,
        alias='stopPrice',
        description='Giá dừng lỗ. Khi giá thị trường đạt đến mức này, lệnh sẽ được kích hoạt.',
    )
    """Giá dừng lỗ. Khi giá thị trường đạt đến mức này, lệnh sẽ được kích hoạt."""

    active_price: float | None | MISSING = Field(
        MISSING,
        alias='activePrice',
        description='Giá kích hoạt ban đầu của lệnh điều kiện.',
    )
    """Giá kích hoạt ban đầu của lệnh điều kiện."""

    trailing_amount: float | None | MISSING = Field(
        MISSING,
        alias='trailingAmount',
        description='Khoảng giá trailing. Dùng cho loại lệnh trailing_stop và trailing_stop_limit.',
    )
    """Khoảng giá trailing. Dùng cho loại lệnh trailing_stop và trailing_stop_limit."""

    tp_active_price: float | None | MISSING = Field(
        MISSING,
        alias='tpActivePrice',
        description='Giá kích hoạt lệnh chốt lời (Take Profit). Khi giá thị trường đạt đến mức này, lệnh chốt lời sẽ được kích hoạt.',
    )
    """Giá kích hoạt lệnh chốt lời (Take Profit). Khi giá thị trường đạt đến mức này, lệnh chốt lời sẽ được kích hoạt."""

    sl_active_price: float | None | MISSING = Field(
        MISSING,
        alias='slActivePrice',
        description='Giá kích hoạt lệnh dừng lỗ (Stop Loss). Khi giá thị trường đạt đến mức này, lệnh dừng lỗ sẽ được kích hoạt.',
    )
    """Giá kích hoạt lệnh dừng lỗ (Stop Loss). Khi giá thị trường đạt đến mức này, lệnh dừng lỗ sẽ được kích hoạt."""

    tp_price: str | None | MISSING = Field(
        MISSING,
        alias='tpPrice',
        description='Giá chốt lời. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL).',
    )
    """Giá chốt lời. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL)."""

    sl_price: str | None | MISSING = Field(
        MISSING,
        alias='slPrice',
        description='Giá dừng lỗ. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL).',
    )
    """Giá dừng lỗ. Hỗ trợ giá số hoặc loại lệnh đặc biệt (MP, MOK, MTL)."""

    tp_slip: float | None | MISSING = Field(
        MISSING, alias='tpSlip', description='Biên trượt giá chốt lời.'
    )
    """Biên trượt giá chốt lời."""

    sl_slip: float | None | MISSING = Field(
        MISSING, alias='slSlip', description='Biên trượt giá dừng lỗ.'
    )
    """Biên trượt giá dừng lỗ."""

    operator: str | None | MISSING = Field(
        MISSING, description='Toán tử so sánh giá để kích hoạt lệnh điều kiện.'
    )
    """Toán tử so sánh giá để kích hoạt lệnh điều kiện."""


class CancelFcoOrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    fco_id: str | None = Field(
        ..., alias='fcoId', description='ID của lệnh điều kiện cần hủy.'
    )
    """ID của lệnh điều kiện cần hủy."""

    code: str | None | MISSING = Field(
        MISSING, description='Mã xác thực OTP hoặc mã PIN dùng để xác thực giao dịch.'
    )
    """Mã xác thực OTP hoặc mã PIN dùng để xác thực giao dịch."""

    device_id: str | MISSING = Field(
        MISSING,
        alias='deviceId',
        description='Định danh thiết bị thực hiện gửi yêu cầu. Thông thường dùng MAC address hoặc IMEI của thiết bị.',
    )
    """Định danh thiết bị thực hiện gửi yêu cầu. Thông thường dùng MAC address hoặc IMEI của thiết bị."""

    user_agent: str | None | MISSING = Field(
        MISSING,
        alias='userAgent',
        description='Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu.',
    )
    """Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu."""


class Datum(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    state: str | MISSING = Field(MISSING, description='Trạng thái của lệnh điều kiện.')
    """Trạng thái của lệnh điều kiện."""

    time: str | MISSING = Field(MISSING, description='Thời điểm ghi nhận.')
    """Thời điểm ghi nhận."""

    code: int | MISSING = Field(
        MISSING, description='Mã kết quả hoặc mã xác thực giao dịch.'
    )
    """Mã kết quả hoặc mã xác thực giao dịch."""

    detail: str | MISSING = Field(MISSING, description='Chi tiết kết quả hoặc lỗi.')
    """Chi tiết kết quả hoặc lỗi."""


class FcoStatusHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[Datum] | MISSING = Field(MISSING, description='Dữ liệu trả về.')
    """Dữ liệu trả về."""


class DatumModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    fco_id: str | MISSING = Field(
        MISSING, alias='fcoId', description='ID của lệnh điều kiện.'
    )
    """ID của lệnh điều kiện."""

    username: str | MISSING = Field(MISSING, description='Tên người dùng tại SSI.')
    """Tên người dùng tại SSI."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    quantity: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    price: str | MISSING = Field(MISSING, description='Giá đặt hoặc giá thực hiện.')
    """Giá đặt hoặc giá thực hiện."""

    price_slip: float | MISSING = Field(
        MISSING, alias='priceSlip', description='Khoảng trượt giá.'
    )
    """Khoảng trượt giá."""

    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    type: str | MISSING = Field(MISSING, description='Loại lệnh điều kiện.')
    """Loại lệnh điều kiện."""

    order_type: str | None | MISSING = Field(
        MISSING, alias='orderType', description='Loại lệnh giao dịch.'
    )
    """Loại lệnh giao dịch."""

    from_: str | MISSING = Field(
        MISSING,
        alias='from',
        description='Thời điểm bắt đầu hiệu lực hoặc khoảng thời gian lọc.',
    )
    """Thời điểm bắt đầu hiệu lực hoặc khoảng thời gian lọc."""

    to: str | MISSING = Field(
        MISSING, description='Thời điểm kết thúc hiệu lực hoặc khoảng thời gian lọc.'
    )
    """Thời điểm kết thúc hiệu lực hoặc khoảng thời gian lọc."""

    matched_quantity: float | MISSING = Field(
        MISSING, alias='matchedQuantity', description='Khối lượng đã khớp.'
    )
    """Khối lượng đã khớp."""

    is_place_order: bool | MISSING = Field(
        MISSING,
        alias='isPlaceOrder',
        description='Cho biết lệnh thực đã được phát sinh hay chưa.',
    )
    """Cho biết lệnh thực đã được phát sinh hay chưa."""

    status: str | MISSING = Field(MISSING, description='Trạng thái xử lý.')
    """Trạng thái xử lý."""

    detail: str | MISSING = Field(MISSING, description='Chi tiết kết quả hoặc lỗi.')
    """Chi tiết kết quả hoặc lỗi."""

    fco_params: dict[str, Any] | MISSING = Field(
        MISSING, description='Các tham số của lệnh điều kiện.'
    )
    """Các tham số của lệnh điều kiện."""


class FcoListResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang.'
    )
    """Chỉ số trang."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang.'
    )
    """Số lượng bản ghi trên mỗi trang."""

    items_count: int | MISSING = Field(
        MISSING, alias='itemsCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    pages_count: str | MISSING = Field(
        MISSING, alias='pagesCount', description='Tổng số trang.'
    )
    """Tổng số trang."""

    data: list[DatumModel] | MISSING = Field(
        MISSING, description='Danh sách lệnh điều kiện.'
    )
    """Danh sách lệnh điều kiện."""


class DatumModel1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    fco_id: str | MISSING = Field(
        MISSING, alias='fcoId', description='ID của lệnh điều kiện.'
    )
    """ID của lệnh điều kiện."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    quantity: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    price: str | MISSING = Field(MISSING, description='Giá đặt hoặc giá thực hiện.')
    """Giá đặt hoặc giá thực hiện."""

    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    side: str | MISSING = Field(MISSING, description='Chiều mua hoặc bán của lệnh.')
    """Chiều mua hoặc bán của lệnh."""

    order_type: str | MISSING = Field(
        MISSING, alias='orderType', description='Loại lệnh giao dịch.'
    )
    """Loại lệnh giao dịch."""

    is_main_order: bool | MISSING = Field(
        MISSING,
        alias='isMainOrder',
        description='Cho biết đây là lệnh chính hay không.',
    )
    """Cho biết đây là lệnh chính hay không."""

    is_attached_order: bool | MISSING = Field(
        MISSING,
        alias='isAttachedOrder',
        description='Cho biết đây là lệnh đính kèm hay không.',
    )
    """Cho biết đây là lệnh đính kèm hay không."""

    created_time: str | MISSING = Field(
        MISSING, alias='createdTime', description='Thời điểm tạo.'
    )
    """Thời điểm tạo."""

    updated_time: str | MISSING = Field(
        MISSING, alias='updatedTime', description='Thời điểm cập nhật.'
    )
    """Thời điểm cập nhật."""

    unique_id: str | MISSING = Field(
        MISSING, alias='uniqueId', description='Định danh duy nhất của lệnh.'
    )
    """Định danh duy nhất của lệnh."""

    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Định danh lệnh do SSI tạo.'
    )
    """Định danh lệnh do SSI tạo."""

    matched_quantity: float | MISSING = Field(
        MISSING, alias='matchedQuantity', description='Khối lượng đã khớp.'
    )
    """Khối lượng đã khớp."""

    os_quantity: float | MISSING = Field(
        MISSING, alias='osQuantity', description='Khối lượng còn lại.'
    )
    """Khối lượng còn lại."""

    avg_price: float | MISSING = Field(
        MISSING, alias='avgPrice', description='Giá khớp trung bình.'
    )
    """Giá khớp trung bình."""

    status: str | MISSING = Field(MISSING, description='Trạng thái xử lý.')
    """Trạng thái xử lý."""

    detail: str | MISSING = Field(MISSING, description='Chi tiết kết quả hoặc lỗi.')
    """Chi tiết kết quả hoặc lỗi."""


class FcoOrderbookResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page_index: str | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang.'
    )
    """Chỉ số trang."""

    page_size: str | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang.'
    )
    """Số lượng bản ghi trên mỗi trang."""

    items_count: str | MISSING = Field(
        MISSING, alias='itemsCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    pages_count: str | MISSING = Field(
        MISSING, alias='pagesCount', description='Tổng số trang.'
    )
    """Tổng số trang."""

    data: list[DatumModel1] | MISSING = Field(MISSING, description='Dữ liệu trả về.')
    """Dữ liệu trả về."""


class FcoOrderResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    fco_id: str | MISSING = Field(
        MISSING, alias='fcoId', description='ID của lệnh điều kiện.'
    )
    """ID của lệnh điều kiện."""

    username: str | MISSING = Field(MISSING, description='Tên người dùng tại SSI.')
    """Tên người dùng tại SSI."""
