# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel
from pydantic.experimental.missing_sentinel import MISSING


class Datum(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    board: str | MISSING = Field(MISSING, description='Mã sàn giao dịch.')
    """Mã sàn giao dịch."""

    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    exchange: str | MISSING = Field(MISSING, description='Sàn giao dịch.')
    """Sàn giao dịch."""

    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    ceiling: float | MISSING = Field(MISSING, description='Giá trần.')
    """Giá trần."""

    floor: float | MISSING = Field(MISSING, description='Giá sàn.')
    """Giá sàn."""

    ref_price: float | MISSING = Field(
        MISSING, alias='refPrice', description='Giá tham chiếu.'
    )
    """Giá tham chiếu."""


class MasterDataResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: int | MISSING = Field(MISSING, description='Mã kết quả.')
    """Mã kết quả."""

    msg: str | MISSING = Field(MISSING, description='Thông báo kết quả.')
    """Thông báo kết quả."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang.'
    )
    """Số lượng bản ghi trên mỗi trang."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang.'
    )
    """Chỉ số trang."""

    pages_count: int | MISSING = Field(
        MISSING, alias='pagesCount', description='Tổng số trang.'
    )
    """Tổng số trang."""

    items_count: int | MISSING = Field(
        MISSING, alias='itemsCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    data: list[Datum] | MISSING = Field(MISSING, description='Dữ liệu trả về.')
    """Dữ liệu trả về."""


class MarketFileResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data_link: AnyUrl | MISSING = Field(
        MISSING, alias='dataLink', description='Đường dẫn tải file dữ liệu thị trường.'
    )
    """Đường dẫn tải file dữ liệu thị trường."""

    code: int | MISSING = Field(MISSING, description='Mã kết quả.')
    """Mã kết quả."""

    msg: str | MISSING = Field(MISSING, description='Thông báo kết quả.')
    """Thông báo kết quả."""


class Board(StrEnum):
    """
    Mã sàn giao dịch.
    """

    HOSE = 'HOSE'
    HNX = 'HNX'
    UPCOM = 'UPCOM'


class SecurityItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    symbol_name_vi: str | MISSING = Field(
        MISSING, alias='symbolNameVi', description='Tên chứng khoán bằng tiếng Việt.'
    )
    """Tên chứng khoán bằng tiếng Việt."""

    symbol_name_en: str | MISSING = Field(
        MISSING, alias='symbolNameEn', description='Tên chứng khoán bằng tiếng Anh.'
    )
    """Tên chứng khoán bằng tiếng Anh."""

    board: Board | MISSING = Field(MISSING, description='Mã sàn giao dịch.')
    """Mã sàn giao dịch."""

    lot_size: str | MISSING = Field(
        MISSING, alias='lotSize', description='Đơn vị giao dịch lô chẵn.'
    )
    """Đơn vị giao dịch lô chẵn."""

    maturity_date: str | MISSING = Field(
        MISSING, alias='maturityDate', description='Ngày đáo hạn.'
    )
    """Ngày đáo hạn."""

    first_trading_date: str | MISSING = Field(
        MISSING, alias='firstTradingDate', description='Ngày giao dịch đầu tiên.'
    )
    """Ngày giao dịch đầu tiên."""

    last_trading_date: str | MISSING = Field(
        MISSING, alias='lastTradingDate', description='Ngày giao dịch cuối cùng.'
    )
    """Ngày giao dịch cuối cùng."""

    cw_underlying_symbol: str | None | MISSING = Field(
        MISSING,
        alias='cwUnderlyingSymbol',
        description='Mã chứng khoán cơ sở của chứng quyền.',
    )
    """Mã chứng khoán cơ sở của chứng quyền."""

    cw_exercise_price: str | MISSING = Field(
        MISSING, alias='cwExercisePrice', description='Giá thực hiện của chứng quyền.'
    )
    """Giá thực hiện của chứng quyền."""

    cw_execution_ratio: str | MISSING = Field(
        MISSING,
        alias='cwExecutionRatio',
        description='Tỷ lệ thực hiện của chứng quyền.',
    )
    """Tỷ lệ thực hiện của chứng quyền."""

    listed_share: str | MISSING = Field(
        MISSING, alias='listedShare', description='Số lượng cổ phiếu niêm yết.'
    )
    """Số lượng cổ phiếu niêm yết."""

    icb_code: str | MISSING = Field(
        MISSING, alias='icbCode', description='Mã ngành ICB.'
    )
    """Mã ngành ICB."""

    icb_name: str | MISSING = Field(
        MISSING, alias='icbName', description='Tên ngành ICB.'
    )
    """Tên ngành ICB."""

    i_index: str | None | MISSING = Field(
        MISSING, alias='iIndex', description='Chỉ số IIndex.'
    )
    """Chỉ số IIndex."""

    i_nav: str | None | MISSING = Field(
        MISSING, alias='iNav', description='Giá trị iNAV.'
    )
    """Giá trị iNAV."""

    open_interest: str | None | MISSING = Field(
        MISSING, alias='openInterest', description='Khối lượng mở.'
    )
    """Khối lượng mở."""

    settlement_price: str | None | MISSING = Field(
        MISSING, alias='settlementPrice', description='Giá thanh toán.'
    )
    """Giá thanh toán."""


class IndexItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    index: str | MISSING = Field(MISSING, description='Mã chỉ số.')
    """Mã chỉ số."""

    index_name: str | MISSING = Field(
        MISSING, alias='indexName', description='Tên chỉ số.'
    )
    """Tên chỉ số."""

    board: Board | MISSING = Field(MISSING, description='Mã sàn giao dịch.')
    """Mã sàn giao dịch."""


class DatumModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    open: str | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""

    high: str | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: str | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    close: str | MISSING = Field(MISSING, description='Giá đóng cửa.')
    """Giá đóng cửa."""

    volume: str | MISSING = Field(MISSING, description='Khối lượng giao dịch.')
    """Khối lượng giao dịch."""

    value: str | MISSING = Field(MISSING, description='Giá trị giao dịch.')
    """Giá trị giao dịch."""


class OhlcResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: int | MISSING = Field(MISSING, description='Mã kết quả.')
    """Mã kết quả."""

    msg: str | MISSING = Field(MISSING, description='Thông báo kết quả.')
    """Thông báo kết quả."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang.'
    )
    """Số lượng bản ghi trên mỗi trang."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang.'
    )
    """Chỉ số trang."""

    data: list[DatumModel] | MISSING = Field(MISSING, description='Dữ liệu trả về.')
    """Dữ liệu trả về."""


class DatumModel1(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    price_change: str | MISSING = Field(
        MISSING, alias='priceChange', description='Mức thay đổi giá.'
    )
    """Mức thay đổi giá."""

    price_change_percentage: str | MISSING = Field(
        MISSING,
        alias='priceChangePercentage',
        description='Tỷ lệ phần trăm thay đổi giá.',
    )
    """Tỷ lệ phần trăm thay đổi giá."""

    open: str | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""

    high: str | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: str | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    close: str | MISSING = Field(MISSING, description='Giá đóng cửa.')
    """Giá đóng cửa."""

    average: str | MISSING = Field(MISSING, description='Giá giao dịch bình quân.')
    """Giá giao dịch bình quân."""

    total_match: str | MISSING = Field(
        MISSING, alias='totalMatch', description='Tổng số lệnh khớp.'
    )
    """Tổng số lệnh khớp."""

    total_match_value: str | MISSING = Field(
        MISSING, alias='totalMatchValue', description='Tổng giá trị khớp lệnh.'
    )
    """Tổng giá trị khớp lệnh."""

    total_buy: str | MISSING = Field(
        MISSING, alias='totalBuy', description='Tổng khối lượng mua.'
    )
    """Tổng khối lượng mua."""

    total_trade_buy: str | MISSING = Field(
        MISSING, alias='totalTradeBuy', description='Tổng giá trị mua khớp lệnh.'
    )
    """Tổng giá trị mua khớp lệnh."""

    total_sell: str | MISSING = Field(
        MISSING, alias='totalSell', description='Tổng khối lượng bán.'
    )
    """Tổng khối lượng bán."""

    total_trade_sell: str | MISSING = Field(
        MISSING, alias='totalTradeSell', description='Tổng giá trị bán khớp lệnh.'
    )
    """Tổng giá trị bán khớp lệnh."""

    total_foreign_buy: str | MISSING = Field(
        MISSING,
        alias='totalForeignBuy',
        description='Tổng khối lượng mua của nhà đầu tư nước ngoài.',
    )
    """Tổng khối lượng mua của nhà đầu tư nước ngoài."""

    total_foreign_buy_value: str | MISSING = Field(
        MISSING,
        alias='totalForeignBuyValue',
        description='Tổng giá trị mua của nhà đầu tư nước ngoài.',
    )
    """Tổng giá trị mua của nhà đầu tư nước ngoài."""

    total_foreign_sell: str | MISSING = Field(
        MISSING,
        alias='totalForeignSell',
        description='Tổng khối lượng bán của nhà đầu tư nước ngoài.',
    )
    """Tổng khối lượng bán của nhà đầu tư nước ngoài."""

    total_foreign_sell_value: str | MISSING = Field(
        MISSING,
        alias='totalForeignSellValue',
        description='Tổng giá trị bán của nhà đầu tư nước ngoài.',
    )
    """Tổng giá trị bán của nhà đầu tư nước ngoài."""

    remain_foreign_room: str | MISSING = Field(
        MISSING,
        alias='remainForeignRoom',
        description='Room còn lại của nhà đầu tư nước ngoài.',
    )
    """Room còn lại của nhà đầu tư nước ngoài."""

    total_foreign_room: str | None | MISSING = Field(
        MISSING,
        alias='totalForeignRoom',
        description='Tổng room của nhà đầu tư nước ngoài.',
    )
    """Tổng room của nhà đầu tư nước ngoài."""

    total_deal: str | MISSING = Field(
        MISSING, alias='totalDeal', description='Tổng số giao dịch thỏa thuận.'
    )
    """Tổng số giao dịch thỏa thuận."""

    total_deal_value: str | MISSING = Field(
        MISSING,
        alias='totalDealValue',
        description='Tổng giá trị giao dịch thỏa thuận.',
    )
    """Tổng giá trị giao dịch thỏa thuận."""

    open_interest: str | None | MISSING = Field(
        MISSING, alias='openInterest', description='Khối lượng mở.'
    )
    """Khối lượng mở."""

    settlement_price: str | None | MISSING = Field(
        MISSING, alias='settlementPrice', description='Giá thanh toán.'
    )
    """Giá thanh toán."""


class SecuritiesSummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: int | MISSING = Field(MISSING, description='Mã kết quả.')
    """Mã kết quả."""

    msg: str | MISSING = Field(MISSING, description='Thông báo kết quả.')
    """Thông báo kết quả."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang.'
    )
    """Số lượng bản ghi trên mỗi trang."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang.'
    )
    """Chỉ số trang."""

    pages_count: int | MISSING = Field(
        MISSING, alias='pagesCount', description='Tổng số trang.'
    )
    """Tổng số trang."""

    items_count: int | MISSING = Field(
        MISSING, alias='itemsCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    data: list[DatumModel1] | MISSING = Field(MISSING, description='Dữ liệu trả về.')
    """Dữ liệu trả về."""


class IndexSummaryResponseItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    total_trade: str | MISSING = Field(
        MISSING, alias='totalTrade', description='Tổng số giao dịch.'
    )
    """Tổng số giao dịch."""

    total_trade_value: str | MISSING = Field(
        MISSING, alias='totalTradeValue', description='Tổng giá trị giao dịch.'
    )
    """Tổng giá trị giao dịch."""

    total_match: str | MISSING = Field(
        MISSING, alias='totalMatch', description='Tổng số lệnh khớp.'
    )
    """Tổng số lệnh khớp."""

    total_match_value: str | MISSING = Field(
        MISSING, alias='totalMatchValue', description='Tổng giá trị khớp lệnh.'
    )
    """Tổng giá trị khớp lệnh."""

    total_deal: str | MISSING = Field(
        MISSING, alias='totalDeal', description='Tổng số giao dịch thỏa thuận.'
    )
    """Tổng số giao dịch thỏa thuận."""

    total_deal_value: str | MISSING = Field(
        MISSING,
        alias='totalDealValue',
        description='Tổng giá trị giao dịch thỏa thuận.',
    )
    """Tổng giá trị giao dịch thỏa thuận."""

    index_change: str | MISSING = Field(
        MISSING, alias='indexChange', description='Mức thay đổi của chỉ số.'
    )
    """Mức thay đổi của chỉ số."""

    index_change_percentage: str | MISSING = Field(
        MISSING,
        alias='indexChangePercentage',
        description='Tỷ lệ phần trăm thay đổi của chỉ số.',
    )
    """Tỷ lệ phần trăm thay đổi của chỉ số."""

    index_value: str | MISSING = Field(
        MISSING, alias='indexValue', description='Giá trị chỉ số.'
    )
    """Giá trị chỉ số."""

    total_advance_stock: str | MISSING = Field(
        MISSING, alias='totalAdvanceStock', description='Tổng số mã tăng giá.'
    )
    """Tổng số mã tăng giá."""

    total_ceiling_stock: str | MISSING = Field(
        MISSING, alias='totalCeilingStock', description='Tổng số mã tăng trần.'
    )
    """Tổng số mã tăng trần."""

    total_decline_stock: str | MISSING = Field(
        MISSING, alias='totalDeclineStock', description='Tổng số mã giảm giá.'
    )
    """Tổng số mã giảm giá."""

    total_floor_stock: str | MISSING = Field(
        MISSING, alias='totalFloorStock', description='Tổng số mã giảm sàn.'
    )
    """Tổng số mã giảm sàn."""

    total_no_change_stock: str | MISSING = Field(
        MISSING, alias='totalNoChangeStock', description='Tổng số mã không đổi giá.'
    )
    """Tổng số mã không đổi giá."""

    total_prop_buy: str | MISSING = Field(
        MISSING,
        alias='totalPropBuy',
        description='Tổng số lượng mua của nhà đầu tư nước ngoài.',
    )
    """Tổng số lượng mua của nhà đầu tư nước ngoài."""

    total_prop_buy_value: str | MISSING = Field(
        MISSING,
        alias='totalPropBuyValue',
        description='Tổng giá trị mua của nhà đầu tư nước ngoài.',
    )
    """Tổng giá trị mua của nhà đầu tư nước ngoài."""

    total_prop_sell: str | MISSING = Field(
        MISSING,
        alias='totalPropSell',
        description='Tổng số lượng bán của nhà đầu tư nước ngoài.',
    )
    """Tổng số lượng bán của nhà đầu tư nước ngoài."""

    total_prop_sell_value: str | MISSING = Field(
        MISSING,
        alias='totalPropSellValue',
        description='Tổng giá trị bán của nhà đầu tư nước ngoài.',
    )
    """Tổng giá trị bán của nhà đầu tư nước ngoài."""


class IndexSummaryResponse(RootModel[list[IndexSummaryResponseItem]]):
    root: list[IndexSummaryResponseItem]


class GetIndexListResponse200(RootModel[list[IndexItem]]):
    root: list[IndexItem]


class GetSecuritiesByBoardResponse200(RootModel[list[SecurityItem]]):
    root: list[SecurityItem]
