# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class Side(StrEnum):
    """
    Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)
    """

    B = 'B'
    S = 'S'


class OrderType(StrEnum):
    """
    Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)
    """

    LO = 'LO'
    ATO = 'ATO'
    ATC = 'ATC'
    MP = 'MP'


class PlaceOrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    client_request_id: str | None | MISSING = Field(
        MISSING,
        alias='clientRequestId',
        description='Định danh lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh lệnh cho khách hàng và trả về response & streaming.',
    )
    """Định danh lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh lệnh cho khách hàng và trả về response & streaming."""

    account_no: str = Field(
        ..., alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    symbol: str = Field(..., description='Mã chứng khoán.')
    """Mã chứng khoán."""

    side: Side = Field(
        ...,
        description='Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)',
    )
    """Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)"""

    order_type: OrderType = Field(
        ...,
        alias='orderType',
        description='Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)',
    )
    """Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)"""

    quantity: float = Field(..., description='Khối lượng đặt lệnh.')
    """Khối lượng đặt lệnh."""

    price: str = Field(
        ...,
        description='Giá đặt lệnh. Bắt buộc khi orderType là LO (Lệnh giới hạn); không bắt buộc với các loại lệnh khác (ATO, ATC, MP).',
    )
    """Giá đặt lệnh. Bắt buộc khi orderType là LO (Lệnh giới hạn); không bắt buộc với các loại lệnh khác (ATO, ATC, MP)."""

    device_id: str = Field(
        ...,
        alias='deviceId',
        description='Định danh thiết bị thực hiện gửi yêu cầu đặt lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị.',
    )
    """Định danh thiết bị thực hiện gửi yêu cầu đặt lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị."""

    user_agent: str | None | MISSING = Field(
        MISSING,
        alias='userAgent',
        description='Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu.',
    )
    """Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu."""

    ip_address: str | None | MISSING = Field(
        MISSING, alias='ipAddress', description='Địa chỉ IP của thiết bị gửi yêu cầu.'
    )
    """Địa chỉ IP của thiết bị gửi yêu cầu."""


class SideModel(Enum):
    """
    Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)
    """

    B = 'B'
    S = 'S'


class OrderTypeModel(Enum):
    """
    Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)
    """

    LO = 'LO'
    ATO = 'ATO'
    ATC = 'ATC'
    MP = 'MP'


class ModifyOrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    client_modify_id: str | None | MISSING = Field(
        MISSING,
        alias='clientModifyId',
        description='Định danh sửa lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh sửa lệnh cho khách hàng và trả về response & streaming.',
    )
    """Định danh sửa lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh sửa lệnh cho khách hàng và trả về response & streaming."""

    client_request_id: str | None | MISSING = Field(
        MISSING,
        alias='clientRequestId',
        description='Định danh lệnh gốc do client tạo ra khi đặt lệnh. Khi để trống thì hệ thống sẽ không đối chiếu dựa trên định danh lệnh gốc mà sẽ dựa vào `orderId` để xác định lệnh cần sửa.',
    )
    """Định danh lệnh gốc do client tạo ra khi đặt lệnh. Khi để trống thì hệ thống sẽ không đối chiếu dựa trên định danh lệnh gốc mà sẽ dựa vào `orderId` để xác định lệnh cần sửa."""

    order_id: str | None | MISSING = Field(
        MISSING,
        alias='orderId',
        description='Định danh lệnh gốc sinh ra bởi hệ thống SSI.',
    )
    """Định danh lệnh gốc sinh ra bởi hệ thống SSI."""

    account_no: str = Field(
        ..., alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    symbol: str | None | MISSING = Field(MISSING, description='Mã chứng khoán.')
    """Mã chứng khoán."""

    side: SideModel | None | MISSING = Field(
        MISSING,
        description='Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)',
    )
    """Chiều mua hoặc bán của lệnh giao dịch. (B- Buy/Mua, S- Sell/Bán)"""

    order_type: OrderTypeModel | None | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)',
    )
    """Loại lệnh giao dịch. (LO - Limit Order/Lệnh giới hạn, ATO - At The Open/Lệnh mở cửa, ATC - At The Close/Lệnh đóng cửa, MP - Market Price/Giá thị trường)"""

    price: str | None | MISSING = Field(
        MISSING,
        description='Giá thay đổi của lệnh. Trường này có thể không bắt buộc tùy theo loại lệnh và quy định sửa lệnh của sàn giao dịch. Ví dụ, đối với lệnh MP (Market Price), giá có thể không cần cung cấp khi sửa lệnh.',
    )
    """Giá thay đổi của lệnh. Trường này có thể không bắt buộc tùy theo loại lệnh và quy định sửa lệnh của sàn giao dịch. Ví dụ, đối với lệnh MP (Market Price), giá có thể không cần cung cấp khi sửa lệnh."""

    quantity: float | None | MISSING = Field(
        MISSING,
        description='Khối lượng thay đổi của lệnh. Trường này có thể không bắt buộc tùy theo quy định sửa lệnh của sàn giao dịch. Ví dụ, một số sàn có thể chỉ cho phép sửa giá mà không cho phép sửa khối lượng, hoặc ngược lại.',
    )
    """Khối lượng thay đổi của lệnh. Trường này có thể không bắt buộc tùy theo quy định sửa lệnh của sàn giao dịch. Ví dụ, một số sàn có thể chỉ cho phép sửa giá mà không cho phép sửa khối lượng, hoặc ngược lại."""

    device_id: str = Field(
        ...,
        alias='deviceId',
        description='Định danh thiết bị thực hiện gửi yêu cầu sửa lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị.',
    )
    """Định danh thiết bị thực hiện gửi yêu cầu sửa lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị."""

    user_agent: str | None | MISSING = Field(
        MISSING,
        alias='userAgent',
        description='Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu.',
    )
    """Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu."""

    ip_address: str | None | MISSING = Field(
        MISSING, alias='ipAddress', description='Địa chỉ IP của thiết bị gửi yêu cầu.'
    )
    """Địa chỉ IP của thiết bị gửi yêu cầu."""


class CancelOrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    client_cancel_id: str | None | MISSING = Field(
        MISSING,
        alias='clientCancelId',
        description='Định danh hủy lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh hủy lệnh cho khách hàng và trả về response & streaming.',
    )
    """Định danh hủy lệnh do client tạo ra, dùng để đối chiếu trong các phản hồi sau này. Trường này không bắt buộc nhưng nếu có thì nên đảm bảo tính duy nhất để tránh nhầm lẫn khi xử lý phản hồi. Khi để trống thì hệ thống sẽ tự sinh định danh hủy lệnh cho khách hàng và trả về response & streaming."""

    client_request_id: str | None | MISSING = Field(
        MISSING,
        alias='clientRequestId',
        description='Định danh lệnh gốc do client tạo ra khi đặt lệnh. Khi để trống thì hệ thống sẽ không đối chiếu dựa trên định danh lệnh gốc mà sẽ dựa vào `orderId` để xác định lệnh cần hủy.',
    )
    """Định danh lệnh gốc do client tạo ra khi đặt lệnh. Khi để trống thì hệ thống sẽ không đối chiếu dựa trên định danh lệnh gốc mà sẽ dựa vào `orderId` để xác định lệnh cần hủy."""

    order_id: str | None | MISSING = Field(
        MISSING,
        alias='orderId',
        description='Định danh lệnh gốc sinh ra bởi hệ thống SSI. Đây là một trong hai trường (cùng với `clientRequestId`) được sử dụng để xác định lệnh cần hủy. Nếu cả hai trường đều có giá trị, hệ thống sẽ ưu tiên đối chiếu dựa trên `clientRequestId`. Nếu chỉ có `orderId` có giá trị thì hệ thống sẽ đối chiếu dựa trên `orderId`. Nếu cả hai trường đều không có giá trị thì yêu cầu hủy lệnh sẽ bị từ chối do thiếu thông tin xác định lệnh cần hủy.',
    )
    """Định danh lệnh gốc sinh ra bởi hệ thống SSI. Đây là một trong hai trường (cùng với `clientRequestId`) được sử dụng để xác định lệnh cần hủy. Nếu cả hai trường đều có giá trị, hệ thống sẽ ưu tiên đối chiếu dựa trên `clientRequestId`. Nếu chỉ có `orderId` có giá trị thì hệ thống sẽ đối chiếu dựa trên `orderId`. Nếu cả hai trường đều không có giá trị thì yêu cầu hủy lệnh sẽ bị từ chối do thiếu thông tin xác định lệnh cần hủy."""

    account_no: str = Field(
        ..., alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    device_id: str = Field(
        ...,
        alias='deviceId',
        description='Định danh thiết bị thực hiện gửi yêu cầu hủy lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị.',
    )
    """Định danh thiết bị thực hiện gửi yêu cầu hủy lệnh. Thông thường dùng MAC address hoặc IMEI của thiết bị."""

    user_agent: str | None | MISSING = Field(
        MISSING,
        alias='userAgent',
        description='Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu hủy lệnh.',
    )
    """Thông tin về trình duyệt hoặc ứng dụng gửi yêu cầu hủy lệnh."""

    ip_address: str | None | MISSING = Field(
        MISSING,
        alias='ipAddress',
        description='Địa chỉ IP của thiết bị gửi yêu cầu hủy lệnh.',
    )
    """Địa chỉ IP của thiết bị gửi yêu cầu hủy lệnh."""


class OrderResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    client_request_id: str | MISSING = Field(
        MISSING, alias='clientRequestId', description='Định danh yêu cầu do client tạo.'
    )
    """Định danh yêu cầu do client tạo."""

    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Định danh lệnh do SSI tạo.'
    )
    """Định danh lệnh do SSI tạo."""

    order_status: str | MISSING = Field(
        MISSING, alias='orderStatus', description='Trạng thái lệnh.'
    )
    """Trạng thái lệnh."""

    client_modify_id: str | MISSING = Field(
        MISSING,
        alias='clientModifyId',
        description='Định danh yêu cầu sửa lệnh do client tạo.',
    )
    """Định danh yêu cầu sửa lệnh do client tạo."""

    client_cancel_id: str | MISSING = Field(
        MISSING,
        alias='clientCancelId',
        description='Định danh yêu cầu hủy lệnh do client tạo.',
    )
    """Định danh yêu cầu hủy lệnh do client tạo."""


class OrderListItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    client_request_id: str | MISSING = Field(
        MISSING, alias='clientRequestId', description='Định danh yêu cầu do client tạo.'
    )
    """Định danh yêu cầu do client tạo."""

    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Định danh lệnh do SSI tạo.'
    )
    """Định danh lệnh do SSI tạo."""

    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    side: str | MISSING = Field(MISSING, description='Chiều mua hoặc bán của lệnh.')
    """Chiều mua hoặc bán của lệnh."""

    order_type: str | MISSING = Field(
        MISSING, alias='orderType', description='Loại lệnh giao dịch.'
    )
    """Loại lệnh giao dịch."""

    quantity: str | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    price: str | MISSING = Field(MISSING, description='Giá đặt hoặc giá thực hiện.')
    """Giá đặt hoặc giá thực hiện."""

    filled_qty: str | MISSING = Field(
        MISSING, alias='filledQty', description='Khối lượng đã khớp.'
    )
    """Khối lượng đã khớp."""

    cancel_qty: str | MISSING = Field(
        MISSING, alias='cancelQty', description='Khối lượng đã hủy.'
    )
    """Khối lượng đã hủy."""

    avg_price: str | MISSING = Field(
        MISSING, alias='avgPrice', description='Giá khớp trung bình.'
    )
    """Giá khớp trung bình."""

    input_time: str | MISSING = Field(
        MISSING, alias='inputTime', description='Thời điểm nhập lệnh.'
    )
    """Thời điểm nhập lệnh."""

    modified_time: str | MISSING = Field(
        MISSING, alias='modifiedTime', description='Thời điểm sửa lệnh.'
    )
    """Thời điểm sửa lệnh."""

    order_status: str | MISSING = Field(
        MISSING, alias='orderStatus', description='Trạng thái lệnh.'
    )
    """Trạng thái lệnh."""

    message: str | None | MISSING = Field(MISSING, description='Thông báo xử lý lệnh.')
    """Thông báo xử lý lệnh."""


class OrderBookResponse(BaseModel):
    """
    Dữ liệu trả về.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    total_record: int | MISSING = Field(
        MISSING, alias='totalRecord', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    order_list: list[OrderListItem] | MISSING = Field(
        MISSING, alias='orderList', description='Danh sách lệnh.'
    )
    """Danh sách lệnh."""


class MaxBuySellResponse(BaseModel):
    """
    Dữ liệu trả về.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    max_buy_qty: float | MISSING = Field(
        MISSING, alias='maxBuyQty', description='Khối lượng mua tối đa.'
    )
    """Khối lượng mua tối đa."""

    margin_ratio: str | MISSING = Field(
        MISSING, alias='marginRatio', description='Tỷ lệ ký quỹ.'
    )
    """Tỷ lệ ký quỹ."""

    max_sell_qty: float | MISSING = Field(
        MISSING, alias='maxSellQty', description='Khối lượng bán tối đa.'
    )
    """Khối lượng bán tối đa."""

    purchasing_power: float | MISSING = Field(
        MISSING, alias='purchasingPower', description='Sức mua.'
    )
    """Sức mua."""


class Equity(BaseModel):
    """
    Thông tin hoặc danh sách vị thế tài khoản cơ sở.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    account_balance: str | MISSING = Field(
        MISSING, alias='accountBalance', description='Số dư tài khoản.'
    )
    """Số dư tài khoản."""

    total_debt: str | MISSING = Field(
        MISSING, alias='totalDebt', description='Tổng dư nợ.'
    )
    """Tổng dư nợ."""

    interest_loan: str | MISSING = Field(
        MISSING, alias='interestLoan', description='Lãi vay.'
    )
    """Lãi vay."""

    overdue_fee_loan: str | MISSING = Field(
        MISSING, alias='overdueFeeLoan', description='Phí vay quá hạn.'
    )
    """Phí vay quá hạn."""

    withdrawable: str | MISSING = Field(MISSING, description='Số tiền có thể rút.')
    """Số tiền có thể rút."""

    on_hold_cash: str | MISSING = Field(
        MISSING, alias='onHoldCash', description='Tiền mặt đang bị giữ.'
    )
    """Tiền mặt đang bị giữ."""

    sell_unmatched: str | MISSING = Field(
        MISSING, alias='sellUnmatched', description='Giá trị bán chưa khớp.'
    )
    """Giá trị bán chưa khớp."""

    sell_t0: str | MISSING = Field(
        MISSING, alias='sellT0', description='Giá trị bán chờ về T+0.'
    )
    """Giá trị bán chờ về T+0."""

    sell_t1: str | MISSING = Field(
        MISSING, alias='sellT1', description='Giá trị bán chờ về T+1.'
    )
    """Giá trị bán chờ về T+1."""

    sell_t2: str | MISSING = Field(
        MISSING, alias='sellT2', description='Giá trị bán chờ về T+2.'
    )
    """Giá trị bán chờ về T+2."""

    buy_unmatched: str | MISSING = Field(
        MISSING, alias='buyUnmatched', description='Giá trị mua chưa khớp.'
    )
    """Giá trị mua chưa khớp."""

    buy_t0: str | MISSING = Field(
        MISSING, alias='buyT0', description='Giá trị mua T+0.'
    )
    """Giá trị mua T+0."""

    buy_t1: str | MISSING = Field(
        MISSING, alias='buyT1', description='Giá trị mua T+1.'
    )
    """Giá trị mua T+1."""

    buy_t2: str | MISSING = Field(
        MISSING, alias='buyT2', description='Giá trị mua T+2.'
    )
    """Giá trị mua T+2."""

    advanced_cash_t0: str | MISSING = Field(
        MISSING, alias='advancedCashT0', description='Tiền ứng trước T+0.'
    )
    """Tiền ứng trước T+0."""

    advanced_cash_t1: str | MISSING = Field(
        MISSING, alias='advancedCashT1', description='Tiền ứng trước T+1.'
    )
    """Tiền ứng trước T+1."""

    hold_subscription: str | MISSING = Field(
        MISSING,
        alias='holdSubscription',
        description='Giá trị tiền đang giữ cho quyền mua.',
    )
    """Giá trị tiền đang giữ cho quyền mua."""

    dividend: str | MISSING = Field(MISSING, description='Cổ tức.')
    """Cổ tức."""


class Derivative(BaseModel):
    """
    Thông tin tài khoản hoặc vị thế phái sinh.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    account_balance: str | MISSING = Field(
        MISSING,
        alias='accountBalance',
        description='Số dư tài khoản giao dịch (tiền mặt khả dụng).',
    )
    """Số dư tài khoản giao dịch (tiền mặt khả dụng)."""

    fee: str | MISSING = Field(MISSING, description='Phí giao dịch.')
    """Phí giao dịch."""

    commission: str | MISSING = Field(MISSING, description='Hoa hồng giao dịch.')
    """Hoa hồng giao dịch."""

    interest: str | MISSING = Field(MISSING, description='Lãi suất vay.')
    """Lãi suất vay."""

    ext_interest: str | MISSING = Field(
        MISSING, alias='extInterest', description='Lãi suất vay ngoài.'
    )
    """Lãi suất vay ngoài."""

    loan: str | MISSING = Field(
        MISSING,
        description='Dư nợ vay gốc đã sử dụng trong tài khoản giao dịch phái sinh.',
    )
    """Dư nợ vay gốc đã sử dụng trong tài khoản giao dịch phái sinh."""

    delivery_amount: str | MISSING = Field(
        MISSING,
        alias='deliveryAmount',
        description='Số tiền phải trả hoặc được nhận khi đến ngày giao hàng đối với các hợp đồng tương lai.',
    )
    """Số tiền phải trả hoặc được nhận khi đến ngày giao hàng đối với các hợp đồng tương lai."""

    floating_pl: str | MISSING = Field(
        MISSING,
        alias='floatingPL',
        description='Lãi/lỗ chưa thực hiện từ các vị thế mở.',
    )
    """Lãi/lỗ chưa thực hiện từ các vị thế mở."""

    trading_pl: str | MISSING = Field(
        MISSING,
        alias='tradingPL',
        description='Lãi/lỗ đã thực hiện từ các vị thế đã đóng.',
    )
    """Lãi/lỗ đã thực hiện từ các vị thế đã đóng."""

    total_pl: str | MISSING = Field(
        MISSING, alias='totalPL', description='Tổng lãi/lỗ (floatingPL + tradingPL).'
    )
    """Tổng lãi/lỗ (floatingPL + tradingPL)."""

    withdrawable: str | MISSING = Field(
        MISSING, description='Số tiền có thể rút từ tài khoản giao dịch phái sinh.'
    )
    """Số tiền có thể rút từ tài khoản giao dịch phái sinh."""

    cash_ssi: str | MISSING = Field(
        MISSING,
        alias='cashSSI',
        description='Số tiền mặt trong tài khoản giao dịch phái sinh tại SSI.',
    )
    """Số tiền mặt trong tài khoản giao dịch phái sinh tại SSI."""

    valid_non_cash_ssi: str | MISSING = Field(
        MISSING,
        alias='validNonCashSSI',
        description='Số tiền phi tiền mặt hợp lệ trong tài khoản phái sinh tại SSI.',
    )
    """Số tiền phi tiền mặt hợp lệ trong tài khoản phái sinh tại SSI."""

    withdrawable_ssi: str | MISSING = Field(
        MISSING,
        alias='withdrawableSSI',
        description='Số tiền có thể rút từ tài khoản phái sinh tại SSI.',
    )
    """Số tiền có thể rút từ tài khoản phái sinh tại SSI."""

    cash_vsdc: str | MISSING = Field(
        MISSING,
        alias='cashVSDC',
        description='Số tiền mặt trong tài khoản giao dịch phái sinh tại VSDC.',
    )
    """Số tiền mặt trong tài khoản giao dịch phái sinh tại VSDC."""

    valid_non_cash_vsdc: str | MISSING = Field(
        MISSING,
        alias='validNonCashVSDC',
        description='Số tiền phi tiền mặt hợp lệ trong tài khoản phái sinh tại VSDC.',
    )
    """Số tiền phi tiền mặt hợp lệ trong tài khoản phái sinh tại VSDC."""

    withdrawable_vsdc: str | MISSING = Field(
        MISSING,
        alias='withdrawableVSDC',
        description='Số tiền có thể rút từ tài khoản phái sinh tại VSDC.',
    )
    """Số tiền có thể rút từ tài khoản phái sinh tại VSDC."""


class AccountBalanceResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    equity: Equity | None = Field(
        ..., description='Thông tin hoặc danh sách vị thế tài khoản cơ sở.'
    )
    """Thông tin hoặc danh sách vị thế tài khoản cơ sở."""

    derivative: Derivative | None = Field(
        ..., description='Thông tin tài khoản hoặc vị thế phái sinh.'
    )
    """Thông tin tài khoản hoặc vị thế phái sinh."""


class EquityItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    symbol: str | MISSING = Field(
        MISSING, description='Mã chứng khoán hoặc mã hợp đồng phái sinh.'
    )
    """Mã chứng khoán hoặc mã hợp đồng phái sinh."""

    quantity: str | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    block_quantity: str | MISSING = Field(
        MISSING, alias='blockQuantity', description='Khối lượng bị phong tỏa.'
    )
    """Khối lượng bị phong tỏa."""

    dividend_quantity: str | MISSING = Field(
        MISSING, alias='dividendQuantity', description='Khối lượng cổ phiếu cổ tức.'
    )
    """Khối lượng cổ phiếu cổ tức."""

    buying_quantity: str | MISSING = Field(
        MISSING, alias='buyingQuantity', description='Khối lượng đang mua.'
    )
    """Khối lượng đang mua."""

    bought_quantity: str | MISSING = Field(
        MISSING, alias='boughtQuantity', description='Khối lượng đã mua.'
    )
    """Khối lượng đã mua."""

    selling_quantity: str | MISSING = Field(
        MISSING, alias='sellingQuantity', description='Khối lượng đang bán.'
    )
    """Khối lượng đang bán."""

    sold_quantity: str | MISSING = Field(
        MISSING, alias='soldQuantity', description='Khối lượng đã bán.'
    )
    """Khối lượng đã bán."""

    t1_sell_quantity: str | MISSING = Field(
        MISSING,
        alias='t1SellQuantity',
        description='Khối lượng có thể bán theo chu kỳ T+1.',
    )
    """Khối lượng có thể bán theo chu kỳ T+1."""

    t2_sell_quantity: str | MISSING = Field(
        MISSING,
        alias='t2SellQuantity',
        description='Khối lượng có thể bán theo chu kỳ T+2.',
    )
    """Khối lượng có thể bán theo chu kỳ T+2."""

    cost_price: str | MISSING = Field(
        MISSING, alias='costPrice', description='Giá vốn.'
    )
    """Giá vốn."""

    mortgage_quantity: str | MISSING = Field(
        MISSING, alias='mortgageQuantity', description='Khối lượng cầm cố.'
    )
    """Khối lượng cầm cố."""

    sellable_quantity: str | MISSING = Field(
        MISSING, alias='sellableQuantity', description='Khối lượng có thể bán.'
    )
    """Khối lượng có thể bán."""

    restricted_quantity: str | MISSING = Field(
        MISSING,
        alias='restrictedQuantity',
        description='Khối lượng bị hạn chế giao dịch.',
    )
    """Khối lượng bị hạn chế giao dịch."""


class PositionResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    equity: list[EquityItem] = Field(
        ..., description='Thông tin hoặc danh sách vị thế tài khoản cơ sở.'
    )
    """Thông tin hoặc danh sách vị thế tài khoản cơ sở."""

    derivative: dict[str, Any] | None = Field(
        ..., description='Thông tin tài khoản hoặc vị thế phái sinh.'
    )
    """Thông tin tài khoản hoặc vị thế phái sinh."""


class EquityModel(BaseModel):
    """
    Thông tin PP/MMR của tài khoản cơ sở.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch.'
    )
    """Số tài khoản giao dịch."""

    dividend: str | MISSING = Field(MISSING, description='Cổ tức.')
    """Cổ tức."""

    loan_value: str | MISSING = Field(
        MISSING, alias='loanValue', description='Giá trị khoản vay.'
    )
    """Giá trị khoản vay."""

    total_debt: str | MISSING = Field(
        MISSING, alias='totalDebt', description='Tổng dư nợ.'
    )
    """Tổng dư nợ."""

    debt: str | MISSING = Field(MISSING, description='Dư nợ.')
    """Dư nợ."""

    liability: str | MISSING = Field(MISSING, description='Dư nợ phải trả.')
    """Dư nợ phải trả."""

    liability_ssi: str | MISSING = Field(
        MISSING, alias='liabilitySSI', description='Dư nợ phải trả tại SSI.'
    )
    """Dư nợ phải trả tại SSI."""

    net_liability: str | MISSING = Field(
        MISSING, alias='netLiability', description='Tổng dư nợ ròng.'
    )
    """Tổng dư nợ ròng."""

    fees: str | MISSING = Field(MISSING, description='Phí giao dịch.')
    """Phí giao dịch."""

    interest_ssi: str | MISSING = Field(
        MISSING, alias='interestSSI', description='Lãi suất vay tại SSI.'
    )
    """Lãi suất vay tại SSI."""

    interest_spv: str | MISSING = Field(
        MISSING, alias='interestSPV', description='Lãi suất vay tại SPV.'
    )
    """Lãi suất vay tại SPV."""

    withdrawable: str | MISSING = Field(MISSING, description='Số tiền có thể rút.')
    """Số tiền có thể rút."""

    ee: str | MISSING = Field(MISSING, description='Equity Excess.')
    """Equity Excess."""

    ee50: str | MISSING = Field(MISSING, description='EE tại tỷ lệ 50%.')
    """EE tại tỷ lệ 50%."""

    ee60: str | MISSING = Field(MISSING, description='EE tại tỷ lệ 60%.')
    """EE tại tỷ lệ 60%."""

    ee70: str | MISSING = Field(MISSING, description='EE tại tỷ lệ 70%.')
    """EE tại tỷ lệ 70%."""

    ee80: str | MISSING = Field(MISSING, description='EE tại tỷ lệ 80%.')
    """EE tại tỷ lệ 80%."""

    ee90: str | MISSING = Field(MISSING, description='EE tại tỷ lệ 90%.')
    """EE tại tỷ lệ 90%."""

    action: str | MISSING = Field(MISSING, description='Hành động hiện tại.')
    """Hành động hiện tại."""

    action_ssi: str | MISSING = Field(
        MISSING, alias='actionSSI', description='Hành động hiện tại tại SSI.'
    )
    """Hành động hiện tại tại SSI."""

    equity: str | MISSING = Field(MISSING, description='Vốn chủ sở hữu.')
    """Vốn chủ sở hữu."""

    equity_ssi: str | MISSING = Field(
        MISSING, alias='equitySSI', description='Vốn chủ sở hữu tại SSI.'
    )
    """Vốn chủ sở hữu tại SSI."""

    ee_cash: str | MISSING = Field(
        MISSING, alias='eeCash', description='EE mặt bằng tiền mặt.'
    )
    """EE mặt bằng tiền mặt."""

    hold_subscription: str | MISSING = Field(
        MISSING,
        alias='holdSubscription',
        description='Số tiền giữ lại cho đăng ký phát hành.',
    )
    """Số tiền giữ lại cho đăng ký phát hành."""

    bank_balance: str | MISSING = Field(
        MISSING, alias='bankBalance', description='Số dư ngân hàng.'
    )
    """Số dư ngân hàng."""

    on_hold_cash: str | MISSING = Field(
        MISSING, alias='onHoldCash', description='Tiền mặt đang bị giữ.'
    )
    """Tiền mặt đang bị giữ."""

    doverdue: str | MISSING = Field(MISSING, description='Quá hạn.')
    """Quá hạn."""

    doverdue_ssi: str | None | MISSING = Field(MISSING, description='Quá hạn tại SSI.')
    """Quá hạn tại SSI."""

    account_balance: str | MISSING = Field(
        MISSING, alias='accountBalance', description='Số dư tài khoản.'
    )
    """Số dư tài khoản."""

    d: str | MISSING = Field(MISSING, description='Dư nợ chính.')
    """Dư nợ chính."""

    dspv: str | MISSING = Field(MISSING, description='Dư nợ SPV.')
    """Dư nợ SPV."""

    dssi: str | MISSING = Field(MISSING, description='Dư nợ SSI.')
    """Dư nợ SSI."""

    cia: str | MISSING = Field(MISSING, description='CIA - Current Investment Account.')
    """CIA - Current Investment Account."""

    collateral_asset: str | MISSING = Field(
        MISSING, alias='collateralAsset', description='Tài sản thế chấp.'
    )
    """Tài sản thế chấp."""

    collateral_asset_ssi: str | MISSING = Field(
        MISSING, alias='collateralAssetSSI', description='Tài sản thế chấp tại SSI.'
    )
    """Tài sản thế chấp tại SSI."""

    total_assets: str | MISSING = Field(
        MISSING, alias='totalAssets', description='Tổng tài sản.'
    )
    """Tổng tài sản."""

    total_equity: str | MISSING = Field(
        MISSING, alias='totalEquity', description='Tổng vốn chủ sở hữu.'
    )
    """Tổng vốn chủ sở hữu."""

    total_equity_ssi: str | MISSING = Field(
        MISSING, alias='totalEquitySSI', description='Tổng vốn chủ sở hữu tại SSI.'
    )
    """Tổng vốn chủ sở hữu tại SSI."""

    call_lmv: str | MISSING = Field(
        MISSING, alias='callLMV', description='LMV trong trạng thái Margin Call.'
    )
    """LMV trong trạng thái Margin Call."""

    force_lmv: str | MISSING = Field(
        MISSING, alias='forceLMV', description='LMV trong trạng thái bắt buộc bán.'
    )
    """LMV trong trạng thái bắt buộc bán."""

    call_lmvssi: str | MISSING = Field(
        MISSING, alias='callLMVSSI', description='LMV Margin Call tại SSI.'
    )
    """LMV Margin Call tại SSI."""

    force_lmvssi: str | MISSING = Field(
        MISSING, alias='forceLMVSSI', description='LMV bắt buộc bán tại SSI.'
    )
    """LMV bắt buộc bán tại SSI."""

    lmv: str | MISSING = Field(
        MISSING, description='Long Market Value - Giá trị thị trường của vị thế dài.'
    )
    """Long Market Value - Giá trị thị trường của vị thế dài."""

    lmv_margin: str | MISSING = Field(
        MISSING, alias='lmvMargin', description='LMV áp dụng ký quỹ.'
    )
    """LMV áp dụng ký quỹ."""

    lmv_margin_ssi: str | MISSING = Field(
        MISSING, alias='lmvMarginSSI', description='LMV ký quỹ tại SSI.'
    )
    """LMV ký quỹ tại SSI."""

    lmv_non_marginable: str | MISSING = Field(
        MISSING, alias='lmvNonMarginable', description='LMV không áp dụng ký quỹ.'
    )
    """LMV không áp dụng ký quỹ."""

    lmv_non_marginable_ssi: str | MISSING = Field(
        MISSING, alias='lmvNonMarginableSSI', description='LMV không ký quỹ tại SSI.'
    )
    """LMV không ký quỹ tại SSI."""

    pre_loan: str | MISSING = Field(
        MISSING, alias='preLoan', description='Khoản vay trước.'
    )
    """Khoản vay trước."""

    margin_ratio: str | MISSING = Field(
        MISSING, alias='marginRatio', description='Tỷ lệ ký quỹ.'
    )
    """Tỷ lệ ký quỹ."""

    margin_ratio_ssi: str | MISSING = Field(
        MISSING, alias='marginRatioSSI', description='Tỷ lệ ký quỹ tại SSI.'
    )
    """Tỷ lệ ký quỹ tại SSI."""

    purchasing_power: str | MISSING = Field(
        MISSING, alias='purchasingPower', description='Sức mua.'
    )
    """Sức mua."""

    ee_origin: str | MISSING = Field(MISSING, alias='eeOrigin', description='EE gốc.')
    """EE gốc."""

    buy_unmatched: str | MISSING = Field(
        MISSING, alias='buyUnmatched', description='Khối lượng mua chưa khớp.'
    )
    """Khối lượng mua chưa khớp."""

    sell_unmatched: str | MISSING = Field(
        MISSING, alias='sellUnmatched', description='Khối lượng bán chưa khớp.'
    )
    """Khối lượng bán chưa khớp."""

    buy_t0: str | MISSING = Field(
        MISSING, alias='buyT0', description='Khối lượng mua T+0 chưa thanh toán.'
    )
    """Khối lượng mua T+0 chưa thanh toán."""

    sell_t0: str | MISSING = Field(
        MISSING, alias='sellT0', description='Khối lượng bán T+0 chưa thanh toán.'
    )
    """Khối lượng bán T+0 chưa thanh toán."""

    sell_t1: str | MISSING = Field(
        MISSING, alias='sellT1', description='Khối lượng bán T+1 chưa thanh toán.'
    )
    """Khối lượng bán T+1 chưa thanh toán."""

    sell_t2: str | MISSING = Field(
        MISSING, alias='sellT2', description='Khối lượng bán T+2 chưa thanh toán.'
    )
    """Khối lượng bán T+2 chưa thanh toán."""

    buy_t1: str | MISSING = Field(
        MISSING, alias='buyT1', description='Khối lượng mua T+1 chưa thanh toán.'
    )
    """Khối lượng mua T+1 chưa thanh toán."""

    buy_t2: str | MISSING = Field(
        MISSING, alias='buyT2', description='Khối lượng mua T+2 chưa thanh toán.'
    )
    """Khối lượng mua T+2 chưa thanh toán."""

    credit_limit: str | MISSING = Field(
        MISSING, alias='creditLimit', description='Hạn mức tín dụng.'
    )
    """Hạn mức tín dụng."""

    margin_call_lmv_sold: str | MISSING = Field(
        MISSING, alias='marginCallLMVSold', description='LMV bán trong Margin Call.'
    )
    """LMV bán trong Margin Call."""

    margin_call_lmv_sold_ssi: str | MISSING = Field(
        MISSING,
        alias='marginCallLMVSoldSSI',
        description='LMV bán Margin Call tại SSI.',
    )
    """LMV bán Margin Call tại SSI."""

    margin_call: str | MISSING = Field(
        MISSING, alias='marginCall', description='Margin Call.'
    )
    """Margin Call."""

    margin_call_ssi: str | MISSING = Field(
        MISSING, alias='marginCallSSI', description='Margin Call tại SSI.'
    )
    """Margin Call tại SSI."""

    collateral_a: str | MISSING = Field(
        MISSING, alias='collateralA', description='Tài sản thế chấp A (loại A).'
    )
    """Tài sản thế chấp A (loại A)."""

    collateral_non: str | MISSING = Field(
        MISSING, alias='collateralNon', description='Tài sản thế chấp không phải A.'
    )
    """Tài sản thế chấp không phải A."""

    collateral_assi: str | MISSING = Field(
        MISSING, alias='collateralASSI', description='Tài sản thế chấp A tại SSI.'
    )
    """Tài sản thế chấp A tại SSI."""

    collateral_non_ssi: str | MISSING = Field(
        MISSING,
        alias='collateralNonSSI',
        description='Tài sản thế chấp không A tại SSI.',
    )
    """Tài sản thế chấp không A tại SSI."""

    call_margin: str | MISSING = Field(
        MISSING, alias='callMargin', description='Margin Call.'
    )
    """Margin Call."""

    call_forcesell: str | MISSING = Field(
        MISSING, alias='callForcesell', description='Bắt buộc bán.'
    )
    """Bắt buộc bán."""

    call_margin_ssi: str | MISSING = Field(
        MISSING, alias='callMarginSSI', description='Margin Call tại SSI.'
    )
    """Margin Call tại SSI."""

    call_forcesell_ssi: str | MISSING = Field(
        MISSING, alias='callForcesellSSI', description='Bắt buộc bán tại SSI.'
    )
    """Bắt buộc bán tại SSI."""

    ar: str | MISSING = Field(MISSING, description='Account Ratio.')
    """Account Ratio."""


class DerivativeModel(BaseModel):
    """
    Thông tin PP/MMR của tài khoản phái sinh.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tài khoản giao dịch phái sinh.'
    )
    """Số tài khoản giao dịch phái sinh."""

    account_balance: str | MISSING = Field(
        MISSING, alias='accountBalance', description='Số dư tài khoản phái sinh.'
    )
    """Số dư tài khoản phái sinh."""

    fee: str | MISSING = Field(MISSING, description='Phí giao dịch phái sinh.')
    """Phí giao dịch phái sinh."""

    commission: str | MISSING = Field(
        MISSING, description='Hoa hồng giao dịch phái sinh.'
    )
    """Hoa hồng giao dịch phái sinh."""

    interest: str | MISSING = Field(MISSING, description='Lãi suất vay phái sinh.')
    """Lãi suất vay phái sinh."""

    loan: str | MISSING = Field(MISSING, description='Dư nợ vay phái sinh.')
    """Dư nợ vay phái sinh."""

    delivery_amount: str | MISSING = Field(
        MISSING, alias='deliveryAmount', description='Số tiền giao hàng phái sinh.'
    )
    """Số tiền giao hàng phái sinh."""

    floating_pl: str | MISSING = Field(
        MISSING, alias='floatingPL', description='Lãi/lỗ chưa thực hiện phái sinh.'
    )
    """Lãi/lỗ chưa thực hiện phái sinh."""

    trading_pl: str | MISSING = Field(
        MISSING, alias='tradingPL', description='Lãi/lỗ đã thực hiện phái sinh.'
    )
    """Lãi/lỗ đã thực hiện phái sinh."""

    total_pl: str | MISSING = Field(
        MISSING, alias='totalPL', description='Tổng lãi/lỗ phái sinh.'
    )
    """Tổng lãi/lỗ phái sinh."""

    marginable: str | MISSING = Field(MISSING, description='Khối lượng áp dụng ký quỹ.')
    """Khối lượng áp dụng ký quỹ."""

    depositable: str | MISSING = Field(MISSING, description='Khối lượng có thể ký quỹ.')
    """Khối lượng có thể ký quỹ."""

    rc_call: str | MISSING = Field(
        MISSING, alias='rcCall', description='RC Call - Margin Call.'
    )
    """RC Call - Margin Call."""

    withdrawable: str | MISSING = Field(
        MISSING, description='Số tiền có thể rút từ tài khoản phái sinh.'
    )
    """Số tiền có thể rút từ tài khoản phái sinh."""

    non_cash_drawable_rc_call: str | MISSING = Field(
        MISSING,
        alias='nonCashDrawableRCCall',
        description='Tiền không mặt có thể rút trong RC Call.',
    )
    """Tiền không mặt có thể rút trong RC Call."""

    cash_ssi: str | MISSING = Field(
        MISSING,
        alias='cashSSI',
        description='Tiền mặt trong tài khoản phái sinh tại SSI.',
    )
    """Tiền mặt trong tài khoản phái sinh tại SSI."""

    valid_non_cash_ssi: str | MISSING = Field(
        MISSING, alias='validNonCashSSI', description='Tiền không mặt hợp lệ tại SSI.'
    )
    """Tiền không mặt hợp lệ tại SSI."""

    total_asset_ssi: str | MISSING = Field(
        MISSING, alias='totalAssetSSI', description='Tổng tài sản phái sinh tại SSI.'
    )
    """Tổng tài sản phái sinh tại SSI."""

    withdrawable_ssi: str | MISSING = Field(
        MISSING, alias='withdrawableSSI', description='Số tiền có thể rút từ SSI.'
    )
    """Số tiền có thể rút từ SSI."""

    ee_ssi: str | MISSING = Field(
        MISSING, alias='eeSSI', description='Equity Excess tại SSI.'
    )
    """Equity Excess tại SSI."""

    cash_vsdc: str | MISSING = Field(
        MISSING,
        alias='cashVSDC',
        description='Tiền mặt trong tài khoản phái sinh tại VSDC.',
    )
    """Tiền mặt trong tài khoản phái sinh tại VSDC."""

    valid_non_cash_vsdc: str | MISSING = Field(
        MISSING, alias='validNonCashVSDC', description='Tiền không mặt hợp lệ tại VSDC.'
    )
    """Tiền không mặt hợp lệ tại VSDC."""

    total_asset_vsdc: str | MISSING = Field(
        MISSING, alias='totalAssetVSDC', description='Tổng tài sản phái sinh tại VSDC.'
    )
    """Tổng tài sản phái sinh tại VSDC."""

    withdrawable_vsdc: str | MISSING = Field(
        MISSING, alias='withdrawableVSDC', description='Số tiền có thể rút từ VSDC.'
    )
    """Số tiền có thể rút từ VSDC."""

    ee_vsdc: str | MISSING = Field(
        MISSING, alias='eeVSDC', description='Equity Excess tại VSDC.'
    )
    """Equity Excess tại VSDC."""

    spread_margin_ssi: str | MISSING = Field(
        MISSING, alias='spreadMarginSSI', description='Spread Margin tại SSI.'
    )
    """Spread Margin tại SSI."""

    delivery_margin_ssi: str | MISSING = Field(
        MISSING, alias='deliveryMarginSSI', description='Delivery Margin tại SSI.'
    )
    """Delivery Margin tại SSI."""

    margin_req_ssi: str | MISSING = Field(
        MISSING, alias='marginReqSSI', description='Margin Requirement tại SSI.'
    )
    """Margin Requirement tại SSI."""

    account_ratio_ssi: str | MISSING = Field(
        MISSING, alias='accountRatioSSI', description='Account Ratio tại SSI.'
    )
    """Account Ratio tại SSI."""

    used_limit_warning_level1_ssi: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel1SSI',
        description='Mức cảnh báo sử dụng hạn mức Level 1 tại SSI.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 1 tại SSI."""

    used_limit_warning_level2_ssi: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel2SSI',
        description='Mức cảnh báo sử dụng hạn mức Level 2 tại SSI.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 2 tại SSI."""

    used_limit_warning_level3_ssi: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel3SSI',
        description='Mức cảnh báo sử dụng hạn mức Level 3 tại SSI.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 3 tại SSI."""

    margin_call_ssi: str | MISSING = Field(
        MISSING, alias='marginCallSSI', description='Margin Call tại SSI.'
    )
    """Margin Call tại SSI."""

    spread_margin_vsdc: str | MISSING = Field(
        MISSING, alias='spreadMarginVSDC', description='Spread Margin tại VSDC.'
    )
    """Spread Margin tại VSDC."""

    delivery_margin_vsdc: str | MISSING = Field(
        MISSING, alias='deliveryMarginVSDC', description='Delivery Margin tại VSDC.'
    )
    """Delivery Margin tại VSDC."""

    margin_req_vsdc: str | MISSING = Field(
        MISSING, alias='marginReqVSDC', description='Margin Requirement tại VSDC.'
    )
    """Margin Requirement tại VSDC."""

    account_ratio_vsdc: str | MISSING = Field(
        MISSING, alias='accountRatioVSDC', description='Account Ratio tại VSDC.'
    )
    """Account Ratio tại VSDC."""

    used_limit_warning_level1_vsdc: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel1VSDC',
        description='Mức cảnh báo sử dụng hạn mức Level 1 tại VSDC.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 1 tại VSDC."""

    used_limit_warning_level2_vsdc: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel2VSDC',
        description='Mức cảnh báo sử dụng hạn mức Level 2 tại VSDC.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 2 tại VSDC."""

    used_limit_warning_level3_vsdc: str | MISSING = Field(
        MISSING,
        alias='usedLimitWarningLevel3VSDC',
        description='Mức cảnh báo sử dụng hạn mức Level 3 tại VSDC.',
    )
    """Mức cảnh báo sử dụng hạn mức Level 3 tại VSDC."""

    margin_call_vsdc: str | MISSING = Field(
        MISSING, alias='marginCallVSDC', description='Margin Call tại VSDC.'
    )
    """Margin Call tại VSDC."""

    total_equity: str | MISSING = Field(
        MISSING, alias='totalEquity', description='Tổng vốn chủ sở hữu phái sinh.'
    )
    """Tổng vốn chủ sở hữu phái sinh."""

    ext_interest: str | MISSING = Field(
        MISSING, alias='extInterest', description='Lãi suất vay ngoài phái sinh.'
    )
    """Lãi suất vay ngoài phái sinh."""


class PpmmrAccountResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    equity: EquityModel | None = Field(
        ..., description='Thông tin PP/MMR của tài khoản cơ sở.'
    )
    """Thông tin PP/MMR của tài khoản cơ sở."""

    derivative: DerivativeModel | None = Field(
        ..., description='Thông tin PP/MMR của tài khoản phái sinh.'
    )
    """Thông tin PP/MMR của tài khoản phái sinh."""
