# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel
from pydantic.experimental.missing_sentinel import MISSING


class PricingPolicyLadderValue(BaseModel):
    """
    Mức lãi suất trong một bậc của gói lãi suất.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='Mã mức lãi suất.')
    """Mã mức lãi suất."""

    rate: float | MISSING = Field(MISSING, description='Mức lãi suất.')
    """Mức lãi suất."""

    start_date: int | MISSING = Field(
        MISSING, alias='startDate', description='Ngày bắt đầu của khoảng áp dụng.'
    )
    """Ngày bắt đầu của khoảng áp dụng."""

    due_date: int | MISSING = Field(
        MISSING, alias='dueDate', description='Ngày kết thúc của khoảng áp dụng.'
    )
    """Ngày kết thúc của khoảng áp dụng."""


class PricingPolicyState(BaseModel):
    """
    Trạng thái áp dụng của gói lãi suất.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    state_id: int | MISSING = Field(
        MISSING, alias='stateId', description='Mã trạng thái.'
    )
    """Mã trạng thái."""

    name: str | MISSING = Field(MISSING, description='Tên trạng thái.')
    """Tên trạng thái."""

    status: str | MISSING = Field(MISSING, description='Trạng thái áp dụng.')
    """Trạng thái áp dụng."""

    is_applied_for_existing: bool | MISSING = Field(
        MISSING,
        alias='isAppliedForExisting',
        description='Có áp dụng cho tài khoản hiện hữu hay không.',
    )
    """Có áp dụng cho tài khoản hiện hữu hay không."""

    undue_interest_type: str | MISSING = Field(
        MISSING, alias='undueInterestType', description='Loại lãi suất trong hạn.'
    )
    """Loại lãi suất trong hạn."""

    undue_ladder_value: list[PricingPolicyLadderValue] | MISSING = Field(
        MISSING,
        alias='undueLadderValue',
        description='Các mức lãi suất theo bậc trong hạn.',
    )
    """Các mức lãi suất theo bậc trong hạn."""

    overdue_interest: float | MISSING = Field(
        MISSING, alias='overdueInterest', description='Lãi suất quá hạn.'
    )
    """Lãi suất quá hạn."""

    extension_interest: float | MISSING = Field(
        MISSING, alias='extensionInterest', description='Lãi suất gia hạn.'
    )
    """Lãi suất gia hạn."""

    valid_from: date | MISSING = Field(
        MISSING, alias='validFrom', description='Ngày bắt đầu hiệu lực.'
    )
    """Ngày bắt đầu hiệu lực."""

    valid_to: date | MISSING = Field(
        MISSING, alias='validTo', description='Ngày kết thúc hiệu lực.'
    )
    """Ngày kết thúc hiệu lực."""


class CashInvestmentItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bod_balance: float | MISSING = Field(
        MISSING, alias='bodBalance', description='Tiền mặt tại TCBS.'
    )
    """Tiền mặt tại TCBS."""

    cash_balance: float | MISSING = Field(
        MISSING, alias='cashBalance', description='Tiền mặt.'
    )
    """Tiền mặt."""

    pp0for_bf: float | MISSING = Field(
        MISSING, alias='pp0forBF', description='Sức mua cơ bản cho sản phẩm BOND/FUND.'
    )
    """Sức mua cơ bản cho sản phẩm BOND/FUND."""

    bank_avl_balance_bf: float | MISSING = Field(
        MISSING,
        alias='bankAvlBalanceBF',
        description='Tổng số dư khả dụng IA cho BOND/FUND.',
    )
    """Tổng số dư khả dụng IA cho BOND/FUND."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""


class MarginSureViewItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: float | MISSING = Field(MISSING, description='Id gói marginsure.')
    """Id gói marginsure."""

    name: str | MISSING = Field(MISSING, description='Tên gói marginsure.')
    """Tên gói marginsure."""

    code: str | MISSING = Field(MISSING, description='Mã gói marginsure.')
    """Mã gói marginsure."""

    subscription_fee: float | MISSING = Field(
        MISSING, alias='subscriptionFee', description='Phí tham gia.'
    )
    """Phí tham gia."""

    status: str | MISSING = Field(MISSING, description='Trạng thái đăng ký gói.')
    """Trạng thái đăng ký gói."""


class TplusItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: float | MISSING = Field(MISSING, description='ID gói T+.')
    """ID gói T+."""

    name: str | MISSING = Field(MISSING, description='Tên gói T+.')
    """Tên gói T+."""

    first_rate: float | MISSING = Field(
        MISSING, alias='firstRate', description='Lãi suất bậc 1 của gói T+.'
    )
    """Lãi suất bậc 1 của gói T+."""

    status: str | MISSING = Field(MISSING, description='Trạng thái gói T+.')
    """Trạng thái gói T+."""


class PositionClosedItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã hợp đồng.')
    """Mã hợp đồng."""

    side: str | MISSING = Field(MISSING, description='Loại giao dịch (B/S).')
    """Loại giao dịch (B/S)."""

    open_price: float | MISSING = Field(
        MISSING, alias='openPrice', description='Giá mở TB.'
    )
    """Giá mở TB."""

    close_price: float | MISSING = Field(
        MISSING, alias='closePrice', description='Giá đóng TB.'
    )
    """Giá đóng TB."""

    close_position: str | MISSING = Field(
        MISSING, alias='closePosition', description='Số vị thế đóng / tổng.'
    )
    """Số vị thế đóng / tổng."""

    fee: float | MISSING = Field(MISSING, description='Phí giao dịch.')
    """Phí giao dịch."""

    tax: float | MISSING = Field(MISSING, description='Thuế.')
    """Thuế."""

    close_vm: float | MISSING = Field(
        MISSING, alias='closeVM', description='Lãi lỗ đã đóng.'
    )
    """Lãi lỗ đã đóng."""

    unrealize: float | MISSING = Field(MISSING, description='Lãi lỗ chưa đóng.')
    """Lãi lỗ chưa đóng."""

    close_pc: float | MISSING = Field(
        MISSING, alias='closePC', description='% lãi/lỗ đã đóng.'
    )
    """% lãi/lỗ đã đóng."""

    time: str | MISSING = Field(MISSING, description='Thời gian đóng cuối.')
    """Thời gian đóng cuối."""


class PositionOpenItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã hợp đồng.')
    """Mã hợp đồng."""

    im: str | MISSING = Field(MISSING, description='Tỷ lệ ký quỹ.')
    """Tỷ lệ ký quỹ."""

    deliver: int | MISSING = Field(MISSING, description='Số lượng vị thế SHORT.')
    """Số lượng vị thế SHORT."""

    receive: int | MISSING = Field(MISSING, description='Số lượng vị thế LONG.')
    """Số lượng vị thế LONG."""

    net: int | MISSING = Field(
        MISSING, description='Vị thế mở (>0 = LONG, <0 = SHORT).'
    )
    """Vị thế mở (>0 = LONG, <0 = SHORT)."""

    side: str | MISSING = Field(
        MISSING, description='Loại vị thế: L = Long, S = Short.'
    )
    """Loại vị thế: L = Long, S = Short."""

    last_price: float | MISSING = Field(
        MISSING, alias='lastPrice', description='Giá thị trường.'
    )
    """Giá thị trường."""

    im_value: float | MISSING = Field(
        MISSING, alias='imValue', description='Giá trị ký quỹ ban đầu.'
    )
    """Giá trị ký quỹ ban đầu."""

    vm_value: float | MISSING = Field(MISSING, alias='vmValue', description='Lãi/lỗ.')
    """Lãi/lỗ."""

    mr_value: float | MISSING = Field(
        MISSING, alias='mrValue', description='Giá trị ký quỹ yêu cầu.'
    )
    """Giá trị ký quỹ yêu cầu."""

    duedate: str | MISSING = Field(MISSING, description='Ngày đáo hạn.')
    """Ngày đáo hạn."""

    pc_remain: str | MISSING = Field(MISSING, description='% lãi/lỗ vị thế mở.')
    """% lãi/lỗ vị thế mở."""


class BankSubAccount(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""

    account_name: str | MISSING = Field(
        MISSING, alias='accountName', description='Tên chủ tài khoản.'
    )
    """Tên chủ tài khoản."""

    bank_code: str | None | MISSING = Field(
        MISSING, alias='bankCode', description='Mã ngân hàng (có thể null).'
    )
    """Mã ngân hàng (có thể null)."""

    account_type: str | MISSING = Field(
        MISSING,
        alias='accountType',
        description='Loại tiểu khoản: NORMAL, MARGIN, DERIVATIVE.',
    )
    """Loại tiểu khoản: NORMAL, MARGIN, DERIVATIVE."""

    account_type_name: str | MISSING = Field(
        MISSING, alias='accountTypeName', description='Tên loại tiểu khoản.'
    )
    """Tên loại tiểu khoản."""

    status: str | MISSING = Field(MISSING, description='Trạng thái tiểu khoản.')
    """Trạng thái tiểu khoản."""

    is_default: str | MISSING = Field(
        MISSING, alias='isDefault', description='Là tiểu khoản mặc định (Y/N).'
    )
    """Là tiểu khoản mặc định (Y/N)."""


class Insurance(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    insurance_name: str | MISSING = Field(
        MISSING, alias='insuranceName', description='Tên gói marginsure.'
    )
    """Tên gói marginsure."""

    insurance_code: str | MISSING = Field(
        MISSING, alias='insuranceCode', description='Mã gói marginsure.'
    )
    """Mã gói marginsure."""

    insurance_fee: float | MISSING = Field(
        MISSING, alias='insuranceFee', description='Phí marginsure.'
    )
    """Phí marginsure."""


class RiskPolicy(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    initial_margin: float | MISSING = Field(
        MISSING, alias='initialMargin', description='Tỷ lệ ký quỹ ban đầu.'
    )
    """Tỷ lệ ký quỹ ban đầu."""

    maintenance_margin: float | MISSING = Field(
        MISSING, alias='maintenanceMargin', description='Tỷ lệ duy trì.'
    )
    """Tỷ lệ duy trì."""

    liquidation_margin: float | MISSING = Field(
        MISSING, alias='liquidationMargin', description='Tỷ lệ cảnh báo.'
    )
    """Tỷ lệ cảnh báo."""


class RiskStatus(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: str | MISSING = Field(MISSING, description='Trạng thái RTT.')
    """Trạng thái RTT."""

    description: str | MISSING = Field(MISSING, description='Mô tả trạng thái RTT.')
    """Mô tả trạng thái RTT."""


class StatusResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Tên lệnh phản hồi.')
    """Tên lệnh phản hồi."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: dict[str, Any] | MISSING = Field(
        MISSING, description='Dữ liệu tổng quan tiền và ký quỹ.'
    )
    """Dữ liệu tổng quan tiền và ký quỹ."""


class StockAssetItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán.')
    """Mã chứng khoán."""

    quantity: int | MISSING = Field(MISSING, description='Số lượng nắm giữ.')
    """Số lượng nắm giữ."""

    avg_price: float | MISSING = Field(
        MISSING, alias='avgPrice', description='Giá trung bình.'
    )
    """Giá trung bình."""

    market_value: float | MISSING = Field(
        MISSING, alias='marketValue', description='Giá trị thị trường.'
    )
    """Giá trị thị trường."""


class PpseResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    purchasing_power: float | MISSING = Field(
        MISSING, alias='purchasingPower', description='Sức mua khả dụng.'
    )
    """Sức mua khả dụng."""

    max_quantity: int | MISSING = Field(
        MISSING, alias='maxQuantity', description='Số lượng tối đa có thể mua.'
    )
    """Số lượng tối đa có thể mua."""


class PpseBySymbolResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pp0: float | MISSING = Field(MISSING, description='Sức mua cơ bản.')
    """Sức mua cơ bản."""

    max_qtty: float | MISSING = Field(
        MISSING, alias='maxQtty', description='Số lượng tối đa có thể mua.'
    )
    """Số lượng tối đa có thể mua."""


class PpseBySymbolPriceResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pp0: float | MISSING = Field(MISSING, description='Sức mua cơ bản.')
    """Sức mua cơ bản."""

    max_qtty: float | MISSING = Field(
        MISSING,
        alias='maxQtty',
        description='Số lượng tối đa có thể mua tại mức giá này.',
    )
    """Số lượng tối đa có thể mua tại mức giá này."""


class MarginInfoItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    release_date: str | MISSING = Field(
        MISSING, alias='releaseDate', description='Ngày giải ngân.'
    )
    """Ngày giải ngân."""

    over_due_date: str | MISSING = Field(
        MISSING, alias='overDueDate', description='Ngày đáo hạn.'
    )
    """Ngày đáo hạn."""

    released_amount: float | MISSING = Field(
        MISSING, alias='releasedAmount', description='Gốc giải ngân.'
    )
    """Gốc giải ngân."""

    print_amount: float | MISSING = Field(
        MISSING, alias='printAmount', description='Nợ gốc hiện tại.'
    )
    """Nợ gốc hiện tại."""

    int_amount: float | MISSING = Field(
        MISSING, alias='intAmount', description='Nợ lãi và phí hiện tại.'
    )
    """Nợ lãi và phí hiện tại."""

    remaining_interest_fee: float | MISSING = Field(
        MISSING,
        alias='remainingInterestFee',
        description='Tổng nợ lãi và phí hiện tại.',
    )
    """Tổng nợ lãi và phí hiện tại."""

    paid_interest_fee: float | MISSING = Field(
        MISSING, alias='paidInterestFee', description='Tổng lãi và phí đã trả.'
    )
    """Tổng lãi và phí đã trả."""

    rate2: float | MISSING = Field(MISSING, description='Lãi suất.')
    """Lãi suất."""

    released_day: float | MISSING = Field(
        MISSING, alias='releasedDay', description='Số ngày vay.'
    )
    """Số ngày vay."""

    paid_fee: float | MISSING = Field(
        MISSING, alias='paidFee', description='Phí đã trả.'
    )
    """Phí đã trả."""

    remaining_fee: float | MISSING = Field(
        MISSING, alias='remainingFee', description='Phí còn lại.'
    )
    """Phí còn lại."""


class CashDepositUpdateResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Loại bút toán.')
    """Loại bút toán."""

    rc: str | MISSING = Field(
        MISSING, description='Mã kết quả. 1: thành công, < 0: lỗi.'
    )
    """Mã kết quả. 1: thành công, < 0: lỗi."""

    rs: str | MISSING = Field(MISSING, description='Chi tiết lỗi.')
    """Chi tiết lỗi."""

    o_id: str | MISSING = Field(MISSING, alias='oID', description='ID giao dịch.')
    """ID giao dịch."""

    data: list[dict[str, Any]] | MISSING = Field(
        MISSING, description='Dữ liệu trả về (chứa transactionId).'
    )
    """Dữ liệu trả về (chứa transactionId)."""


class CashWithdrawUpdateResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Loại bút toán.')
    """Loại bút toán."""

    rc: str | MISSING = Field(
        MISSING, description='Mã kết quả. 1: thành công, < 0: lỗi.'
    )
    """Mã kết quả. 1: thành công, < 0: lỗi."""

    rs: str | MISSING = Field(MISSING, description='Chi tiết lỗi.')
    """Chi tiết lỗi."""

    o_id: str | MISSING = Field(MISSING, alias='oID', description='ID giao dịch.')
    """ID giao dịch."""

    data: list[dict[str, Any]] | None | MISSING = Field(
        MISSING, description='Dữ liệu trả về.'
    )
    """Dữ liệu trả về."""


class StockTransferResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: str | MISSING = Field(
        MISSING, description='Code trả về, 200 là thành công, khác 200 là lỗi.'
    )
    """Code trả về, 200 là thành công, khác 200 là lỗi."""

    message: str | MISSING = Field(MISSING, description='Mô tả mã lỗi nếu có.')
    """Mô tả mã lỗi nếu có."""


class SubAccountStatus(StrEnum):
    """
    Trạng thái tiểu khoản.

    - `A`: Được phép đặt lệnh
    - `P`: Không được phép
    - `C`: Đã đóng
    - `B`: Phong tỏa
    - `N`: Chờ đóng
    - `R`: Từ chối
    - `T`: Chờ cập nhật
    """

    ACTIVE = 'A'
    """Được phép đặt lệnh"""

    PENDING = 'P'
    """Không được phép"""

    CLOSED = 'C'
    """Đã đóng"""

    BLOCKED = 'B'
    """Phong tỏa"""

    NOTICE = 'N'
    """Chờ đóng"""

    REJECTED = 'R'
    """Từ chối"""

    TENTATIVE = 'T'
    """Chờ cập nhật"""


class SubAccountType(StrEnum):
    """
    Loại tiểu khoản.

    - `normal`: Tài khoản thường
    - `margin`: Tài khoản ký quỹ
    - `copier`: Tài khoản copy trade
    - `trader`: Tài khoản trader
    - `CHILD`: Tài khoản con
    - `CW`: Chứng quyền
    - `SPW`: Tài khoản SPW
    - `SPT`: Tài khoản SPT
    """

    NORMAL = 'normal'
    """Tài khoản thường"""

    MARGIN = 'margin'
    """Tài khoản ký quỹ"""

    COPIER = 'copier'
    """Tài khoản copy trade"""

    TRADER = 'trader'
    """Tài khoản trader"""

    CHILD = 'CHILD'
    """Tài khoản con"""

    CW = 'CW'
    """Chứng quyền"""

    SPW = 'SPW'
    """Tài khoản SPW"""

    SPT = 'SPT'
    """Tài khoản SPT"""


class DerivativeGetType(StrEnum):
    """
    Phạm vi dữ liệu tổng quan phái sinh.

    - `0`: Lấy toàn bộ
    - `1`: Chỉ lấy tiền
    """

    ALL = '0'
    """Lấy toàn bộ"""

    CASH_ONLY = '1'
    """Chỉ lấy tiền"""


class AccountsPostDepositRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Số tài khoản lưu ký.')
    """Số tài khoản lưu ký."""

    sub_account_id: str = Field(
        ..., alias='subAccountId', description='Phái sinh Số tiểu khoản.'
    )
    """Phái sinh Số tiểu khoản."""

    amount: float = Field(..., description='Deposit margin Số tiền.')
    """Deposit margin Số tiền."""

    payment_content: str | MISSING = Field(
        MISSING, alias='paymentContent', description='Deposit Giao dịch Mô tả.'
    )
    """Deposit Giao dịch Mô tả."""


class AccountsPostWithdrawRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Số tài khoản lưu ký.')
    """Số tài khoản lưu ký."""

    sub_account_id: str = Field(
        ..., alias='subAccountId', description='Phái sinh Số tiểu khoản.'
    )
    """Phái sinh Số tiểu khoản."""

    amount: float = Field(..., description='Withdraw margin Số tiền.')
    """Withdraw margin Số tiền."""

    payment_content: str | MISSING = Field(
        MISSING, alias='paymentContent', description='Withdraw Giao dịch Mô tả.'
    )
    """Withdraw Giao dịch Mô tả."""


class AccountsPostStockTransferRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    source_account_number: str = Field(
        ..., alias='sourceAccountNumber', description='Source Số tiểu khoản.'
    )
    """Source Số tiểu khoản."""

    destination_account_number: str = Field(
        ..., alias='destinationAccountNumber', description='Destination Số tiểu khoản.'
    )
    """Destination Số tiểu khoản."""

    amount: float = Field(..., description='Transfer Số tiền.')
    """Transfer Số tiền."""

    description: str = Field(..., description='Transfer Mô tả.')
    """Transfer Mô tả."""


class PricingPolicy(BaseModel):
    """
    Thông tin gói lãi suất margin.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='Mã gói lãi suất.')
    """Mã gói lãi suất."""

    name: str | MISSING = Field(MISSING, description='Tên gói lãi suất.')
    """Tên gói lãi suất."""

    status: str | MISSING = Field(MISSING, description='Trạng thái gói lãi suất.')
    """Trạng thái gói lãi suất."""

    pricing_policy_type: str | MISSING = Field(
        MISSING, alias='pricingPolicyType', description='Loại chính sách lãi suất.'
    )
    """Loại chính sách lãi suất."""

    undue_interest_type: str | MISSING = Field(
        MISSING, alias='undueInterestType', description='Loại lãi suất trong hạn.'
    )
    """Loại lãi suất trong hạn."""

    undue_fixed_value: float | MISSING = Field(
        MISSING, alias='undueFixedValue', description='Mức lãi suất trong hạn cố định.'
    )
    """Mức lãi suất trong hạn cố định."""

    least_mass_rate: float | MISSING = Field(
        MISSING, alias='leastMassRate', description='Tỷ lệ margin thấp nhất.'
    )
    """Tỷ lệ margin thấp nhất."""

    greatest_mass_rate: float | MISSING = Field(
        MISSING, alias='greatestMassRate', description='Tỷ lệ margin cao nhất.'
    )
    """Tỷ lệ margin cao nhất."""

    overdue_interest: float | MISSING = Field(
        MISSING, alias='overdueInterest', description='Lãi suất quá hạn.'
    )
    """Lãi suất quá hạn."""

    extension_interest: float | MISSING = Field(
        MISSING, alias='extensionInterest', description='Lãi suất gia hạn.'
    )
    """Lãi suất gia hạn."""

    interest_calculation_basis: int | MISSING = Field(
        MISSING,
        alias='interestCalculationBasis',
        description='Số ngày dùng làm cơ sở tính lãi.',
    )
    """Số ngày dùng làm cơ sở tính lãi."""

    description: str | MISSING = Field(MISSING, description='Mô tả gói lãi suất.')
    """Mô tả gói lãi suất."""

    labels: list[str] | MISSING = Field(
        MISSING, description='Các nhãn của gói lãi suất.'
    )
    """Các nhãn của gói lãi suất."""

    valid_from: date | MISSING = Field(
        MISSING, alias='validFrom', description='Ngày bắt đầu hiệu lực.'
    )
    """Ngày bắt đầu hiệu lực."""

    valid_to: date | MISSING = Field(
        MISSING, alias='validTo', description='Ngày kết thúc hiệu lực.'
    )
    """Ngày kết thúc hiệu lực."""

    discountable: bool | MISSING = Field(
        MISSING, description='Có được áp dụng chiết khấu hay không.'
    )
    """Có được áp dụng chiết khấu hay không."""

    states: list[PricingPolicyState] | MISSING = Field(
        MISSING, description='Danh sách trạng thái áp dụng của gói lãi suất.'
    )
    """Danh sách trạng thái áp dụng của gói lãi suất."""


class PricingPolicyResponse(BaseModel):
    """
    Danh sách các gói lãi suất margin.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[PricingPolicy] | MISSING = Field(
        MISSING, description='Các gói lãi suất margin khả dụng.'
    )
    """Các gói lãi suất margin khả dụng."""


class CashInvestmentsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_count: int | MISSING = Field(
        MISSING, alias='totalCount', description='Tổng số bản ghi trả ra.'
    )
    """Tổng số bản ghi trả ra."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Kích thước trang (mặc định = 20).'
    )
    """Kích thước trang (mặc định = 20)."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Index trang (mặc định = 1).'
    )
    """Index trang (mặc định = 1)."""

    data: list[CashInvestmentItem] | MISSING = MISSING


class Tplus(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[TplusItem] | MISSING = MISSING


class PositionsClosedResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Tên lệnh phản hồi.')
    """Tên lệnh phản hồi."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[PositionClosedItem] | MISSING = Field(
        MISSING, description='Danh sách vị thế đóng.'
    )
    """Danh sách vị thế đóng."""


class PositionsOpenResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Tên lệnh phản hồi.')
    """Tên lệnh phản hồi."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[PositionOpenItem] | MISSING = Field(
        MISSING, description='Danh sách vị thế mở.'
    )
    """Danh sách vị thế mở."""


class ProfileResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    basic_info: dict[str, Any] | MISSING = Field(
        MISSING, alias='basicInfo', description='Thông tin cơ bản tài khoản.'
    )
    """Thông tin cơ bản tài khoản."""

    bank_sub_accounts: list[BankSubAccount] | MISSING = Field(
        MISSING, alias='bankSubAccounts', description='Danh sách tiểu khoản.'
    )
    """Danh sách tiểu khoản."""


class MarginLimitItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    custody_id: str | MISSING = Field(
        MISSING, alias='custodyID', description='Số tài khoản lưu ký.'
    )
    """Số tài khoản lưu ký."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""

    aftype: str | MISSING = Field(MISSING, description='Loại hình hợp đồng.')
    """Loại hình hợp đồng."""

    vsd_status: str | MISSING = Field(
        MISSING, alias='vsdStatus', description='Trạng thái VSD.'
    )
    """Trạng thái VSD."""

    account_status: SubAccountStatus | MISSING = Field(MISSING, alias='accountStatus')
    margin_limit: float | MISSING = Field(
        MISSING, alias='marginLimit', description='Hạn mức margin của tiểu khoản.'
    )
    """Hạn mức margin của tiểu khoản."""

    account_type: SubAccountType | MISSING = Field(MISSING, alias='accountType')
    is_ia: str | MISSING = Field(
        MISSING, alias='isIA', description='Có kết nối IA: Y = Có, N = Không.'
    )
    """Có kết nối IA: Y = Có, N = Không."""

    bank_name: str | MISSING = Field(
        MISSING, alias='bankName', description='Tên ngân hàng kết nối IA.'
    )
    """Tên ngân hàng kết nối IA."""

    bank_account: str | MISSING = Field(
        MISSING, alias='bankAccount', description='Số tài khoản kết nối IA.'
    )
    """Số tài khoản kết nối IA."""


class LoanItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    opening_date: str | MISSING = Field(
        MISSING, alias='openingDate', description='Ngày mở khoản vay.'
    )
    """Ngày mở khoản vay."""

    due_date: str | MISSING = Field(
        MISSING, alias='dueDate', description='Ngày đáo hạn.'
    )
    """Ngày đáo hạn."""

    renew_time: float | MISSING = Field(
        MISSING, alias='renewTime', description='Số lần đã gia hạn nợ.'
    )
    """Số lần đã gia hạn nợ."""

    max_renew_time: float | MISSING = Field(
        MISSING, alias='maxRenewTime', description='Giới hạn số lần gia hạn.'
    )
    """Giới hạn số lần gia hạn."""

    is_renewable: bool | MISSING = Field(
        MISSING, alias='isRenewable', description='Có được gia hạn: true/false.'
    )
    """Có được gia hạn: true/false."""

    reason_list: list[str] | MISSING = Field(
        MISSING, alias='reasonList', description='Lý do không được gia hạn.'
    )
    """Lý do không được gia hạn."""

    insurance: Insurance | MISSING = MISSING


class RiskItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""

    rtt: float | MISSING = Field(MISSING, description='Rtt thực tế.')
    """Rtt thực tế."""

    outstanding: float | MISSING = Field(MISSING, description='Tổng nợ gốc.')
    """Tổng nợ gốc."""

    accrued_interest: float | MISSING = Field(
        MISSING, alias='accruedInterest', description='Tổng nợ lãi.'
    )
    """Tổng nợ lãi."""

    due_amount: float | MISSING = Field(
        MISSING, alias='dueAmount', description='Nợ đến hạn.'
    )
    """Nợ đến hạn."""

    overdue_amount: float | MISSING = Field(
        MISSING, alias='overdueAmount', description='Nợ quá hạn.'
    )
    """Nợ quá hạn."""

    total_fee_debt: float | MISSING = Field(
        MISSING, alias='totalFeeDebt', description='Tổng nợ phí (Phí marginsure).'
    )
    """Tổng nợ phí (Phí marginsure)."""

    risk_policy: RiskPolicy | MISSING = Field(MISSING, alias='riskPolicy')
    risk_status: RiskStatus | MISSING = Field(MISSING, alias='riskStatus')


class StockAssetResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    assets: list[StockAssetItem] | MISSING = Field(
        MISSING, description='Danh sách tài sản cổ phiếu.'
    )
    """Danh sách tài sản cổ phiếu."""


class MarginInfoPage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_row: int | MISSING = Field(
        MISSING, alias='totalRow', description='Số bản ghi.'
    )
    """Số bản ghi."""

    total_page: int | MISSING = Field(
        MISSING, alias='totalPage', description='Số trang.'
    )
    """Số trang."""

    data: list[MarginInfoItem] | MISSING = MISSING


class AddonsDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    margin_sure_views: list[MarginSureViewItem] | MISSING = Field(
        MISSING, alias='marginSureViews'
    )
    tplus: Tplus | MISSING = MISSING


class MarginLimitResponse(RootModel[list[MarginLimitItem]]):
    root: list[MarginLimitItem]


class LoanResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    size: float | MISSING = Field(MISSING, description='Số bản ghi.')
    """Số bản ghi."""

    content: list[LoanItem] | MISSING = MISSING


class RiskResponse(RootModel[list[RiskItem]]):
    root: list[RiskItem]


class MarginInfoResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    response: MarginInfoPage | MISSING = MISSING
