# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class CashStatementItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    custody_id: str | MISSING = Field(
        MISSING, alias='custodyID', description='Số tài khoản.'
    )
    """Số tài khoản."""

    transaction_code: str | MISSING = Field(
        MISSING, alias='transactionCode', description='Loại giao dịch.'
    )
    """Loại giao dịch."""

    transaction_name: str | MISSING = Field(
        MISSING, alias='transactionName', description='Tên loại giao dịch.'
    )
    """Tên loại giao dịch."""

    debit_amount: float | MISSING = Field(
        MISSING, alias='debitAmount', description='Số tiền phát sinh tăng.'
    )
    """Số tiền phát sinh tăng."""

    credit_amount: float | MISSING = Field(
        MISSING, alias='creditAmount', description='Số tiền phát sinh giảm.'
    )
    """Số tiền phát sinh giảm."""

    business_date: str | MISSING = Field(
        MISSING, alias='businessDate', description='Ngày làm việc.'
    )
    """Ngày làm việc."""

    transaction_date: str | MISSING = Field(
        MISSING, alias='transactionDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    transaction_num: str | MISSING = Field(
        MISSING, alias='transactionNum', description='Số giao dịch.'
    )
    """Số giao dịch."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""

    descriptions: str | MISSING = Field(MISSING, description='Mô tả.')
    """Mô tả."""


class StockOrderSide(StrEnum):
    """
    Chiều lệnh cơ sở.

    - `S`: Bán
    - `B`: Mua
    """

    SELL = 'S'
    """Bán"""

    BUY = 'B'
    """Mua"""


class IAConnection(StrEnum):
    """
    Trạng thái kết nối IA.

    - `Y`: Có
    - `N`: Không
    """

    YES = 'Y'
    """Có"""

    NO = 'N'
    """Không"""


class CashStatementPage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Page index.'
    )
    """Page index."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Page size.'
    )
    """Page size."""

    total_credit_amount: int | MISSING = Field(
        MISSING, alias='totalCreditAmount', description='Tổng tiền ghi có.'
    )
    """Tổng tiền ghi có."""

    total_debit_amount: int | MISSING = Field(
        MISSING, alias='totalDebitAmount', description='Tổng phát sinh tăng.'
    )
    """Tổng phát sinh tăng."""

    total_count: int | MISSING = Field(
        MISSING, alias='totalCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    data: list[CashStatementItem] | MISSING = MISSING


class CashStatementsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    response: CashStatementPage | MISSING = MISSING
