# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import StockOrderSide


class SecType(StrEnum):
    """
    Phân loại chứng khoán: 001 = cổ phiếu phổ thông, 002 = cổ phiếu ưu đãi, 003 = trái phiếu chuyển đổi, 006 = trái phiếu.
    """

    FIELD_001 = '001'
    FIELD_002 = '002'
    FIELD_003 = '003'
    FIELD_006 = '006'


class InvestmentType(StrEnum):
    """
    Hình thức đầu tư: 001 = ngắn hạn, 002 = dài hạn.
    """

    FIELD_001 = '001'
    FIELD_002 = '002'


class TradePlace(StrEnum):
    """
    Nơi giao dịch: 001 = HOSE, 002 = HNX, 005 = UPCOM.
    """

    FIELD_001 = '001'
    FIELD_002 = '002'
    FIELD_005 = '005'


class Status(StrEnum):
    """
    Có sử dụng hay không (Y/N).
    """

    Y = 'Y'
    N = 'N'


class Halt(StrEnum):
    """
    Tạm ngừng giao dịch (Y/N).
    """

    Y = 'Y'
    N = 'N'


class StatusModel(StrEnum):
    """
    Trạng thái giao dịch: 001 = bình thường, 002 = tạm ngừng, 003 = dừng, 004 = giám sát, 005 = cảnh báo.
    """

    FIELD_001 = '001'
    FIELD_002 = '002'
    FIELD_003 = '003'
    FIELD_004 = '004'
    FIELD_005 = '005'


class ListingStatus(StrEnum):
    """
    Trạng thái niêm yết: N = bình thường, L = niêm yết mới, U = hủy, I = tăng vốn, D = giảm vốn.
    """

    N = 'N'
    L = 'L'
    U = 'U'
    I = 'I'
    D = 'D'


class TradeBuySell(StrEnum):
    """
    Cho phép mua bán cùng ngày (Y/N).
    """

    Y = 'Y'
    N = 'N'


class SecuritiesInfo(BaseModel):
    """
    Thông tin chi tiết niêm yết của chứng khoán.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã niêm yết.')
    """Mã niêm yết."""

    status: StatusModel | MISSING = Field(
        MISSING,
        description='Trạng thái giao dịch: 001 = bình thường, 002 = tạm ngừng, 003 = dừng, 004 = giám sát, 005 = cảnh báo.',
    )
    """Trạng thái giao dịch: 001 = bình thường, 002 = tạm ngừng, 003 = dừng, 004 = giám sát, 005 = cảnh báo."""

    listing_qtty: int | MISSING = Field(
        MISSING, alias='listingQtty', description='Tổng khối lượng niêm yết.'
    )
    """Tổng khối lượng niêm yết."""

    tx_date: date | MISSING = Field(
        MISSING, alias='txDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    listing_status: ListingStatus | MISSING = Field(
        MISSING,
        alias='listingStatus',
        description='Trạng thái niêm yết: N = bình thường, L = niêm yết mới, U = hủy, I = tăng vốn, D = giảm vốn.',
    )
    """Trạng thái niêm yết: N = bình thường, L = niêm yết mới, U = hủy, I = tăng vốn, D = giảm vốn."""

    trade_unit: int | MISSING = Field(
        MISSING, alias='tradeUnit', description='Đơn vị giá giao dịch.'
    )
    """Đơn vị giá giao dịch."""

    ceiling_price: int | MISSING = Field(
        MISSING, alias='ceilingPrice', description='Giá trần.'
    )
    """Giá trần."""

    floor_price: int | MISSING = Field(
        MISSING, alias='floorPrice', description='Giá sàn.'
    )
    """Giá sàn."""

    basic_price: int | MISSING = Field(
        MISSING, alias='basicPrice', description='Giá tham chiếu.'
    )
    """Giá tham chiếu."""

    trade_lot: int | MISSING = Field(
        MISSING, alias='tradeLot', description='Đơn vị khối lượng giao dịch.'
    )
    """Đơn vị khối lượng giao dịch."""

    trade_buy_sell: TradeBuySell | MISSING = Field(
        MISSING, alias='tradeBuySell', description='Cho phép mua bán cùng ngày (Y/N).'
    )
    """Cho phép mua bán cùng ngày (Y/N)."""

    margin_limit_max: int | MISSING = Field(
        MISSING, alias='marginLimitMax', description='Hạn mức giao dịch margin tối đa.'
    )
    """Hạn mức giao dịch margin tối đa."""

    current_room: int | MISSING = Field(
        MISSING,
        alias='currentRoom',
        description='Room còn lại của nhà đầu tư nước ngoài.',
    )
    """Room còn lại của nhà đầu tư nước ngoài."""

    secured_ratio_max: float | MISSING = Field(
        MISSING, alias='securedRatioMax', description='Tỷ lệ ký quỹ tối đa.'
    )
    """Tỷ lệ ký quỹ tối đa."""

    mortage_ratio_max: float | MISSING = Field(
        MISSING, alias='mortageRatioMax', description='Tỷ lệ cầm cố tối đa.'
    )
    """Tỷ lệ cầm cố tối đa."""


class TickerIntradayBsaItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bup: float | MISSING = Field(MISSING, description='Tỷ lệ % mua tích cực.')
    """Tỷ lệ % mua tích cực."""

    sdp: float | MISSING = Field(MISSING, description='Tỷ lệ % bán tiêu cực.')
    """Tỷ lệ % bán tiêu cực."""

    bsr: float | MISSING = Field(MISSING, description='Tỷ lệ mua/bán.')
    """Tỷ lệ mua/bán."""

    t: str | MISSING = Field(MISSING, description='Thời gian giao dịch.')
    """Thời gian giao dịch."""


class TickerIntradayBsaExtItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bu: float | MISSING = Field(MISSING, description='Khối lượng mua tích cực.')
    """Khối lượng mua tích cực."""

    bms: float | MISSING = Field(MISSING, description='Tổng tích lũy mua.')
    """Tổng tích lũy mua."""

    bup: float | MISSING = Field(MISSING, description='Tỷ lệ % mua tích cực.')
    """Tỷ lệ % mua tích cực."""

    sd: float | MISSING = Field(MISSING, description='Khối lượng bán tiêu cực.')
    """Khối lượng bán tiêu cực."""

    sms: float | MISSING = Field(MISSING, description='Tổng tích lũy bán.')
    """Tổng tích lũy bán."""

    sdp: float | MISSING = Field(MISSING, description='Tỷ lệ % bán tiêu cực.')
    """Tỷ lệ % bán tiêu cực."""

    bsr: float | MISSING = Field(MISSING, description='Tỷ lệ mua/bán.')
    """Tỷ lệ mua/bán."""

    t: str | MISSING = Field(MISSING, description='Thời gian (HH:mm:ss).')
    """Thời gian (HH:mm:ss)."""

    s: float | MISSING = Field(MISSING, description='Thời gian (timestamp).')
    """Thời gian (timestamp)."""


class TickerIntradayBsaMonthItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bup: float | MISSING = Field(MISSING, description='Tỷ lệ % mua tích cực.')
    """Tỷ lệ % mua tích cực."""

    sdp: float | MISSING = Field(MISSING, description='Tỷ lệ % bán tiêu cực.')
    """Tỷ lệ % bán tiêu cực."""

    bsr: float | MISSING = Field(MISSING, description='Tỷ lệ mua/bán.')
    """Tỷ lệ mua/bán."""

    t: str | MISSING = Field(MISSING, description='Thời gian (DD/MM).')
    """Thời gian (DD/MM)."""


class IntradayHistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    p: float | MISSING = Field(MISSING, description='Giá khớp lệnh.')
    """Giá khớp lệnh."""

    v: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    cp: float | MISSING = Field(
        MISSING, description='Thay đổi giá (giá - giá tham chiếu).'
    )
    """Thay đổi giá (giá - giá tham chiếu)."""

    a: str | MISSING = Field(MISSING, description='Hành động (Buy up/Sell down).')
    """Hành động (Buy up/Sell down)."""

    ba: float | MISSING = Field(MISSING, description='Tích lũy KL mua lên.')
    """Tích lũy KL mua lên."""

    sa: float | MISSING = Field(MISSING, description='Tích lũy KL bán xuống.')
    """Tích lũy KL bán xuống."""

    hl: bool | MISSING = Field(MISSING, description='Highlight nếu giá trị > 200M.')
    """Highlight nếu giá trị > 200M."""

    t: float | MISSING = Field(
        MISSING, description='Thời gian nhận lệnh từ sở (timestamp).'
    )
    """Thời gian nhận lệnh từ sở (timestamp)."""


class DerivativeQuoteItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã hợp đồng.')
    """Mã hợp đồng."""

    ceil_price: float | MISSING = Field(
        MISSING, alias='ceilPrice', description='Giá trần.'
    )
    """Giá trần."""

    floor_price: float | MISSING = Field(
        MISSING, alias='floorPrice', description='Giá sàn.'
    )
    """Giá sàn."""

    ref_price: float | MISSING = Field(
        MISSING, alias='refPrice', description='Giá tham chiếu.'
    )
    """Giá tham chiếu."""

    bid_price01: float | MISSING = Field(
        MISSING, alias='bidPrice01', description='Giá mua 1.'
    )
    """Giá mua 1."""

    bid_price02: float | MISSING = Field(
        MISSING, alias='bidPrice02', description='Giá mua 2.'
    )
    """Giá mua 2."""

    bid_price03: float | MISSING = Field(
        MISSING, alias='bidPrice03', description='Giá mua 3.'
    )
    """Giá mua 3."""

    bid_qtty01: float | MISSING = Field(
        MISSING, alias='bidQtty01', description='Khối lượng mua 1.'
    )
    """Khối lượng mua 1."""

    bid_qtty02: float | MISSING = Field(
        MISSING, alias='bidQtty02', description='Khối lượng mua 2.'
    )
    """Khối lượng mua 2."""

    bid_qtty03: float | MISSING = Field(
        MISSING, alias='bidQtty03', description='Khối lượng mua 3.'
    )
    """Khối lượng mua 3."""

    offer_price01: float | MISSING = Field(
        MISSING, alias='offerPrice01', description='Giá bán 1.'
    )
    """Giá bán 1."""

    offer_price02: float | MISSING = Field(
        MISSING, alias='offerPrice02', description='Giá bán 2.'
    )
    """Giá bán 2."""

    offer_price03: float | MISSING = Field(
        MISSING, alias='offerPrice03', description='Giá bán 3.'
    )
    """Giá bán 3."""

    offer_qtty01: float | MISSING = Field(
        MISSING, alias='offerQtty01', description='Khối lượng bán 1.'
    )
    """Khối lượng bán 1."""

    offer_qtty02: float | MISSING = Field(
        MISSING, alias='offerQtty02', description='Khối lượng bán 2.'
    )
    """Khối lượng bán 2."""

    offer_qtty03: float | MISSING = Field(
        MISSING, alias='offerQtty03', description='Khối lượng bán 3.'
    )
    """Khối lượng bán 3."""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp.'
    )
    """Giá khớp."""

    match_qtty: float | MISSING = Field(
        MISSING, alias='matchQtty', description='Khối lượng khớp.'
    )
    """Khối lượng khớp."""

    change: float | MISSING = Field(MISSING, description='Thay đổi giá.')
    """Thay đổi giá."""

    change_percent: float | MISSING = Field(
        MISSING, alias='changePercent', description='% thay đổi.'
    )
    """% thay đổi."""

    open: float | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""

    high: float | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: float | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    total_vol: float | MISSING = Field(
        MISSING, alias='totalVol', description='Tổng khối lượng.'
    )
    """Tổng khối lượng."""

    open_vol: float | MISSING = Field(
        MISSING, alias='openVol', description='Khối lượng mở.'
    )
    """Khối lượng mở."""

    buy_foreign_qtty: float | MISSING = Field(
        MISSING,
        alias='buyForeignQtty',
        description='Khối lượng mua của nhà đầu tư nước ngoài.',
    )
    """Khối lượng mua của nhà đầu tư nước ngoài."""

    sell_foreign_qtty: float | MISSING = Field(
        MISSING,
        alias='sellForeignQtty',
        description='Khối lượng bán của nhà đầu tư nước ngoài.',
    )
    """Khối lượng bán của nhà đầu tư nước ngoài."""

    expiry_date: str | MISSING = Field(
        MISSING, alias='expiryDate', description='Ngày đáo hạn.'
    )
    """Ngày đáo hạn."""

    avg: float | MISSING = Field(MISSING, description='Giá trị giao dịch trung bình.')
    """Giá trị giao dịch trung bình."""


class MatchItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    price: float | MISSING = Field(MISSING, description='Giá khớp.')
    """Giá khớp."""

    vol: float | MISSING = Field(MISSING, description='Khối lượng khớp.')
    """Khối lượng khớp."""

    val: float | MISSING = Field(MISSING, description='Giá trị.')
    """Giá trị."""

    time: float | MISSING = Field(MISSING, description='Thời gian khớp (timestamp).')
    """Thời gian khớp (timestamp)."""

    color: int | MISSING = Field(MISSING, description='Màu.')
    """Màu."""

    accumulated_value: float | MISSING = Field(
        MISSING, alias='accumulatedValue', description='Giá trị tích lũy.'
    )
    """Giá trị tích lũy."""


class TickerCommonItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    ceil_price: float | MISSING = Field(
        MISSING, alias='ceilPrice', description='Giá trần.'
    )
    """Giá trần."""

    floor_price: float | MISSING = Field(
        MISSING, alias='floorPrice', description='Giá sàn.'
    )
    """Giá sàn."""

    ref_price: float | MISSING = Field(
        MISSING, alias='refPrice', description='Giá tham chiếu.'
    )
    """Giá tham chiếu."""

    bid_price01: float | MISSING = Field(
        MISSING, alias='bidPrice01', description='Dư mua giá 1.'
    )
    """Dư mua giá 1."""

    bid_price02: float | MISSING = Field(
        MISSING, alias='bidPrice02', description='Dư mua giá 2.'
    )
    """Dư mua giá 2."""

    bid_price03: float | MISSING = Field(
        MISSING, alias='bidPrice03', description='Dư mua giá 3.'
    )
    """Dư mua giá 3."""

    bid_qtty01: float | MISSING = Field(
        MISSING, alias='bidQtty01', description='Dư mua KL 1.'
    )
    """Dư mua KL 1."""

    bid_qtty02: float | MISSING = Field(
        MISSING, alias='bidQtty02', description='Dư mua KL 2.'
    )
    """Dư mua KL 2."""

    bid_qtty03: float | MISSING = Field(
        MISSING, alias='bidQtty03', description='Dư mua KL 3.'
    )
    """Dư mua KL 3."""

    offer_price01: float | MISSING = Field(
        MISSING, alias='offerPrice01', description='Dư bán giá 1.'
    )
    """Dư bán giá 1."""

    offer_price02: float | MISSING = Field(
        MISSING, alias='offerPrice02', description='Dư bán giá 2.'
    )
    """Dư bán giá 2."""

    offer_price03: float | MISSING = Field(
        MISSING, alias='offerPrice03', description='Dư bán giá 3.'
    )
    """Dư bán giá 3."""

    offer_qtty01: float | MISSING = Field(
        MISSING, alias='offerQtty01', description='Dư bán KL 1.'
    )
    """Dư bán KL 1."""

    offer_qtty02: float | MISSING = Field(
        MISSING, alias='offerQtty02', description='Dư bán KL 2.'
    )
    """Dư bán KL 2."""

    offer_qtty03: float | MISSING = Field(
        MISSING, alias='offerQtty03', description='Dư bán KL 3.'
    )
    """Dư bán KL 3."""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp.'
    )
    """Giá khớp."""

    match_qtty: float | MISSING = Field(
        MISSING, alias='matchQtty', description='Khối lượng khớp.'
    )
    """Khối lượng khớp."""

    change: float | MISSING = Field(MISSING, description='Thay đổi giá.')
    """Thay đổi giá."""

    change_percent: float | MISSING = Field(
        MISSING, alias='changePercent', description='Phần trăm thay đổi.'
    )
    """Phần trăm thay đổi."""

    open: float | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""

    avg: float | MISSING = Field(MISSING, description='Giá trung bình.')
    """Giá trung bình."""

    high: float | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: float | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    total_vol: float | MISSING = Field(
        MISSING, alias='totalVol', description='Tổng khối lượng giao dịch.'
    )
    """Tổng khối lượng giao dịch."""

    total_val: float | MISSING = Field(
        MISSING, alias='totalVal', description='Tổng giá trị giao dịch.'
    )
    """Tổng giá trị giao dịch."""

    buy_foreign_qtty: float | MISSING = Field(
        MISSING, alias='buyForeignQtty', description='KL mua nước ngoài.'
    )
    """KL mua nước ngoài."""

    sell_foreign_qtty: float | MISSING = Field(
        MISSING, alias='sellForeignQtty', description='KL bán nước ngoài.'
    )
    """KL bán nước ngoài."""

    room: str | MISSING = Field(MISSING, description='Room nước ngoài.')
    """Room nước ngoài."""

    index_number: float | MISSING = Field(
        MISSING, alias='indexNumber', description='Mã rổ chứng khoán.'
    )
    """Mã rổ chứng khoán."""


class TickerSnapItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    ceil_price: float | MISSING = Field(
        MISSING, alias='ceilPrice', description='Giá trần.'
    )
    """Giá trần."""

    floor_price: float | MISSING = Field(
        MISSING, alias='floorPrice', description='Giá sàn.'
    )
    """Giá sàn."""

    ref_price: float | MISSING = Field(
        MISSING, alias='refPrice', description='Giá tham chiếu.'
    )
    """Giá tham chiếu."""

    bid_price01: float | MISSING = Field(
        MISSING, alias='bidPrice01', description='Giá mua 1.'
    )
    """Giá mua 1."""

    bid_price02: float | MISSING = Field(
        MISSING, alias='bidPrice02', description='Giá mua 2.'
    )
    """Giá mua 2."""

    bid_price03: float | MISSING = Field(
        MISSING, alias='bidPrice03', description='Giá mua 3.'
    )
    """Giá mua 3."""

    bid_qtty01: float | MISSING = Field(
        MISSING, alias='bidQtty01', description='KL mua 1.'
    )
    """KL mua 1."""

    bid_qtty02: float | MISSING = Field(
        MISSING, alias='bidQtty02', description='KL mua 2.'
    )
    """KL mua 2."""

    bid_qtty03: float | MISSING = Field(
        MISSING, alias='bidQtty03', description='KL mua 3.'
    )
    """KL mua 3."""

    offer_price01: float | MISSING = Field(
        MISSING, alias='offerPrice01', description='Giá bán 1.'
    )
    """Giá bán 1."""

    offer_price02: float | MISSING = Field(
        MISSING, alias='offerPrice02', description='Giá bán 2.'
    )
    """Giá bán 2."""

    offer_price03: float | MISSING = Field(
        MISSING, alias='offerPrice03', description='Giá bán 3.'
    )
    """Giá bán 3."""

    offer_qtty01: float | MISSING = Field(
        MISSING, alias='offerQtty01', description='KL bán 1.'
    )
    """KL bán 1."""

    offer_qtty02: float | MISSING = Field(
        MISSING, alias='offerQtty02', description='KL bán 2.'
    )
    """KL bán 2."""

    offer_qtty03: float | MISSING = Field(
        MISSING, alias='offerQtty03', description='KL bán 3.'
    )
    """KL bán 3."""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp.'
    )
    """Giá khớp."""

    match_qtty: float | MISSING = Field(
        MISSING, alias='matchQtty', description='Khối lượng khớp.'
    )
    """Khối lượng khớp."""

    change: float | MISSING = Field(MISSING, description='Thay đổi giá.')
    """Thay đổi giá."""

    change_percent: float | MISSING = Field(
        MISSING, alias='changePercent', description='% thay đổi.'
    )
    """% thay đổi."""

    avg: float | MISSING = Field(MISSING, description='Giá bình quân.')
    """Giá bình quân."""

    high: float | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: float | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    total_value: float | MISSING = Field(
        MISSING, alias='totalValue', description='Tổng giá trị.'
    )
    """Tổng giá trị."""

    total_volume: float | MISSING = Field(
        MISSING, alias='totalVolume', description='Tổng khối lượng.'
    )
    """Tổng khối lượng."""

    buy_foreign_qtty: float | MISSING = Field(
        MISSING, alias='buyForeignQtty', description='KL nước ngoài mua.'
    )
    """KL nước ngoài mua."""

    sell_foreign_qtty: float | MISSING = Field(
        MISSING, alias='sellForeignQtty', description='KL nước ngoài bán.'
    )
    """KL nước ngoài bán."""

    room: str | MISSING = Field(MISSING, description='Room nước ngoài.')
    """Room nước ngoài."""

    open: float | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""


class MarketBasket(StrEnum):
    """
    Rổ chứng khoán.

    - `1`: HOSE
    - `2`: VN30
    - `3`: HNX
    - `4`: HNX30
    - `5`: Upcom
    - `10`: Midcap
    - `11`: VN100
    - `12`: VNAllshare
    - `13`: VNSmallcap
    - `14`: VNXAllshare
    - `15`: VN50
    - `16`: VNSI
    """

    HOSE = '1'
    """HOSE"""

    VN30 = '2'
    """VN30"""

    HNX = '3'
    """HNX"""

    HNX30 = '4'
    """HNX30"""

    UPCOM = '5'
    """Upcom"""

    MIDCAP = '10'
    """Midcap"""

    VN100 = '11'
    """VN100"""

    VNALLSHARE = '12'
    """VNAllshare"""

    VNSMALLCAP = '13'
    """VNSmallcap"""

    VNXALLSHARE = '14'
    """VNXAllshare"""

    VN50 = '15'
    """VN50"""

    VNSI = '16'
    """VNSI"""


class MarketFloor(StrEnum):
    """
    Sàn giao dịch.

    - `1`: HOSE
    - `2`: HNX
    - `3`: Upcom
    """

    HOSE = '1'
    """HOSE"""

    HNX = '2'
    """HNX"""

    UPCOM = '3'
    """Upcom"""


class InvestorType(StrEnum):
    """
    Loại nhà đầu tư.

    - `sheep`: Cá nhân nhỏ lẻ
    - `wolf`: Tổ chức vừa
    - `shark`: Tổ chức lớn
    - `all`: Tất cả
    """

    SHEEP = 'sheep'
    """Cá nhân nhỏ lẻ"""

    WOLF = 'wolf'
    """Tổ chức vừa"""

    SHARK = 'shark'
    """Tổ chức lớn"""

    ALL = 'all'
    """Tất cả"""


class IntradayTimeWindow(StrEnum):
    """
    Khung thời gian cung cầu trong phiên, tính bằng phút.

    - `15`: 15 phút
    - `60`: 60 phút
    """

    M15 = '15'
    """15 phút"""

    H1 = '60'
    """60 phút"""


class IntradayTWindow(StrEnum):
    """
    Khung thời gian cung cầu trong phiên.

    - `15`: 15 phút
    """

    M15 = '15'
    """15 phút"""


class Security(BaseModel):
    """
    Thông tin cơ bản của một chứng khoán.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code_id: str | MISSING = Field(
        MISSING, alias='codeId', description='Mã số quy ước của chứng khoán.'
    )
    """Mã số quy ước của chứng khoán."""

    issuer_id: str | MISSING = Field(
        MISSING, alias='issuerId', description='Mã tổ chức phát hành.'
    )
    """Mã tổ chức phát hành."""

    issuer_name: str | MISSING = Field(
        MISSING, alias='issuerName', description='Tên tổ chức phát hành.'
    )
    """Tên tổ chức phát hành."""

    symbol: str | MISSING = Field(MISSING, description='Mã niêm yết giao dịch.')
    """Mã niêm yết giao dịch."""

    sec_type: SecType | MISSING = Field(
        MISSING,
        alias='secType',
        description='Phân loại chứng khoán: 001 = cổ phiếu phổ thông, 002 = cổ phiếu ưu đãi, 003 = trái phiếu chuyển đổi, 006 = trái phiếu.',
    )
    """Phân loại chứng khoán: 001 = cổ phiếu phổ thông, 002 = cổ phiếu ưu đãi, 003 = trái phiếu chuyển đổi, 006 = trái phiếu."""

    investment_type: InvestmentType | MISSING = Field(
        MISSING,
        alias='investmentType',
        description='Hình thức đầu tư: 001 = ngắn hạn, 002 = dài hạn.',
    )
    """Hình thức đầu tư: 001 = ngắn hạn, 002 = dài hạn."""

    issue_date: AwareDatetime | MISSING = Field(
        MISSING, alias='issueDate', description='Ngày phát hành.'
    )
    """Ngày phát hành."""

    exp_date: AwareDatetime | MISSING = Field(
        MISSING, alias='expDate', description='Ngày hết hạn.'
    )
    """Ngày hết hạn."""

    underlying_symbol: str | MISSING = Field(
        MISSING, alias='underlyingSymbol', description='Mã gốc, ví dụ mã chứng quyền.'
    )
    """Mã gốc, ví dụ mã chứng quyền."""

    covered_warrant_type: str | MISSING = Field(
        MISSING, alias='coveredWarrantType', description='Loại chứng quyền.'
    )
    """Loại chứng quyền."""

    exercise_price: float | MISSING = Field(
        MISSING, alias='exercisePrice', description='Giá quyền.'
    )
    """Giá quyền."""

    par_value: float | MISSING = Field(
        MISSING, alias='parValue', description='Mệnh giá chứng khoán.'
    )
    """Mệnh giá chứng khoán."""

    trade_place: TradePlace | MISSING = Field(
        MISSING,
        alias='tradePlace',
        description='Nơi giao dịch: 001 = HOSE, 002 = HNX, 005 = UPCOM.',
    )
    """Nơi giao dịch: 001 = HOSE, 002 = HNX, 005 = UPCOM."""

    status: Status | MISSING = Field(MISSING, description='Có sử dụng hay không (Y/N).')
    """Có sử dụng hay không (Y/N)."""

    halt: Halt | MISSING = Field(MISSING, description='Tạm ngừng giao dịch (Y/N).')
    """Tạm ngừng giao dịch (Y/N)."""

    securities_info: SecuritiesInfo | MISSING = Field(MISSING, alias='securitiesInfo')


class SecuritiesResponse(BaseModel):
    """
    Danh sách chứng khoán có phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    content: list[Security] | MISSING = Field(
        MISSING, description='Danh sách chứng khoán.'
    )
    """Danh sách chứng khoán."""

    total_elements: int | MISSING = Field(
        MISSING, alias='totalElements', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    total_pages: int | MISSING = Field(
        MISSING, alias='totalPages', description='Tổng số trang.'
    )
    """Tổng số trang."""

    size: int | MISSING = Field(
        MISSING, description='Số bản ghi mỗi trang (mặc định 1000).'
    )
    """Số bản ghi mỗi trang (mặc định 1000)."""

    number: int | MISSING = Field(MISSING, description='Trang hiện tại (0-indexed).')
    """Trang hiện tại (0-indexed)."""

    first: bool | MISSING = Field(MISSING, description='Có phải trang đầu.')
    """Có phải trang đầu."""

    last: bool | MISSING = Field(MISSING, description='Có phải trang cuối.')
    """Có phải trang cuối."""


class TickerIntradayBsaResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    ticker: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    data: list[TickerIntradayBsaItem] | MISSING = MISSING


class TickerIntradayBsaExtResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    ticker: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    data: list[TickerIntradayBsaExtItem] | MISSING = MISSING


class TickerIntradayBsaMonthResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    ticker: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    data: list[TickerIntradayBsaMonthItem] | MISSING = MISSING


class TickerIntradayHistoryPagingResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page: float | MISSING = Field(MISSING, description='Trang hiện tại.')
    """Trang hiện tại."""

    size: float | MISSING = Field(MISSING, description='Kích thước trang.')
    """Kích thước trang."""

    head_index: float | MISSING = Field(
        MISSING, alias='headIndex', description='Chỉ số đầu.'
    )
    """Chỉ số đầu."""

    number_of_items: float | MISSING = Field(
        MISSING, alias='numberOfItems', description='Số bản ghi trả về.'
    )
    """Số bản ghi trả về."""

    total: float | MISSING = Field(MISSING, description='Tổng số lệnh khớp.')
    """Tổng số lệnh khớp."""

    ticker: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    data: list[IntradayHistoryItem] | MISSING = MISSING


class DerivativesResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[DerivativeQuoteItem] | MISSING = Field(
        MISSING, description='Danh sách hợp đồng phái sinh.'
    )
    """Danh sách hợp đồng phái sinh."""


class BuyAdvItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    price: float | MISSING = Field(MISSING, description='Giá.')
    """Giá."""

    vol: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    time: str | MISSING = Field(MISSING, description='Thời gian.')
    """Thời gian."""

    status: int | MISSING = Field(MISSING, description='Trạng thái.')
    """Trạng thái."""

    color: int | MISSING = Field(MISSING, description='Màu.')
    """Màu."""

    order_id: str | MISSING = Field(MISSING, alias='orderId', description='Mã lệnh.')
    """Mã lệnh."""

    side: StockOrderSide | MISSING = MISSING


class SellAdvItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    price: float | MISSING = Field(MISSING, description='Giá.')
    """Giá."""

    vol: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    time: str | MISSING = Field(MISSING, description='Thời gian.')
    """Thời gian."""

    status: int | MISSING = Field(MISSING, description='Trạng thái.')
    """Trạng thái."""

    color: int | MISSING = Field(MISSING, description='Màu.')
    """Màu."""

    order_id: str | MISSING = Field(MISSING, alias='orderId', description='Mã lệnh.')
    """Mã lệnh."""

    side: StockOrderSide | MISSING = MISSING


class TickerCommonsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[TickerCommonItem] | MISSING = Field(
        MISSING, description='Danh sách thông tin mã.'
    )
    """Danh sách thông tin mã."""

    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch (dd/MM/yyyy).'
    )
    """Ngày giao dịch (dd/MM/yyyy)."""


class TickerSnapsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    trading_date: str | MISSING = Field(
        MISSING, alias='tradingDate', description='Ngày giao dịch.'
    )
    """Ngày giao dịch."""

    data: list[TickerSnapItem] | MISSING = MISSING


class PutThroughSnapsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    buy_adv: list[BuyAdvItem] | MISSING = Field(MISSING, alias='buyAdv')
    sell_adv: list[SellAdvItem] | MISSING = Field(MISSING, alias='sellAdv')
    match: list[MatchItem] | MISSING = MISSING
