# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import StockOrderSide


class OrderPostResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    error: str | MISSING = Field(MISSING, description='Mã lỗi, 0 = thành công.')
    """Mã lỗi, 0 = thành công."""

    message: str | MISSING = Field(MISSING, description='Thông báo kết quả.')
    """Thông báo kết quả."""

    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Mã lệnh được tạo.'
    )
    """Mã lệnh được tạo."""


class OrderPutResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    error: str | MISSING = Field(MISSING, description='Mã lỗi, 0 = thành công.')
    """Mã lỗi, 0 = thành công."""

    message: str | MISSING = Field(MISSING, description='Mô tả mã lỗi nếu có.')
    """Mô tả mã lỗi nếu có."""

    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Mã lệnh đã sửa.'
    )
    """Mã lệnh đã sửa."""


class OrdersCancelResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    error: str | MISSING = Field(MISSING, description='Mã lỗi, 0 = thành công.')
    """Mã lỗi, 0 = thành công."""

    message: str | MISSING = Field(MISSING, description='Mô tả mã lỗi nếu có.')
    """Mô tả mã lỗi nếu có."""


class DerivativeOrderCancelItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_no: str | MISSING = Field(
        MISSING, alias='orderNo', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    msg_type: str | MISSING = Field(MISSING, description='Loại lệnh (1C = hủy lệnh).')
    """Loại lệnh (1C = hủy lệnh)."""

    status: str | MISSING = Field(
        MISSING, description='Trạng thái (PW = pending withdrawal).'
    )
    """Trạng thái (PW = pending withdrawal)."""

    pk_order_no: str | MISSING = Field(
        MISSING, alias='pk_orderNo', description='Key lệnh.'
    )
    """Key lệnh."""

    cancel_time: str | MISSING = Field(
        MISSING, alias='cancelTime', description='Thời gian hủy.'
    )
    """Thời gian hủy."""


class DerivativeOrderChangeItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_no: str | MISSING = Field(
        MISSING, alias='orderNo', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    msg_type: str | MISSING = Field(MISSING, description='Loại lệnh (1P = sửa lệnh).')
    """Loại lệnh (1P = sửa lệnh)."""

    status: str | MISSING = Field(
        MISSING, description='Trạng thái (PC = pending change).'
    )
    """Trạng thái (PC = pending change)."""

    show_price: str | MISSING = Field(
        MISSING, alias='showPrice', description='Giá mới.'
    )
    """Giá mới."""

    volume: str | MISSING = Field(MISSING, description='Khối lượng mới.')
    """Khối lượng mới."""

    pk_order_no: str | MISSING = Field(
        MISSING, alias='pk_orderNo', description='Key lệnh.'
    )
    """Key lệnh."""


class DerivativeConditionOrderCancelResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str = Field('Web.cancelActivatedOrder', description='Tên lệnh.')
    """Tên lệnh."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    rs: str | MISSING = Field(MISSING, description='Chi tiết lỗi (nếu có).')
    """Chi tiết lỗi (nếu có)."""

    data: list[dict[str, Any]] | MISSING = Field(
        MISSING, description='Mảng rỗng nếu thành công.'
    )
    """Mảng rỗng nếu thành công."""


class DerivativeOrderPlaceItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_no: str = Field(..., alias='orderNo')
    pk_order_no: str = Field(..., alias='pk_orderNo')
    show_price: str = Field(..., alias='showPrice')


class DerivativeConditionOrderChangeV2Item(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    show_price: str | MISSING = Field(
        MISSING, alias='showPrice', description='Giá kích hoạt.'
    )
    """Giá kích hoạt."""

    price: str | MISSING = Field(MISSING, description='Giá đặt.')
    """Giá đặt."""

    volume: str | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    pk_order_no: str | MISSING = Field(
        MISSING, alias='pkOrderNo', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    notes: str | MISSING = Field(MISSING, description='Loại lệnh điều kiện.')
    """Loại lệnh điều kiện."""


class OtpRequestResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    otp_id: str | MISSING = Field(
        MISSING, alias='otpId', description='ID của OTP, dùng ở bước 2 để đổi token.'
    )
    """ID của OTP, dùng ở bước 2 để đổi token."""


class TokenResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    token: str | MISSING = Field(
        MISSING, description='JWT token dùng cho các request tiếp theo.'
    )
    """JWT token dùng cho các request tiếp theo."""


class StockOrderDirection(StrEnum):
    """
    Chiều giao dịch lệnh cơ sở.

    - `NS`: Bán
    - `NB`: Mua
    """

    SELL = 'NS'
    """Bán"""

    BUY = 'NB'
    """Mua"""


class StockPriceType(StrEnum):
    """
    Loại giá lệnh cơ sở.

    - `LO`: Lệnh giới hạn
    - `ATO`: Lệnh phiên định kỳ mở cửa
    - `ATC`: Lệnh phiên định kỳ đóng cửa
    - `PLO`: Lệnh khớp lệnh sau giờ
    - `MP`: Lệnh thị trường
    - `MTL`: Lệnh thị trường khớp theo giá thị trường
    - `MOK`: Lệnh thị trường khớp toàn bộ hoặc hủy
    - `MAK`: Lệnh thị trường khớp một phần và hủy phần còn lại
    """

    LO = 'LO'
    """Lệnh giới hạn"""

    ATO = 'ATO'
    """Lệnh phiên định kỳ mở cửa"""

    ATC = 'ATC'
    """Lệnh phiên định kỳ đóng cửa"""

    PLO = 'PLO'
    """Lệnh khớp lệnh sau giờ"""

    MP = 'MP'
    """Lệnh thị trường"""

    MTL = 'MTL'
    """Lệnh thị trường khớp theo giá thị trường"""

    MOK = 'MOK'
    """Lệnh thị trường khớp toàn bộ hoặc hủy"""

    MAK = 'MAK'
    """Lệnh thị trường khớp một phần và hủy phần còn lại"""


class StockOrderStatus(StrEnum):
    """
    Trạng thái lệnh cơ sở.

    - `0`: Từ chối
    - `2`: Đã gửi
    - `3`: Đã hủy
    - `4`: Đã khớp
    - `5`: Hết hiệu lực
    - `8`: Chờ gửi
    - `10`: Đã sửa
    - `11`: Đang gửi
    - `12`: Khớp hết
    - `A`: Đang sửa
    - `C`: Đang hủy
    - `S`: Hoàn tất
    """

    REJECTED = '0'
    """Từ chối"""

    SENT = '2'
    """Đã gửi"""

    CANCELED = '3'
    """Đã hủy"""

    FILLED = '4'
    """Đã khớp"""

    EXPIRED = '5'
    """Hết hiệu lực"""

    PENDING_SEND = '8'
    """Chờ gửi"""

    REPLACED = '10'
    """Đã sửa"""

    SENDING = '11'
    """Đang gửi"""

    FULLY_FILLED = '12'
    """Khớp hết"""

    REPLACING = 'A'
    """Đang sửa"""

    CANCELLING = 'C'
    """Đang hủy"""

    COMPLETED = 'S'
    """Hoàn tất"""


class DerivativeSide(StrEnum):
    """
    Chiều lệnh phái sinh.

    - `B`: Mua
    - `S`: Bán
    """

    BUY = 'B'
    """Mua"""

    SELL = 'S'
    """Bán"""


class DerivativeConditionalOrderType(StrEnum):
    """
    Loại lệnh điều kiện phái sinh.

    - `SOL`: Giá thị trường lớn hơn hoặc bằng giá điều kiện
    - `SOU`: Giá thị trường nhỏ hơn hoặc bằng giá điều kiện
    - `TSO`: Trailing Stop
    """

    SOL = 'SOL'
    """Giá thị trường lớn hơn hoặc bằng giá điều kiện"""

    SOU = 'SOU'
    """Giá thị trường nhỏ hơn hoặc bằng giá điều kiện"""

    TSO = 'TSO'
    """Trailing Stop"""


class DerivativeOrderType(StrEnum):
    """
    Lọc loại lệnh phái sinh.

    - ``: Tất cả
    - `3`: Arbitrage
    - `4`: SL/TP
    - `5`: ForceClose
    - `6`: Thường
    """

    ALL = ''
    """Tất cả"""

    ARBITRAGE = '3'
    """Arbitrage"""

    SL_TP = '4'
    """SL/TP"""

    FORCE_CLOSE = '5'
    """ForceClose"""

    NORMAL = '6'
    """Thường"""


class DerivativeOrderStatus(StrEnum):
    """
    Bộ lọc trạng thái lệnh phái sinh.

    - `0`: Tất cả
    - `1`: Chờ khớp hoặc chờ kích hoạt
    - `2`: Đã khớp hoặc đã kích hoạt
    - `3`: Từ chối
    """

    ALL = '0'
    """Tất cả"""

    PENDING = '1'
    """Chờ khớp hoặc chờ kích hoạt"""

    MATCHED = '2'
    """Đã khớp hoặc đã kích hoạt"""

    REJECTED = '3'
    """Từ chối"""


class DerivativeConditionalStatus(StrEnum):
    """
    Trạng thái lệnh điều kiện phái sinh.

    - `0`: Chờ kích hoạt
    - `1`: Đã kích hoạt
    - `2`: Đã hủy
    - `3`: Từ chối
    """

    PENDING = '0'
    """Chờ kích hoạt"""

    ACTIVATED = '1'
    """Đã kích hoạt"""

    CANCELED = '2'
    """Đã hủy"""

    REJECTED = '3'
    """Từ chối"""


class DerivativeConditionalOrderTypeFilter(StrEnum):
    """
    Bộ lọc loại lệnh điều kiện phái sinh.

    - ``: Tất cả
    - `3`: Arbitrage
    - `4`: SL/TP
    - `5`: Stop order
    """

    ALL = ''
    """Tất cả"""

    ARBITRAGE = '3'
    """Arbitrage"""

    SL_TP = '4'
    """SL/TP"""

    STOP_ORDER = '5'
    """Stop order"""


class OrdersCancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    orders_list: list[dict[str, Any]] = Field(
        ..., alias='ordersList', description='Danh sách lệnh cần hủy.'
    )
    """Danh sách lệnh cần hủy."""


class OrdersPlaceRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    exec_type: StockOrderDirection = Field(
        ..., alias='execType', description='Chiều giao dịch: NS = bán, NB = mua.'
    )
    """Chiều giao dịch: NS = bán, NB = mua."""

    symbol: str = Field(..., description='Mã chứng khoán, ví dụ VNM.')
    """Mã chứng khoán, ví dụ VNM."""

    price_type: StockPriceType = Field(
        ...,
        alias='priceType',
        description='Loại giá: LO, ATO, ATC, PLO, MP, MTL, MOK, MAK.',
    )
    """Loại giá: LO, ATO, ATC, PLO, MP, MTL, MOK, MAK."""

    price: int = Field(..., description='Giá giao dịch.')
    """Giá giao dịch."""

    quantity: int = Field(..., description='Khối lượng giao dịch.')
    """Khối lượng giao dịch."""


class OrdersModifyRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: int = Field(..., description='Giá giao dịch mới.')
    """Giá giao dịch mới."""

    quantity: int = Field(..., description='Khối lượng giao dịch mới.')
    """Khối lượng giao dịch mới."""


class AuthPostRequestOtpRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    api_key: str = Field(
        ..., alias='apiKey', description='API Key generated on TCInvest.'
    )
    """API Key generated on TCInvest."""


class AuthPostTokenRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    api_key: str = Field(
        ..., alias='apiKey', description='API Key generated on TCInvest.'
    )
    """API Key generated on TCInvest."""

    otp: str = Field(..., description='Mã OTP từ ứng dụng TCInvest.')
    """Mã OTP từ ứng dụng TCInvest."""

    otp_id: str | MISSING = Field(
        MISSING, alias='otpId', description='OTP ID trả về từ bước 1.'
    )
    """OTP ID trả về từ bước 1."""


class DerivativeOrdersCancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Số tài khoản lưu ký.')
    """Số tài khoản lưu ký."""

    order_no: str = Field(
        ..., alias='orderNo', description='orderNo từ API sổ lệnh thường.'
    )
    """orderNo từ API sổ lệnh thường."""

    cmd: str | MISSING = Field(MISSING, description='Web.cancelOrder.')
    """Web.cancelOrder."""

    pin: str | MISSING = Field(MISSING, description='Kênh đặt lệnh (F).')
    """Kênh đặt lệnh (F)."""

    ref_id: str | MISSING = Field(MISSING, alias='refId', description='Reference ID.')
    """Reference ID."""


class DerivativeOrdersModifyRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Mã tài khoản lưu ký.')
    """Mã tài khoản lưu ký."""

    sub_account_id: str = Field(
        ..., alias='subAccountId', description='Phái sinh sub-Số tiểu khoản.'
    )
    """Phái sinh sub-Số tiểu khoản."""

    order_no: str = Field(..., alias='orderNo', description='orderNo từ API đặt lệnh.')
    """orderNo từ API đặt lệnh."""

    ref_id: str = Field(..., alias='refId', description='Unique reference ID.')
    """Unique reference ID."""

    nvol: float = Field(..., description='New Khối lượng (> 0).')
    """New Khối lượng (> 0)."""

    nprice: float = Field(..., description='New Giá.')
    """New Giá."""


class DerivativeConditionOrdersCancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Số tài khoản lưu ký.')
    """Số tài khoản lưu ký."""

    sub_account_id: str | MISSING = Field(
        MISSING, alias='subAccountId', description='Phái sinh sub-Số tiểu khoản.'
    )
    """Phái sinh sub-Số tiểu khoản."""

    order_no: str = Field(
        ..., alias='orderNo', description='pk_orderNo từ API sổ lệnh điều kiện.'
    )
    """pk_orderNo từ API sổ lệnh điều kiện."""


class DerivativeConditionOrdersPlaceRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Mã tài khoản lưu ký.')
    """Mã tài khoản lưu ký."""

    sub_account_id: str = Field(
        ..., alias='subAccountId', description='Số tiểu khoản phái sinh.'
    )
    """Số tiểu khoản phái sinh."""

    side: DerivativeSide = Field(..., description='B = Mua, S = Bán.')
    """B = Mua, S = Bán."""

    symbol: str = Field(..., description='Mã phái sinh, ví dụ VN30F2101.')
    """Mã phái sinh, ví dụ VN30F2101."""

    price: float = Field(..., description='Giá đặt lệnh.')
    """Giá đặt lệnh."""

    volume: float = Field(..., description='Số lượng, lớn hơn 0.')
    """Số lượng, lớn hơn 0."""

    order_type: DerivativeConditionalOrderType = Field(
        ...,
        alias='orderType',
        description='SOL = giá TT >= soPrice, SOU = giá TT <= soPrice, TSO = Trailing Stop.',
    )
    """SOL = giá TT >= soPrice, SOU = giá TT <= soPrice, TSO = Trailing Stop."""

    so_price: float = Field(..., alias='soPrice', description='Giá kích hoạt.')
    """Giá kích hoạt."""

    callback_point: float = Field(
        ...,
        alias='callbackPoint',
        description='Biên trượt (chỉ dùng khi orderType = TSO).',
    )
    """Biên trượt (chỉ dùng khi orderType = TSO)."""

    activation_price: float = Field(
        ...,
        alias='activationPrice',
        description='Giá kích hoạt (chỉ dùng khi orderType = TSO).',
    )
    """Giá kích hoạt (chỉ dùng khi orderType = TSO)."""

    ref_id: str | MISSING = Field(
        MISSING, alias='refId', description='Số chống trùng theo từng lệnh.'
    )
    """Số chống trùng theo từng lệnh."""


class DerivativeOrdersPlaceRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Mã tài khoản lưu ký.')
    """Mã tài khoản lưu ký."""

    sub_account_id: str = Field(
        ..., alias='subAccountId', description='Số tiểu khoản phái sinh.'
    )
    """Số tiểu khoản phái sinh."""

    side: DerivativeSide = Field(..., description='B = Mua, S = Bán.')
    """B = Mua, S = Bán."""

    symbol: str = Field(..., description='Mã phái sinh, ví dụ VN30F2103.')
    """Mã phái sinh, ví dụ VN30F2103."""

    price: float = Field(..., description='Giá đặt lệnh (trong khoảng giá sàn–trần).')
    """Giá đặt lệnh (trong khoảng giá sàn–trần)."""

    volume: int = Field(..., description='Khối lượng.')
    """Khối lượng."""

    order_type: str = Field(
        ...,
        alias='orderType',
        description='0 = lệnh thường; SLP=1.0,0.8 = SL/TP; ABI=mã HĐTL = lệnh đối ứng.',
    )
    """0 = lệnh thường; SLP=1.0,0.8 = SL/TP; ABI=mã HĐTL = lệnh đối ứng."""

    ref_id: str = Field(
        ...,
        alias='refId',
        description='Số ngẫu nhiên duy nhất xác định kênh đặt lệnh (H.< số tự sinh>). Có thể dùng UUID cho trường hợp này.',
    )
    """Số ngẫu nhiên duy nhất xác định kênh đặt lệnh (H.< số tự sinh>). Có thể dùng UUID cho trường hợp này."""


class DerivativeConditionOrdersModifyRequest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str = Field(..., alias='accountId', description='Mã tài khoản lưu ký.')
    """Mã tài khoản lưu ký."""

    pk_order_no: str = Field(
        ..., alias='pkOrderNo', description='pk_orderNo từ API tra cứu sổ lệnh.'
    )
    """pk_orderNo từ API tra cứu sổ lệnh."""

    ref_id: str = Field(..., alias='refId', description='Unique reference ID.')
    """Unique reference ID."""

    so_price: float = Field(..., alias='soPrice', description='Giá kích hoạt mới.')
    """Giá kích hoạt mới."""

    type: str | MISSING = Field(MISSING, description='Loại (empty).')
    """Loại (empty)."""

    cmd: str | MISSING = Field(MISSING, description='Web.Order.ChangeCondition.')
    """Web.Order.ChangeCondition."""


class MatchingItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_id: str | MISSING = Field(
        MISSING, alias='orderId', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    side: StockOrderSide | MISSING = MISSING
    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán.')
    """Mã chứng khoán."""

    quote_qtty: float | MISSING = Field(
        MISSING, alias='quoteQtty', description='Khối lượng đặt.'
    )
    """Khối lượng đặt."""

    quote_price: float | MISSING = Field(
        MISSING, alias='quotePrice', description='Giá đặt.'
    )
    """Giá đặt."""

    trade_id: str | MISSING = Field(
        MISSING, alias='tradeId', description='Id lệnh khớp.'
    )
    """Id lệnh khớp."""

    qtty: float | MISSING = Field(MISSING, description='Khối lượng khớp.')
    """Khối lượng khớp."""

    price: float | MISSING = Field(MISSING, description='Giá khớp.')
    """Giá khớp."""

    time_exec: str | MISSING = Field(
        MISSING, alias='timeExec', description='Thời điểm khớp.'
    )
    """Thời điểm khớp."""


class OrderItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_id: str | MISSING = Field(MISSING, alias='orderId', description='Mã lệnh.')
    """Mã lệnh."""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán.')
    """Mã chứng khoán."""

    exec_type: StockOrderDirection | MISSING = Field(MISSING, alias='execType')
    price: int | MISSING = Field(MISSING, description='Giá đặt.')
    """Giá đặt."""

    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt.')
    """Khối lượng đặt."""

    status: str | MISSING = Field(MISSING, description='Trạng thái lệnh.')
    """Trạng thái lệnh."""


class OrderDetailItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_id: str | MISSING = Field(
        MISSING, alias='orderID', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản.'
    )
    """Số tiểu khoản."""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán.')
    """Mã chứng khoán."""

    exec_type: StockOrderDirection | MISSING = Field(MISSING, alias='execType')
    order_qtty: float | MISSING = Field(
        MISSING, alias='orderQtty', description='Khối lượng đặt.'
    )
    """Khối lượng đặt."""

    exec_qtty: float | MISSING = Field(
        MISSING, alias='execQtty', description='Khối lượng khớp.'
    )
    """Khối lượng khớp."""

    price_type: StockPriceType | MISSING = Field(MISSING, alias='priceType')
    limit_price: float | MISSING = Field(
        MISSING, alias='limitPrice', description='Giá đặt lệnh.'
    )
    """Giá đặt lệnh."""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp trung bình.'
    )
    """Giá khớp trung bình."""

    or_status: StockOrderStatus | MISSING = Field(MISSING, alias='orStatus')
    txdate: str | MISSING = Field(MISSING, description='Ngày đặt lệnh (RFC 3339).')
    """Ngày đặt lệnh (RFC 3339)."""

    txtime: str | MISSING = Field(MISSING, description='Giờ đặt lệnh.')
    """Giờ đặt lệnh."""


class DerivativeOrderCancelResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str = Field('Web.changeOrder', description='Web.changeOrder.')
    """Web.changeOrder."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeOrderCancelItem] | MISSING = MISSING


class DerivativeOrderChangeResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str = Field('Web.changeOrder', description='Tên lệnh.')
    """Tên lệnh."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeOrderChangeItem] | MISSING = MISSING


class DerivativeConditionOrderDetailItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_no: str | MISSING = Field(
        MISSING, alias='orderNo', description='Số hiệu lệnh.'
    )
    """Số hiệu lệnh."""

    group_order: str | MISSING = Field(
        MISSING, alias='groupOrder', description='Mã nhóm lệnh.'
    )
    """Mã nhóm lệnh."""

    pk_order_no: str | MISSING = Field(
        MISSING, alias='pk_orderNo', description='Key lệnh.'
    )
    """Key lệnh."""

    account_code: str | MISSING = Field(
        MISSING, alias='accountCode', description='Mã tài khoản.'
    )
    """Mã tài khoản."""

    side: DerivativeSide | MISSING = MISSING
    symbol: str | MISSING = Field(MISSING, description='Mã hợp đồng.')
    """Mã hợp đồng."""

    show_price: float | MISSING = Field(
        MISSING, alias='showPrice', description='Giá đặt.'
    )
    """Giá đặt."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng đặt.')
    """Khối lượng đặt."""

    so_price: float | MISSING = Field(MISSING, alias='soPrice', description='Giá stop.')
    """Giá stop."""

    order_type: str | MISSING = Field(
        MISSING, alias='orderType', description='SL = giá >=, SU = giá <=.'
    )
    """SL = giá >=, SU = giá <=."""

    from_time: str | MISSING = Field(MISSING, description='Thời gian bắt đầu hiệu lực.')
    """Thời gian bắt đầu hiệu lực."""

    exp_time: str | MISSING = Field(MISSING, description='Thời gian hết hạn.')
    """Thời gian hết hạn."""

    status: DerivativeConditionalStatus | MISSING = MISSING
    send_time: str | MISSING = Field(MISSING, description='Thời gian gửi lệnh.')
    """Thời gian gửi lệnh."""

    notes: str | MISSING = Field(
        MISSING, description='Loại lệnh: SL/TP, Stop order, Arbitrage.'
    )
    """Loại lệnh: SL/TP, Stop order, Arbitrage."""


class DerivativeConditionOrderPlaceItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = MISSING
    status: str | MISSING = MISSING
    msg_type: str | MISSING = MISSING
    show_price: str | MISSING = Field(MISSING, alias='showPrice')
    order_time: str | MISSING = Field(MISSING, alias='orderTime')
    account_code: str | MISSING = Field(MISSING, alias='accountCode')
    order_no: int | MISSING = Field(MISSING, alias='orderNo')
    match_volume: float | MISSING = Field(MISSING, alias='matchVolume')
    side: DerivativeSide | MISSING = MISSING
    volume: str | MISSING = MISSING
    pk_order_no: str | MISSING = Field(MISSING, alias='pk_orderNo')
    channel: str | MISSING = MISSING
    group: str | MISSING = MISSING
    quote: str | MISSING = MISSING


class DerivativeOrderInDayItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_no: str = Field(..., alias='orderNo', description='Số hiệu lệnh.')
    """Số hiệu lệnh."""

    pk_order_no: str = Field(..., alias='pk_orderNo', description='Key lệnh.')
    """Key lệnh."""

    ref_id: str | MISSING = Field(
        MISSING, alias='refId', description='Reference ID của lệnh.'
    )
    """Reference ID của lệnh."""

    order_time: str | MISSING = Field(
        MISSING, alias='orderTime', description='Thời gian đặt lệnh.'
    )
    """Thời gian đặt lệnh."""

    account_code: str | MISSING = Field(
        MISSING, alias='accountCode', description='Mã tài khoản.'
    )
    """Mã tài khoản."""

    side: DerivativeSide
    symbol: str = Field(..., description='Mã hợp đồng.')
    """Mã hợp đồng."""

    volume: float = Field(..., description='Khối lượng đặt.')
    """Khối lượng đặt."""

    show_price: str = Field(..., alias='showPrice', description='Giá đặt.')
    """Giá đặt."""

    match_volume: float = Field(
        ..., alias='matchVolume', description='Khối lượng khớp.'
    )
    """Khối lượng khớp."""

    status: str = Field(..., description='Trạng thái lệnh.')
    """Trạng thái lệnh."""

    order_status: str | MISSING = Field(
        MISSING, alias='orderStatus', description='Mã trạng thái lệnh.'
    )
    """Mã trạng thái lệnh."""

    channel: str | MISSING = Field(MISSING, description='Kênh đặt lệnh.')
    """Kênh đặt lệnh."""

    group: str | MISSING = Field(MISSING, description='Nhóm sản phẩm.')
    """Nhóm sản phẩm."""

    is_cancel: str = Field(
        ..., alias='isCancel', description='0 = không thể hủy, 1 = có thể hủy.'
    )
    """0 = không thể hủy, 1 = có thể hủy."""

    is_amend: str = Field(
        ..., alias='isAmend', description='0 = không thể sửa, 1 = có thể sửa.'
    )
    """0 = không thể sửa, 1 = có thể sửa."""

    order_type: str | MISSING = Field(
        MISSING, alias='orderType', description='Loại lệnh.'
    )
    """Loại lệnh."""

    source: str | MISSING = Field(MISSING, description='Nguồn đặt lệnh.')
    """Nguồn đặt lệnh."""


class DerivativeOrderPlaceResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str
    rc: str
    rs: str
    o_id: str = Field(..., alias='oID')
    data: list[DerivativeOrderPlaceItem]


class DerivativeConditionOrderChangeV2Response(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Lệnh gọi (echo).')
    """Lệnh gọi (echo)."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeConditionOrderChangeV2Item] | MISSING = MISSING


class OrderMatchingDetailsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_count: int | MISSING = Field(
        MISSING, alias='totalCount', description='Tổng số bản ghi trả ra.'
    )
    """Tổng số bản ghi trả ra."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng phần tử 1 trang.'
    )
    """Số lượng phần tử 1 trang."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Mục lục trang.'
    )
    """Mục lục trang."""

    data: list[MatchingItem] | MISSING = MISSING


class OrdersResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    orders: list[OrderItem] | MISSING = Field(
        MISSING, description='Danh sách lệnh trong sổ lệnh.'
    )
    """Danh sách lệnh trong sổ lệnh."""


class OrderDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    object: str | MISSING = Field(MISSING, description="Mặc định = 'List'.")
    """Mặc định = 'List'."""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Kích thước trang.'
    )
    """Kích thước trang."""

    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Mục lục trang.'
    )
    """Mục lục trang."""

    total_count: int | MISSING = Field(
        MISSING, alias='totalCount', description='Tổng số bản ghi.'
    )
    """Tổng số bản ghi."""

    data: list[OrderDetailItem] | MISSING = MISSING


class DerivativeConditionOrderDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str = Field('Web.Order.ConditionOrder', description='Tên lệnh.')
    """Tên lệnh."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeConditionOrderDetailItem] | MISSING = Field(
        MISSING, description='Danh sách lệnh điều kiện.'
    )
    """Danh sách lệnh điều kiện."""


class DerivativeConditionOrderPlaceResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Lệnh gọi (echo).')
    """Lệnh gọi (echo)."""

    rc: str | MISSING = Field(MISSING, description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeConditionOrderPlaceItem] | MISSING = Field(
        MISSING, description='Danh sách kết quả đặt lệnh.'
    )
    """Danh sách kết quả đặt lệnh."""


class DerivativeOrdersInDayResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    cmd: str | MISSING = Field(MISSING, description='Lệnh gọi (echo).')
    """Lệnh gọi (echo)."""

    rc: str = Field(..., description='Mã kết quả, 1 = thành công.')
    """Mã kết quả, 1 = thành công."""

    data: list[DerivativeOrderInDayItem] = Field(
        ..., description='Danh sách lệnh thường.'
    )
    """Danh sách lệnh thường."""
