# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import EnvelopeBase


class UserProfile(BaseModel):
    """
    Profile user trả về từ `GET /users/v1/users/me`.

    Chỉ `user_id` là field luôn có — bootstrap flow chỉ cần field này. Các
    field khác là chuẩn của endpoint user Finhay.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    user_id: int = Field(
        ...,
        description='User ID của Finhay. Dùng làm path variable `{userId}` ở mọi endpoint user-scoped.',
    )
    """User ID của Finhay. Dùng làm path variable `{userId}` ở mọi endpoint user-scoped."""


class UserProfileResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: UserProfile


class SubAccount(BaseModel):
    """
    1 item tiểu khoản trong response của
    `GET /users/v1/users/{userId}/sub-accounts`.

    Bootstrap flow dùng `id` (làm `subAccountId` cho path) và `type` (chọn
    `Normal` hay `Margin` tuỳ nhu cầu).

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: str = Field(
        ...,
        description='ID tiểu khoản. Dùng làm giá trị thay cho path variable `{subAccountId}`.',
    )
    """ID tiểu khoản. Dùng làm giá trị thay cho path variable `{subAccountId}`."""

    cust_id: str | MISSING = Field(
        MISSING, description='ID khách hàng cha (chung cho mọi tiểu khoản của 1 user).'
    )
    """ID khách hàng cha (chung cho mọi tiểu khoản của 1 user)."""

    name: str | MISSING = Field(MISSING, description='Họ tên đầy đủ của user.')
    """Họ tên đầy đủ của user."""

    depository_number: str | MISSING = Field(
        MISSING, description='Số lưu ký chứng khoán do VSDC cấp.'
    )
    """Số lưu ký chứng khoán do VSDC cấp."""

    product_type_name: str | MISSING = Field(
        MISSING,
        description='Hậu tố loại sản phẩm trong `sub_account_ext`. `.1` cho tiểu khoản\nthường, `.6` cho tiểu khoản margin.\n',
    )
    """
    Hậu tố loại sản phẩm trong `sub_account_ext`. `.1` cho tiểu khoản
    thường, `.6` cho tiểu khoản margin.

    """

    sub_account_ext: str = Field(
        ...,
        description='Định danh tiểu khoản dạng mở rộng (`{depository_number}{product_type_name}`).',
    )
    """Định danh tiểu khoản dạng mở rộng (`{depository_number}{product_type_name}`)."""

    type: str = Field(
        ...,
        description='Loại tiểu khoản — `Normal` (tiểu khoản thường) hoặc `Margin` (tiểu khoản ký quỹ).',
    )
    """Loại tiểu khoản — `Normal` (tiểu khoản thường) hoặc `Margin` (tiểu khoản ký quỹ)."""


class SubAccountsResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[SubAccount]


class AccountSummary(BaseModel):
    """
    Chi tiết tiểu khoản, trả về từ `/trading/accounts/{subAccountId}/summary`.

    Mọi giá trị tiền là `int64` VND trừ khi ghi chú khác.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    balance: int | MISSING = Field(MISSING, description='Available balance.')
    """Available balance."""

    ci_balance: int | MISSING = MISSING
    td_balance: int | MISSING = MISSING
    interest_balance: int | MISSING = MISSING
    ca_receiving: int | MISSING = MISSING
    receiving_t1: int | MISSING = Field(MISSING, description='Receiving amount T+1.')
    """Receiving amount T+1."""

    receiving_t2: int | MISSING = Field(MISSING, description='Receiving amount T+2.')
    """Receiving amount T+2."""

    receiving_t3: int | MISSING = Field(MISSING, description='Receiving amount T+3.')
    """Receiving amount T+3."""

    securities_amt: int | MISSING = Field(MISSING, description='Securities amount.')
    """Securities amount."""

    total_debt_amt: int | MISSING = Field(MISSING, description='Total debt amount.')
    """Total debt amount."""

    secure_amt: int | MISSING = MISSING
    trf_buy_amt: int | MISSING = MISSING
    margin_amt: int | MISSING = Field(MISSING, description='Margin amount.')
    """Margin amount."""

    t0_debt_amt: int | MISSING = Field(MISSING, description='T+0 debt amount.')
    """T+0 debt amount."""

    advanced_amt: int | MISSING = Field(MISSING, description='Advanced amount.')
    """Advanced amount."""

    df_debt_amt: int | MISSING = MISSING
    td_debt_amt: int | MISSING = MISSING
    cidepo_fee_acr: int | MISSING = MISSING
    net_asset_value: int | MISSING = Field(MISSING, description='Net asset value.')
    """Net asset value."""

    mrcr_limit: int | MISSING = Field(MISSING, description='Margin credit limit.')
    """Margin credit limit."""

    debt_amt: int | MISSING = MISSING
    advance_max_amt_fee: int | MISSING = MISSING
    receiving_amt: int | MISSING = MISSING
    margin_rate: int | MISSING = Field(MISSING, description='Margin rate.')
    """Margin rate."""

    sms_fee_amt: int | MISSING = MISSING
    ibroker_fee_amt: int | MISSING = MISSING
    hold_balance: int | MISSING = MISSING
    mri_rate: int | MISSING = MISSING
    mrm_rate: int | MISSING = MISSING
    cidepo_fee: int | MISSING = MISSING
    td_int_amt: int | MISSING = MISSING
    add_vnd: int | MISSING = MISSING
    add_vnd_1: int | MISSING = MISSING
    core_bank: str | MISSING = Field(MISSING, description='Core bank code.')
    """Core bank code."""

    bankacct_no: str | MISSING = Field(MISSING, description='Bank account number.')
    """Bank account number."""

    bank_name: str | MISSING = Field(MISSING, description='Bank name.')
    """Bank name."""

    emk_amt: int | MISSING = MISSING
    baldefovd: str | MISSING = MISSING
    mrcr_limit_max: int | MISSING = Field(
        MISSING, description='Maximum margin credit limit.'
    )
    """Maximum margin credit limit."""


class AccountSummaryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: AccountSummary


class UserRightStatus(StrEnum):
    """
    Trạng thái xử lý quyền cổ đông (phía hệ thống).

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `WAIT_FOR_REVIEW` | Chờ review |
    | `WAIT_EXECUTED` | Chờ thực hiện |
    | `WAITING_FOR_APPROVE` | Chờ phê duyệt |
    | `NAVIGATING` | Chuyển sang bước kế tiếp |
    | `COMPLETED` | Đã hoàn tất |
    | `ALLOCATION_COMPLETED` | Đã phân bổ xong |
    | `CANCELED` | Đã huỷ |
    | `EMPTY_STOCK` | Không còn stock để phân bổ |
    | `APPROVED` | Đã phê duyệt |
    | `REJECTED` | Từ chối |
    | `READY_FOR_TRADE` | Sẵn sàng giao dịch |
    | `READY_FOR_CLOSE` | Sẵn sàng đóng |
    | `STOCK_ALLOTTED` | Đã chia stock |
    | `MONEY_ALLOTTED` | Đã chia tiền |
    | `PARTIALLY_DONE` | Hoàn tất 1 phần |
    | `VERIFIED` | Đã xác nhận |
    | `DELETED` | Đã xoá |
    | `REGISTERED` | Đã đăng ký |
    | `UNKNOWN` | Không xác định / fallback |

    """

    WAIT_FOR_REVIEW = 'WAIT_FOR_REVIEW'
    WAIT_EXECUTED = 'WAIT_EXECUTED'
    WAITING_FOR_APPROVE = 'WAITING_FOR_APPROVE'
    NAVIGATING = 'NAVIGATING'
    COMPLETED = 'COMPLETED'
    ALLOCATION_COMPLETED = 'ALLOCATION_COMPLETED'
    CANCELED = 'CANCELED'
    EMPTY_STOCK = 'EMPTY_STOCK'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    READY_FOR_TRADE = 'READY_FOR_TRADE'
    READY_FOR_CLOSE = 'READY_FOR_CLOSE'
    STOCK_ALLOTTED = 'STOCK_ALLOTTED'
    MONEY_ALLOTTED = 'MONEY_ALLOTTED'
    PARTIALLY_DONE = 'PARTIALLY_DONE'
    VERIFIED = 'VERIFIED'
    DELETED = 'DELETED'
    REGISTERED = 'REGISTERED'
    UNKNOWN = 'UNKNOWN'


class UserRightRegisterStatus(StrEnum):
    """
    Trạng thái đăng ký quyền cổ đông (phía user).

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `UNREGISTER` | Chưa đăng ký |
    | `REGISTERED` | Đã đăng ký |
    | `EXPIRED` | Hết hạn đăng ký |
    | `RECEIVED` | Đã nhận quyền |
    | `PARTIAL_REGISTERED` | Đăng ký 1 phần |
    | `PENDING` | Đang xử lý |
    | `PARTIAL_RECEIVED` | Đã nhận 1 phần |
    | `WAIT_REGISTER` | Đang chờ đăng ký |
    | `REGISTERED_V2` | Đã đăng ký (schema v2) |
    | `WAIT_RECEIVE` | Đang chờ nhận |
    | `WAIT_STOCK` | Đang chờ phân bổ stock |
    | `PARTIAL_RECEIVED_V2` | Đã nhận 1 phần (schema v2) |
    | `UNKNOWN` | Không xác định / fallback |

    """

    UNREGISTER = 'UNREGISTER'
    REGISTERED = 'REGISTERED'
    EXPIRED = 'EXPIRED'
    RECEIVED = 'RECEIVED'
    PARTIAL_REGISTERED = 'PARTIAL_REGISTERED'
    PENDING = 'PENDING'
    PARTIAL_RECEIVED = 'PARTIAL_RECEIVED'
    WAIT_REGISTER = 'WAIT_REGISTER'
    REGISTERED_V2 = 'REGISTERED_V2'
    WAIT_RECEIVE = 'WAIT_RECEIVE'
    WAIT_STOCK = 'WAIT_STOCK'
    PARTIAL_RECEIVED_V2 = 'PARTIAL_RECEIVED_V2'
    UNKNOWN = 'UNKNOWN'


class UserRightType(StrEnum):
    """
    Loại quyền cổ đông.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `OTC_BOND_INTEREST` | Trả lãi trái phiếu OTC |
    | `SHAREHOLDER_MEETING` | Họp đại hội cổ đông |
    | `SOLICIT_SHAREHOLDER_OPINIONS` | Lấy ý kiến cổ đông bằng văn bản |
    | `CASH_DIVIDEND` | Cổ tức tiền mặt |
    | `STOCK_DIVIDEND` | Cổ tức bằng stock |
    | `STOCK_RIGHT` | Phát hành quyền mua stock |
    | `BOND_INTEREST` | Trả lãi trái phiếu |
    | `BOND_PRINCIPAL_AND_INTEREST` | Trả gốc + lãi trái phiếu |
    | `CONVERT_BONDS_TO_STOCKS` | Chuyển đổi trái phiếu sang stock |
    | `CONVERT_STOCKS_TO_OTHER_STOCKS` | Chuyển đổi stock sang stock khác |
    | `BONUS_SHARES` | Thưởng stock |
    | `VOTING_RIGHTS` | Quyền biểu quyết |
    | `CONVERTIBLE_BOND` | Sự kiện trái phiếu chuyển đổi |
    | `TRANSFER_PENDING_STOCKS` | Chuyển stock đang chờ |
    | `WARRANT_DIVIDENDS` | Cổ tức chứng quyền |

    """

    OTC_BOND_INTEREST = 'OTC_BOND_INTEREST'
    SHAREHOLDER_MEETING = 'SHAREHOLDER_MEETING'
    SOLICIT_SHAREHOLDER_OPINIONS = 'SOLICIT_SHAREHOLDER_OPINIONS'
    CASH_DIVIDEND = 'CASH_DIVIDEND'
    STOCK_DIVIDEND = 'STOCK_DIVIDEND'
    STOCK_RIGHT = 'STOCK_RIGHT'
    BOND_INTEREST = 'BOND_INTEREST'
    BOND_PRINCIPAL_AND_INTEREST = 'BOND_PRINCIPAL_AND_INTEREST'
    CONVERT_BONDS_TO_STOCKS = 'CONVERT_BONDS_TO_STOCKS'
    CONVERT_STOCKS_TO_OTHER_STOCKS = 'CONVERT_STOCKS_TO_OTHER_STOCKS'
    BONUS_SHARES = 'BONUS_SHARES'
    VOTING_RIGHTS = 'VOTING_RIGHTS'
    CONVERTIBLE_BOND = 'CONVERTIBLE_BOND'
    TRANSFER_PENDING_STOCKS = 'TRANSFER_PENDING_STOCKS'
    WARRANT_DIVIDENDS = 'WARRANT_DIVIDENDS'


class UserRight(BaseModel):
    """
    1 quyền cổ đông của tiểu khoản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_id: str | MISSING = Field(MISSING, alias='accountId')
    depository_number: str | MISSING = Field(MISSING, alias='depositoryNumber')
    full_name: str | MISSING = Field(MISSING, alias='fullName')
    own_number_of_share: int | MISSING = Field(
        MISSING,
        alias='ownNumberOfShare',
        description='Number of shares owned at record date.',
    )
    """Number of shares owned at record date."""

    ratio: str | MISSING = Field(MISSING, description='Right ratio (e.g. `1:5`).')
    """Right ratio (e.g. `1:5`)."""

    status: UserRightStatus | MISSING = MISSING
    user_right_register_status: UserRightRegisterStatus | MISSING = Field(
        MISSING, alias='userRightRegisterStatus'
    )
    ca_mast_id: str | MISSING = Field(
        MISSING, alias='caMastId', description='Corporate action master ID.'
    )
    """Corporate action master ID."""

    amount: int | MISSING = MISSING
    symbol: str | MISSING = MISSING
    to_symbol: str | None | MISSING = Field(
        MISSING,
        alias='toSymbol',
        description='Target symbol (for stock-conversion events).',
    )
    """Target symbol (for stock-conversion events)."""

    number_of_waiting_stock: int | MISSING = Field(
        MISSING, alias='numberOfWaitingStock'
    )
    waiting_amount_for_return: int | MISSING = Field(
        MISSING, alias='waitingAmountForReturn'
    )
    right_off_rate: str | MISSING = Field(
        MISSING, alias='rightOffRate', description='Right offering rate.'
    )
    """Right offering rate."""

    buy_price: int | MISSING = Field(
        MISSING, alias='buyPrice', description='Subscription price (for stock rights).'
    )
    """Subscription price (for stock rights)."""

    allow_register: bool | MISSING = Field(
        MISSING, alias='allowRegister', description='Whether registration is allowed.'
    )
    """Whether registration is allowed."""

    total_stocks_can_buy: int | MISSING = Field(MISSING, alias='totalStocksCanBuy')
    total_pay_amount: int | MISSING = Field(MISSING, alias='totalPayAmount')
    start_date: date | MISSING = Field(MISSING, alias='startDate')
    finish_date: date | MISSING = Field(MISSING, alias='finishDate')
    start_date_transfer: date | MISSING = Field(MISSING, alias='startDateTransfer')
    action_date: date | MISSING = Field(
        MISSING, alias='actionDate', description='Record date / ex-date.'
    )
    """Record date / ex-date."""

    finish_date_transfer: date | MISSING = Field(MISSING, alias='finishDateTransfer')
    report_date: date | MISSING = Field(
        MISSING, alias='reportDate', description='Used for sorting (descending).'
    )
    """Used for sorting (descending)."""

    type: UserRightType | MISSING = MISSING
    stock_name: str | MISSING = Field(MISSING, alias='stockName')
    total_volume: int | MISSING = Field(MISSING, alias='totalVolume')
    total_value: int | MISSING = Field(MISSING, alias='totalValue')
    reference_price: int | MISSING = Field(MISSING, alias='referencePrice')
    close_price: int | MISSING = Field(MISSING, alias='closePrice')
    ceiling_price: int | MISSING = Field(MISSING, alias='ceilingPrice')
    floor_price: int | MISSING = Field(MISSING, alias='floorPrice')
    predict_price: int | MISSING = Field(MISSING, alias='predictPrice')
    change_price: int | MISSING = Field(MISSING, alias='changePrice')
    has_read: bool | MISSING = Field(
        MISSING,
        alias='hasRead',
        description='Whether the user has read this right notification.',
    )
    """Whether the user has read this right notification."""


class UserRightsResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[UserRight]


class PnlToday(BaseModel):
    """
    Lãi / lỗ hôm nay của user, tổng hợp qua mọi tiểu khoản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    sub_account_id: str | MISSING = Field(
        MISSING, description='ID tiểu khoản hoặc `ALL`.'
    )
    """ID tiểu khoản hoặc `ALL`."""

    pnl_amount: int | MISSING = Field(
        MISSING, description='Số tiền lãi / lỗ hôm nay (VND).'
    )
    """Số tiền lãi / lỗ hôm nay (VND)."""

    pnl_rate: float | MISSING = Field(
        MISSING, description='Tỷ lệ lãi / lỗ hôm nay (%).'
    )
    """Tỷ lệ lãi / lỗ hôm nay (%)."""


class PnlTodayResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: PnlToday


class ProductsSummary(BaseModel):
    """
    Giá trị tài sản chia theo loại sản phẩm.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total: float | MISSING = Field(MISSING, description='Total product value.')
    """Total product value."""

    stock: float | MISSING = Field(MISSING, description='Stock value.')
    """Stock value."""

    fund: float | MISSING = Field(MISSING, description='Fund value.')
    """Fund value."""

    saving: float | None | MISSING = Field(
        MISSING, description='Saving amount (may be null).'
    )
    """Saving amount (may be null)."""

    bond: float | MISSING = Field(
        MISSING,
        description='HayBond product value. **Lưu ý**: field này chỉ đại diện cho sản phẩm\nHayBond — KHÔNG phải trái phiếu doanh nghiệp / chính phủ thông thường.\n',
    )
    """
    HayBond product value. **Lưu ý**: field này chỉ đại diện cho sản phẩm
    HayBond — KHÔNG phải trái phiếu doanh nghiệp / chính phủ thông thường.

    """

    hay0: float | MISSING = Field(MISSING, description='Hay0 NAV.')
    """Hay0 NAV."""

    hay0_interest: float | MISSING = Field(MISSING, description='Hay0 interest.')
    """Hay0 interest."""

    hay0_depositing: float | MISSING = Field(
        MISSING, description='Hay0 amount being deposited.'
    )
    """Hay0 amount being deposited."""

    hay0_withdrawing: float | MISSING = Field(
        MISSING, description='Hay0 amount being withdrawn.'
    )
    """Hay0 amount being withdrawn."""


class MoneySummary(BaseModel):
    """
    Số dư tiền mặt.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total: float | MISSING = Field(MISSING, description='Total cash.')
    """Total cash."""

    ci_balance: float | MISSING = Field(MISSING, description='Cash balance in account.')
    """Cash balance in account."""

    ca_receiving: float | MISSING = Field(MISSING, description='Dividend cash pending.')
    """Dividend cash pending."""

    emk_amt: float | MISSING = Field(MISSING, description='Other blocked funds.')
    """Other blocked funds."""

    receiving_amt: float | MISSING = Field(MISSING, description='Cash to receive.')
    """Cash to receive."""

    baldefovd: float | MISSING = Field(
        MISSING, description='Available withdrawable amount.'
    )
    """Available withdrawable amount."""


class DebtSummary(BaseModel):
    """
    Chi tiết dư nợ.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total: float | MISSING = Field(MISSING, description='Total debt.')
    """Total debt."""

    secure_amount: float | MISSING = Field(MISSING, description='Secured loan amount.')
    """Secured loan amount."""

    advance_amt: float | MISSING = Field(MISSING, description='Advanced amount.')
    """Advanced amount."""

    sms_fee_amt: float | MISSING = Field(MISSING, description='SMS fee amount.')
    """SMS fee amount."""

    cidepo_fee_acr: float | MISSING = Field(MISSING, description='CIDEPO fee accrual.')
    """CIDEPO fee accrual."""

    owe_deposit: float | MISSING = Field(MISSING, description='Deposit owed.')
    """Deposit owed."""


class PnlEntry(BaseModel):
    """
    Số tiền PnL và tỷ lệ PnL cho 1 loại tài sản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pnl: float | MISSING = Field(MISSING, description='Profit/loss amount.')
    """Profit/loss amount."""

    pnl_rate: float | MISSING = Field(
        MISSING, description='Profit/loss rate (percentage).'
    )
    """Profit/loss rate (percentage)."""


class PnlSummary(BaseModel):
    """
    PnL chia theo loại tài sản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    stock: PnlEntry | MISSING = MISSING
    fund: PnlEntry | MISSING = MISSING


class UserAssetsSummary(BaseModel):
    """
    Tổng quan tài sản / số dư của user qua mọi loại sản phẩm (stock, fund,
    bond, hay0), kèm tiền mặt, dư nợ và PnL.

    Với user Level 0 / 1, `products.stock`, `products.fund`, `products.bond`
    và các entry trong `pnl` đều trả về `0`. `products.saving` có thể `null`.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    net_asset_value: float | MISSING = Field(
        MISSING, description='Total net asset value.'
    )
    """Total net asset value."""

    products: ProductsSummary | MISSING = MISSING
    money: MoneySummary | MISSING = MISSING
    debt: DebtSummary | MISSING = MISSING
    pnl: PnlSummary | MISSING = MISSING


class UserAssetsSummaryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: UserAssetsSummary
