# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class EnvelopeBase(BaseModel):
    """
    Các field chung của envelope trong mọi response của Finhay API.

    - `error_code` là `"0"` (string) khi thành công, mã khác `"0"` khi lỗi.
    - `message` là thông điệp ngắn từ server.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    error_code: str | MISSING = Field(
        MISSING, description='`"0"` khi thành công, khác `"0"` khi lỗi.'
    )
    """`"0"` khi thành công, khác `"0"` khi lỗi."""

    message: str | MISSING = Field(MISSING, description='Thông điệp trạng thái dễ đọc.')
    """Thông điệp trạng thái dễ đọc."""


class ErrorBody(BaseModel):
    """
    Body của response khi 4xx / 5xx.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    error_code: str = Field(
        ...,
        description='Mã lỗi khác `"0"` (ví dụ `AUTH_SIGNATURE_INVALID`, `RATE_LIMIT_EXCEEDED`, …).',
    )
    """Mã lỗi khác `"0"` (ví dụ `AUTH_SIGNATURE_INVALID`, `RATE_LIMIT_EXCEEDED`, …)."""

    message: str = Field(..., description='Thông điệp lỗi (tiếng Anh, từ server).')
    """Thông điệp lỗi (tiếng Anh, từ server)."""


class OrderType(StrEnum):
    """
    Loại order được đặt.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `LO` | Giới hạn (Limit Order) |
    | `MP` | Khớp giá thị trường |
    | `ATO` | Phiên mở cửa |
    | `ATC` | Phiên đóng cửa |
    | `MAK` | Khớp và huỷ |
    | `MOK` | Khớp hoặc huỷ toàn bộ |
    | `MTL` | Khớp đến giới hạn rồi chuyển limit |
    | `PLO` | Post-limit (HNX, sau giờ khớp chính) |
    | `FOK` | Khớp toàn bộ hoặc huỷ |
    | `FAK` | Khớp phần nào được và huỷ phần còn lại |

    """

    LO = 'LO'
    MP = 'MP'
    ATO = 'ATO'
    ATC = 'ATC'
    MAK = 'MAK'
    MOK = 'MOK'
    MTL = 'MTL'
    PLO = 'PLO'
    FOK = 'FOK'
    FAK = 'FAK'
