# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import StrEnum
from typing import Dict

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import EnvelopeBase, OrderType


class Exchange(StrEnum):
    """
    Mã sàn chứng khoán Việt Nam.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `HOSE` | Sở Giao dịch Chứng khoán TP. HCM |
    | `HNX` | Sở Giao dịch Chứng khoán Hà Nội |
    | `UPCOM` | Thị trường công ty đại chúng chưa niêm yết |
    | `HCX` | Sàn hàng hoá TP. HCM (phái sinh) |

    """

    HOSE = 'HOSE'
    HNX = 'HNX'
    UPCOM = 'UPCOM'
    HCX = 'HCX'


class EconomicCountry(StrEnum):
    """
    Tên quốc gia hiển thị (full name) cho dữ liệu kinh tế. Dùng trong
    `/market/calendar`.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `China` | Trung Quốc |
    | `Euro Area` | Khu vực đồng Euro |
    | `Japan` | Nhật Bản |
    | `United States` | Mỹ |
    | `United Kingdom` | Anh |
    | `Vietnam` | Việt Nam |

    """

    CHINA = 'China'
    EURO_AREA = 'Euro Area'
    JAPAN = 'Japan'
    UNITED_STATES = 'United States'
    UNITED_KINGDOM = 'United Kingdom'
    VIETNAM = 'Vietnam'


class IndexRecommendationReport(BaseModel):
    """
    1 báo cáo khuyến nghị cụ thể.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    stock: str | MISSING = Field(MISSING, description='Mã stock.')
    """Mã stock."""

    title: str | None | MISSING = Field(MISSING, description='Tiêu đề báo cáo.')
    """Tiêu đề báo cáo."""

    source: str | None | MISSING = Field(
        MISSING, description='Nguồn báo cáo (mặc định `VietStock`).'
    )
    """Nguồn báo cáo (mặc định `VietStock`)."""

    recommendation_price: float | None | MISSING = Field(
        MISSING, description='Giá khuyến nghị mua vào. Hiện luôn là `null`.'
    )
    """Giá khuyến nghị mua vào. Hiện luôn là `null`."""

    target_price: float | None | MISSING = Field(
        MISSING, description='Giá mục tiêu (target price).'
    )
    """Giá mục tiêu (target price)."""

    publish_date: AwareDatetime | None | MISSING = Field(
        MISSING, description='Ngày phát hành báo cáo.'
    )
    """Ngày phát hành báo cáo."""

    description: str | None | MISSING = Field(
        MISSING, description='Mô tả ngắn / tóm tắt nội dung báo cáo.'
    )
    """Mô tả ngắn / tóm tắt nội dung báo cáo."""

    download_url: str | None | MISSING = Field(
        MISSING, description='URL tải báo cáo bản đầy đủ (PDF).'
    )
    """URL tải báo cáo bản đầy đủ (PDF)."""

    created_at: AwareDatetime | None | MISSING = MISSING
    updated_at: AwareDatetime | None | MISSING = MISSING


class RecommendationReport(BaseModel):
    """
    Payload báo cáo khuyến nghị — chứa text khuyến nghị mới nhất và danh
    sách các report cụ thể. Trả về `[]` (array rỗng) khi stock không có
    báo cáo nào — xem `oneOf` trong response của endpoint.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    recommendation: str | None | MISSING = Field(
        MISSING,
        description='Latest recommendation description (from the most recent report).',
    )
    """Latest recommendation description (from the most recent report)."""

    recommendation_reports: list[IndexRecommendationReport] | MISSING = Field(
        MISSING, alias='recommendationReports'
    )


class RecommendationReportsResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: RecommendationReport | None = Field(
        ...,
        description='Payload báo cáo khuyến nghị, hoặc `null` khi symbol không có báo cáo nào.\n',
    )
    """
    Payload báo cáo khuyến nghị, hoặc `null` khi symbol không có báo cáo nào.

    """


class Resolution(StrEnum):
    """
    Độ phân giải nến cho các endpoint `/market/quotes/{class}/{symbol}/history`.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `1D` | Theo ngày (mặc định) |
    | `5` | 5 phút |
    | `15` | 15 phút |
    | `30` | 30 phút |
    | `1H` | Theo giờ |
    | `4H` | 4 giờ |

    """

    DAILY = '1D'
    FIVE_MINUTE = '5'
    FIFTEEN_MINUTE = '15'
    THIRTY_MINUTE = '30'
    HOURLY = '1H'
    FOUR_HOUR = '4H'


class Industry(BaseModel):
    """
    Industry-average ratios.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pe: float | None | MISSING = MISSING
    pb: float | None | MISSING = MISSING
    ev_ebitda: float | None | MISSING = MISSING


class FinancialOverview(BaseModel):
    """
    Các chỉ số và tỷ số tài chính quan trọng của 1 mã stock.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pe: float | None | MISSING = Field(MISSING, description='Price-to-Earnings ratio.')
    """Price-to-Earnings ratio."""

    pb: float | None | MISSING = Field(MISSING, description='Price-to-Book ratio.')
    """Price-to-Book ratio."""

    ev_ebitda: float | None | MISSING = Field(MISSING, description='EV / EBITDA ratio.')
    """EV / EBITDA ratio."""

    industry: Industry | MISSING = Field(
        MISSING, description='Industry-average ratios.'
    )
    """Industry-average ratios."""

    gross_margin: float | None | MISSING = Field(
        MISSING, description='Gross profit margin.'
    )
    """Gross profit margin."""

    roe: float | None | MISSING = Field(MISSING, description='Return on Equity.')
    """Return on Equity."""

    eps: float | None | MISSING = Field(MISSING, description='Earnings per Share.')
    """Earnings per Share."""

    dividend_yield: float | None | MISSING = MISSING
    nim: float | None | MISSING = Field(
        MISSING, description='Net Interest Margin (banks only).'
    )
    """Net Interest Margin (banks only)."""

    margin_loan_to_equity_ratio: float | None | MISSING = Field(
        MISSING, description='Margin loan to equity ratio (securities firms only).'
    )
    """Margin loan to equity ratio (securities firms only)."""

    roa: float | None | MISSING = Field(MISSING, description='Return on Assets.')
    """Return on Assets."""


class FinancialOverviewResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: FinancialOverview


class FinancialPeriod(StrEnum):
    """
    Kỳ báo cáo cho truy vấn tài chính doanh nghiệp.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `annual` | Theo năm |
    | `quarterly` | Theo quý |

    """

    ANNUAL = 'annual'
    QUARTERLY = 'quarterly'


class FinancialAnalysisEntry(BaseModel):
    """
    Các chỉ số tài chính cho 1 kỳ báo cáo. `year` luôn có; `quarter` chỉ có
    khi `period=quarterly`. Các field còn lại là metric code động (ví dụ
    `pe`, `roe`, `eps`, `pb`) nhận giá trị số hoặc null — bộ key thay đổi
    theo loại doanh nghiệp (ngân hàng có `nim`, sản xuất có `gross_margin`,
    …).

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, float | None],
    }
    year: int | MISSING = MISSING
    quarter: int | None | MISSING = Field(
        MISSING, description='Present only for quarterly period (1–4).'
    )
    """Present only for quarterly period (1–4)."""


class FinancialAnalysisResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[FinancialAnalysisEntry]


class FinancialStatementType(StrEnum):
    """
    Loại báo cáo dùng cho `/market/v2/financial-statement/statement`.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `income-statement` | Báo cáo kết quả kinh doanh |
    | `balance-sheet` | Bảng cân đối kế toán |
    | `cash-flow` | Báo cáo lưu chuyển tiền tệ |

    """

    INCOME_STATEMENT = 'income-statement'
    BALANCE_SHEET = 'balance-sheet'
    CASH_FLOW = 'cash-flow'


class FinancialStatementEntry(BaseModel):
    """
    1 row báo cáo tài chính cho 1 kỳ, trả về từ
    `/market/v2/financial-statement/statement`. `year` luôn có; `quarter`
    chỉ có khi `period=quarterly` (giá trị `1`–`4`).

    Các key còn lại là **metric code động** (tên romanized tiếng Việt, ví
    dụ `luuchuyentienthuantuhoatdongkinhdoanh`, `tienvatuongduongtiendaunam`,
    `loinhuanlotruocthue`, …) nhận giá trị số hoặc `null`. Bộ key phụ thuộc
    vào tham số `type` — income-statement, balance-sheet và cash-flow có bộ
    field khác nhau, mỗi loại mấy chục field. Tham chiếu
    `additionalProperties` trong schema là nguồn chuẩn.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, float | None],
    }
    year: int = Field(..., description='Fiscal year.')
    """Fiscal year."""

    quarter: int | None | MISSING = Field(
        MISSING, description='Quarter (`1`–`4`) for quarterly rows; null for annual.'
    )
    """Quarter (`1`–`4`) for quarterly rows; null for annual."""


class FinancialStatementResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[FinancialStatementEntry]


class ExchangeSession(StrEnum):
    """
    Trạng thái phiên giao dịch hiện tại của 1 sàn.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `OPEN` | ATO — phiên khớp mở cửa |
    | `PROGRESS` | Khớp lệnh liên tục |
    | `BREAK` | Nghỉ giữa trưa |
    | `CLOSED` | Đã đóng cửa |
    | `PRE_CLOSED` | ATC — phiên khớp đóng cửa |
    | `PUT_THROUGH` | Phiên thoả thuận |
    | `POST_SESSION` | Phiên sau giờ khớp lệnh (HNX) |
    | `CA` | Khớp lệnh định kỳ |

    """

    OPEN = 'OPEN'
    PROGRESS = 'PROGRESS'
    BREAK = 'BREAK'
    CLOSED = 'CLOSED'
    PRE_CLOSED = 'PRE_CLOSED'
    PUT_THROUGH = 'PUT_THROUGH'
    POST_SESSION = 'POST_SESSION'
    CA = 'CA'


class ExchangeSessionInfo(BaseModel):
    """
    Thông tin phiên giao dịch hiện tại của 1 sàn.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    exchange: Exchange | MISSING = MISSING
    exchange_session: ExchangeSession | MISSING = MISSING
    available_order_types: list[OrderType] | MISSING = Field(
        MISSING, description='Order types available in the current session.'
    )
    """Order types available in the current session."""


class MarketSessionResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: ExchangeSessionInfo


class BankInterestRate(BaseModel):
    """
    Lãi suất của một kỳ hạn cụ thể.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    effective_date: str | MISSING = Field(
        MISSING, description='Ngày áp dụng, định dạng `D/M/YYYY`.'
    )
    """Ngày áp dụng, định dạng `D/M/YYYY`."""

    percent: str = Field(
        ...,
        description='Lãi suất dạng chuỗi kèm dấu `%`, phần thập phân dùng dấu phẩy (vd `4,4%`).',
    )
    """Lãi suất dạng chuỗi kèm dấu `%`, phần thập phân dùng dấu phẩy (vd `4,4%`)."""

    duration_name: str = Field(..., description='Tên kỳ hạn.')
    """Tên kỳ hạn."""

    bank_icon_url: AnyUrl | None | MISSING = Field(
        MISSING, description='Logo ngân hàng.'
    )
    """Logo ngân hàng."""


class BankInterestRateGroup(BaseModel):
    """
    Lãi suất của một ngân hàng theo từng kỳ hạn.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bank_name: str = Field(..., description='Tên ngân hàng.')
    """Tên ngân hàng."""

    rates: list[BankInterestRate]


class MacroIndicatorCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    indicator: str = Field(
        ...,
        description='Slug định danh của chỉ tiêu — dùng giá trị này để lấy giá trị của chỉ tiêu theo kỳ.',
    )
    """Slug định danh của chỉ tiêu — dùng giá trị này để lấy giá trị của chỉ tiêu theo kỳ."""

    name: str
    tags: list[str]
    unit: str


class MacroIndicatorCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[MacroIndicatorCatalogItem]


class MacroIndicatorObservation(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    period: str = Field(
        ..., description='Kỳ dữ liệu (`yyyy`, `yyyy-Qn` hoặc `yyyy-MM`).'
    )
    """Kỳ dữ liệu (`yyyy`, `yyyy-Qn` hoặc `yyyy-MM`)."""

    value: float | None


class MacroIndicatorSeries(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    indicator: str
    name: str
    unit: str
    series: list[MacroIndicatorObservation]


class MacroIndicatorSeriesResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: MacroIndicatorSeries


class PageMeta(BaseModel):
    """
    Metadata phân trang dùng chung cho mọi list API. Dữ liệu của trang nằm ở `results`.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total: int = Field(..., description='Tổng số bản ghi khớp bộ lọc.')
    """Tổng số bản ghi khớp bộ lọc."""

    current_page: int = Field(..., description='Trang hiện tại.')
    """Trang hiện tại."""

    next_page: int | MISSING = Field(
        MISSING, description='Trang kế tiếp; bằng `current_page` khi đã ở trang cuối.'
    )
    """Trang kế tiếp; bằng `current_page` khi đã ở trang cuối."""

    previous_page: int | MISSING = Field(
        MISSING, description='Trang trước; bằng 1 khi đang ở trang đầu.'
    )
    """Trang trước; bằng 1 khi đang ở trang đầu."""

    page_size: int = Field(..., description='Số bản ghi mỗi trang.')
    """Số bản ghi mỗi trang."""

    page_total: int | MISSING = Field(MISSING, description='Tổng số trang.')
    """Tổng số trang."""


class EconomicEventDetail(BaseModel):
    """
    Phần đặc thù của sự kiện vĩ mô (`type = ECONOMIC`).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: AwareDatetime = Field(
        ...,
        description='Thời điểm diễn ra sự kiện, ISO 8601 kèm offset (giờ Việt Nam).',
    )
    """Thời điểm diễn ra sự kiện, ISO 8601 kèm offset (giờ Việt Nam)."""

    category: str = Field(
        ...,
        description='Phân loại sự kiện (ví dụ "Interest Rate", "Inflation", "Employment").',
    )
    """Phân loại sự kiện (ví dụ "Interest Rate", "Inflation", "Employment")."""

    actual: str | None | MISSING = Field(
        MISSING,
        description='Số liệu thực tế đã công bố. `null` khi sự kiện chưa diễn ra.',
    )
    """Số liệu thực tế đã công bố. `null` khi sự kiện chưa diễn ra."""

    previous: str | None | MISSING = Field(
        MISSING, description='Số liệu kỳ trước. `null` nếu nguồn không có.'
    )
    """Số liệu kỳ trước. `null` nếu nguồn không có."""

    consensus: str | None | MISSING = Field(
        MISSING,
        description='Đồng thuận thị trường (consensus). `null` nếu nguồn không có.',
    )
    """Đồng thuận thị trường (consensus). `null` nếu nguồn không có."""

    forecast: str | None | MISSING = Field(
        MISSING, description='Dự báo nhà phân tích. `null` nếu nguồn không có.'
    )
    """Dự báo nhà phân tích. `null` nếu nguồn không có."""


class Type(StrEnum):
    """
    Loại sự kiện. Hiện chỉ có `ECONOMIC` (công bố số liệu vĩ mô).
    """

    ECONOMIC = 'ECONOMIC'


class CalendarEvent(BaseModel):
    """
    1 sự kiện trên lịch thị trường. Các trường chung nằm ở cấp ngoài, phần đặc thù theo `type` nằm trong `detail` — thêm loại lịch mới không phá contract cũ.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    type: Type = Field(
        ..., description='Loại sự kiện. Hiện chỉ có `ECONOMIC` (công bố số liệu vĩ mô).'
    )
    """Loại sự kiện. Hiện chỉ có `ECONOMIC` (công bố số liệu vĩ mô)."""

    country: EconomicCountry = Field(..., description='Quốc gia của sự kiện.')
    """Quốc gia của sự kiện."""

    title: str = Field(
        ..., description='Tên sự kiện (ví dụ "Fed Interest Rate Decision", "CPI MoM").'
    )
    """Tên sự kiện (ví dụ "Fed Interest Rate Decision", "CPI MoM")."""

    detail: EconomicEventDetail = Field(
        ..., description='Chi tiết theo `type`; với `ECONOMIC` là số liệu công bố.'
    )
    """Chi tiết theo `type`; với `ECONOMIC` là số liệu công bố."""


class CalendarEventsPage(PageMeta):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    results: list[CalendarEvent] = Field(
        ..., description='Sự kiện của trang hiện tại, sort `detail.date` tăng dần.'
    )
    """Sự kiện của trang hiện tại, sort `detail.date` tăng dần."""


class CalendarEventsPageResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: CalendarEventsPage


class MarketNewsTopic(StrEnum):
    """
    Chủ đề tin tức thị trường.
    """

    CRYPTO = 'crypto'
    FOREX = 'forex'
    STOCK = 'stock'
    COMMODITIES = 'commodities'
    MACRO = 'macro'


class MarketNewsItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: str
    title: str
    url: AnyUrl
    summary: str | None | MISSING = Field(
        MISSING, description='Tóm tắt ngắn nội dung bài viết.'
    )
    """Tóm tắt ngắn nội dung bài viết."""

    source: str | None | MISSING = Field(
        MISSING, description='Nguồn tin (hãng tin / trang đăng).'
    )
    """Nguồn tin (hãng tin / trang đăng)."""

    published_at: AwareDatetime
    topic: MarketNewsTopic
    symbols: list[str] | None | MISSING = MISSING


class MarketNewsPage(PageMeta):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    results: list[MarketNewsItem] = Field(
        ..., description='Tin tức của trang hiện tại, mới nhất trước.'
    )
    """Tin tức của trang hiện tại, mới nhất trước."""


class MarketNewsPageResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: MarketNewsPage


class MarketNewsDetail(MarketNewsItem):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    content: str | None | MISSING = Field(MISSING, description='Toàn văn bài viết.')
    """Toàn văn bài viết."""


class MarketNewsDetailResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: MarketNewsDetail


class QuoteStockCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""


class QuoteStocksCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteStockCatalogItem]


class QuoteStock(BaseModel):
    """
    Quote cổ phiếu realtime.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    exchange: str | MISSING = Field(MISSING, description='Sàn niêm yết.')
    """Sàn niêm yết."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    price: float = Field(..., description='Giá hiện tại.')
    """Giá hiện tại."""

    open: float | MISSING = Field(MISSING, description='Giá mở cửa.')
    """Giá mở cửa."""

    high: float | MISSING = Field(MISSING, description='Giá cao nhất.')
    """Giá cao nhất."""

    low: float | MISSING = Field(MISSING, description='Giá thấp nhất.')
    """Giá thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Giá tham chiếu.')
    """Giá tham chiếu."""

    ceiling: float | MISSING = Field(
        MISSING,
        description='Giá trần trong ngày. `null` với cổ phiếu Mỹ (không có biên độ).',
    )
    """Giá trần trong ngày. `null` với cổ phiếu Mỹ (không có biên độ)."""

    floor: float | MISSING = Field(
        MISSING,
        description='Giá sàn trong ngày. `null` với cổ phiếu Mỹ (không có biên độ).',
    )
    """Giá sàn trong ngày. `null` với cổ phiếu Mỹ (không có biên độ)."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng khớp.')
    """Khối lượng khớp."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteStockResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteStock


class QuoteOrderBookLevel(BaseModel):
    """
    1 mức giá trong sổ lệnh.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: float = Field(..., description='Giá đặt.')
    """Giá đặt."""

    volume: float = Field(..., description='Khối lượng tại mức giá.')
    """Khối lượng tại mức giá."""


class QuoteOrderBook(BaseModel):
    """
    Độ sâu bid/ask.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    bids: list[QuoteOrderBookLevel]
    asks: list[QuoteOrderBookLevel]
    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteOrderBookResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteOrderBook


class QuoteOhlcvBar(BaseModel):
    """
    1 cây nến OHLCV. Với trái phiếu Chính phủ, nến chỉ có `{t, yield}` — `c` là `null`.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    t: int = Field(..., description='Unix timestamp (giây) mốc bắt đầu nến.')
    """Unix timestamp (giây) mốc bắt đầu nến."""

    o: float | None | MISSING = Field(
        MISSING, description='Giá mở cửa. `null` với chuỗi close-only.'
    )
    """Giá mở cửa. `null` với chuỗi close-only."""

    h: float | None | MISSING = Field(
        MISSING, description='Giá cao nhất. `null` với chuỗi close-only.'
    )
    """Giá cao nhất. `null` với chuỗi close-only."""

    l: float | None | MISSING = Field(
        MISSING, description='Giá thấp nhất. `null` với chuỗi close-only.'
    )
    """Giá thấp nhất. `null` với chuỗi close-only."""

    c: float | None | MISSING = Field(
        MISSING,
        description='Giá đóng cửa. `null` với nến yield-only (trái phiếu Chính phủ).',
    )
    """Giá đóng cửa. `null` với nến yield-only (trái phiếu Chính phủ)."""

    v: float | None | MISSING = Field(
        MISSING, description='Khối lượng. `null` với chuỗi close-only.'
    )
    """Khối lượng. `null` với chuỗi close-only."""

    yield_: float | None | MISSING = Field(
        MISSING,
        alias='yield',
        description='Lợi suất (%). Chỉ xuất hiện với lịch sử trái phiếu Chính phủ; các nến khác không có trường này.',
    )
    """Lợi suất (%). Chỉ xuất hiện với lịch sử trái phiếu Chính phủ; các nến khác không có trường này."""


class QuoteOhlcvSeries(BaseModel):
    """
    Chuỗi giá OHLCV theo thời gian.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    currency: str | MISSING = Field(
        MISSING, description='Đơn vị tiền tệ (bỏ qua với chỉ số).'
    )
    """Đơn vị tiền tệ (bỏ qua với chỉ số)."""

    resolution: str | MISSING = Field(MISSING, description='Độ phân giải nến.')
    """Độ phân giải nến."""

    series: list[QuoteOhlcvBar]


class QuoteOhlcvHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteOhlcvSeries


class QuoteIndexCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã chỉ số.')
    """Mã chỉ số."""

    name: str | MISSING = Field(MISSING, description='Tên chỉ số.')
    """Tên chỉ số."""


class QuoteIndicesCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteIndexCatalogItem]


class QuoteIndex(BaseModel):
    """
    Quote chỉ số realtime (dùng `value` thay `price`).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã chỉ số.')
    """Mã chỉ số."""

    name: str | MISSING = Field(MISSING, description='Tên chỉ số.')
    """Tên chỉ số."""

    value: float = Field(..., description='Giá trị chỉ số.')
    """Giá trị chỉ số."""

    open: float | MISSING = Field(MISSING, description='Mở cửa.')
    """Mở cửa."""

    high: float | MISSING = Field(MISSING, description='Cao nhất.')
    """Cao nhất."""

    low: float | MISSING = Field(MISSING, description='Thấp nhất.')
    """Thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Tham chiếu.')
    """Tham chiếu."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng toàn thị trường.')
    """Khối lượng toàn thị trường."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteIndexResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteIndex


class ResolutionDaily(StrEnum):
    """
    Độ phân giải nến — các endpoint này **chỉ hỗ trợ `1D`**; truyền giá trị khác trả `400 INVALID_PARAMETER`.
    """

    FIELD_1_D = '1D'


class QuoteForexCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Cặp forex 6 ký tự.')
    """Cặp forex 6 ký tự."""

    name: str | MISSING = Field(MISSING, description='Tên cặp.')
    """Tên cặp."""


class QuoteForexCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteForexCatalogItem]


class QuoteForexSide(BaseModel):
    """
    Cặp bid/ask.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    bid: float | None | MISSING = Field(MISSING, description='Giá mua vào.')
    """Giá mua vào."""

    ask: float | None | MISSING = Field(MISSING, description='Giá bán ra.')
    """Giá bán ra."""


class QuoteForex(BaseModel):
    """
    Quote forex — bid/ask. Chỉ USDVND có spread thực; các cặp khác bid=ask.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Cặp forex.')
    """Cặp forex."""

    name: str | MISSING = Field(MISSING, description='Tên cặp.')
    """Tên cặp."""

    bid: float = Field(..., description='Giá mua vào.')
    """Giá mua vào."""

    ask: float = Field(..., description='Giá bán ra.')
    """Giá bán ra."""

    open: QuoteForexSide | MISSING = MISSING
    high: QuoteForexSide | MISSING = MISSING
    low: QuoteForexSide | MISSING = MISSING
    reference: QuoteForexSide | MISSING = MISSING
    change: QuoteForexSide | MISSING = MISSING
    change_percent: QuoteForexSide | MISSING = MISSING
    volume: float | None | MISSING = Field(
        MISSING, description='Luôn `null` với forex.'
    )
    """Luôn `null` với forex."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteForexResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteForex


class QuoteCryptoCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã crypto.')
    """Mã crypto."""

    name: str | MISSING = Field(MISSING, description='Tên crypto.')
    """Tên crypto."""


class QuoteCryptosCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteCryptoCatalogItem]


class QuoteCrypto(BaseModel):
    """
    Quote crypto realtime.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã crypto.')
    """Mã crypto."""

    name: str | MISSING = Field(MISSING, description='Tên crypto.')
    """Tên crypto."""

    currency: str | MISSING = Field(MISSING, description='Tiền tệ.')
    """Tiền tệ."""

    price: float = Field(..., description='Giá hiện tại.')
    """Giá hiện tại."""

    open: float | MISSING = Field(MISSING, description='Mở cửa (00:00 UTC).')
    """Mở cửa (00:00 UTC)."""

    high: float | MISSING = Field(MISSING, description='Cao nhất.')
    """Cao nhất."""

    low: float | MISSING = Field(MISSING, description='Thấp nhất.')
    """Thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Tham chiếu (phiên trước).')
    """Tham chiếu (phiên trước)."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng 24h.')
    """Khối lượng 24h."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteCryptoResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteCrypto


class QuoteCommodityCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã hàng hoá ISO.')
    """Mã hàng hoá ISO."""

    name: str | MISSING = Field(MISSING, description='Tên hàng hoá.')
    """Tên hàng hoá."""

    unit: str | MISSING = Field(MISSING, description='Đơn vị định giá.')
    """Đơn vị định giá."""


class QuoteCommoditiesCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteCommodityCatalogItem]


class QuoteCommodity(BaseModel):
    """
    Quote hàng hoá realtime (giá quốc tế).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã hàng hoá ISO.')
    """Mã hàng hoá ISO."""

    name: str | MISSING = Field(MISSING, description='Tên hàng hoá.')
    """Tên hàng hoá."""

    currency: str | MISSING = Field(MISSING, description='Tiền tệ.')
    """Tiền tệ."""

    price: float = Field(..., description='Giá hiện tại.')
    """Giá hiện tại."""

    open: float | MISSING = Field(MISSING, description='Mở cửa.')
    """Mở cửa."""

    high: float | MISSING = Field(MISSING, description='Cao nhất.')
    """Cao nhất."""

    low: float | MISSING = Field(MISSING, description='Thấp nhất.')
    """Thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Tham chiếu.')
    """Tham chiếu."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng.')
    """Khối lượng."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteCommodityResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteCommodity


class QuoteFundCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã CCQ quỹ mở.')
    """Mã CCQ quỹ mở."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    fund_company: str | MISSING = Field(MISSING, description='Công ty quản lý quỹ.')
    """Công ty quản lý quỹ."""

    type: str | MISSING = Field(MISSING, description='Loại quỹ.')
    """Loại quỹ."""

    valuation_frequency: str | MISSING = Field(
        MISSING, description='Tần suất định giá.'
    )
    """Tần suất định giá."""


class QuoteFundsCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteFundCatalogItem]


class QuoteFund(BaseModel):
    """
    NAV mới nhất của quỹ mở. Không có open/high/low/volume.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã CCQ.')
    """Mã CCQ."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    nav: float = Field(..., description='NAV/CCQ (giá tài sản).')
    """NAV/CCQ (giá tài sản)."""

    reference: float | MISSING = Field(MISSING, description='NAV kỳ định giá trước.')
    """NAV kỳ định giá trước."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    total_nav: float | MISSING = Field(
        MISSING, description='Tổng tài sản ròng của quỹ (tuỳ chọn).'
    )
    """Tổng tài sản ròng của quỹ (tuỳ chọn)."""

    nav_date: date_aliased = Field(
        ..., description='Ngày định giá T (đọc NAV theo mốc này).'
    )
    """Ngày định giá T (đọc NAV theo mốc này)."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm công bố (thường T+1).'
    )
    """Thời điểm công bố (thường T+1)."""


class QuoteFundResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteFund


class QuoteNavPoint(BaseModel):
    """
    1 điểm NAV.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    t: int = Field(..., description='Unix timestamp (giây) ngày định giá.')
    """Unix timestamp (giây) ngày định giá."""

    nav: float = Field(..., description='NAV tại kỳ định giá.')
    """NAV tại kỳ định giá."""


class QuoteNavSeries(BaseModel):
    """
    Chuỗi NAV theo kỳ định giá.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    series: list[QuoteNavPoint]


class QuoteNavHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteNavSeries


class QuoteBondCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã trái phiếu HNX.')
    """Mã trái phiếu HNX."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    issuer: str | MISSING = Field(MISSING, description='Tổ chức phát hành.')
    """Tổ chức phát hành."""

    type: str | MISSING = Field(
        MISSING, description='Loại trái phiếu (`corporate`/`government`).'
    )
    """Loại trái phiếu (`corporate`/`government`)."""

    face_value: float | MISSING = Field(MISSING, description='Mệnh giá.')
    """Mệnh giá."""

    coupon_rate: float | MISSING = Field(MISSING, description='Lãi suất coupon (%).')
    """Lãi suất coupon (%)."""

    coupon_frequency: int | MISSING = Field(
        MISSING, description='Số kỳ trả coupon mỗi năm.'
    )
    """Số kỳ trả coupon mỗi năm."""

    issue_date: date_aliased | MISSING = Field(MISSING, description='Ngày phát hành.')
    """Ngày phát hành."""

    maturity_date: date_aliased | MISSING = Field(MISSING, description='Ngày đáo hạn.')
    """Ngày đáo hạn."""


class QuoteBondsCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteBondCatalogItem]


class QuoteBond(BaseModel):
    """
    Quote trái phiếu realtime.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã trái phiếu.')
    """Mã trái phiếu."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    exchange: str | MISSING = Field(MISSING, description='Sàn.')
    """Sàn."""

    currency: str | None | MISSING = Field(
        MISSING,
        description='Đơn vị tiền tệ. `null` với trái phiếu Chính phủ (yield-only).',
    )
    """Đơn vị tiền tệ. `null` với trái phiếu Chính phủ (yield-only)."""

    price: float | None = Field(
        ...,
        description='Giá khớp/trái phiếu (VND, không phải %). `null` với trái phiếu Chính phủ.',
    )
    """Giá khớp/trái phiếu (VND, không phải %). `null` với trái phiếu Chính phủ."""

    open: float | MISSING = Field(MISSING, description='Mở cửa.')
    """Mở cửa."""

    high: float | MISSING = Field(MISSING, description='Cao nhất.')
    """Cao nhất."""

    low: float | MISSING = Field(MISSING, description='Thấp nhất.')
    """Thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Tham chiếu.')
    """Tham chiếu."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    yield_: float | None | MISSING = Field(
        MISSING,
        alias='yield',
        description='Lợi suất (%). `null` với trái phiếu doanh nghiệp chưa tính được; với trái phiếu Chính phủ là lợi suất 10 năm.',
    )
    """Lợi suất (%). `null` với trái phiếu doanh nghiệp chưa tính được; với trái phiếu Chính phủ là lợi suất 10 năm."""

    volume: float | MISSING = Field(MISSING, description='Số trái phiếu khớp.')
    """Số trái phiếu khớp."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteBondResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteBond


class QuoteEtfCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã ETF niêm yết.')
    """Mã ETF niêm yết."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    fund_company: str | MISSING = Field(MISSING, description='Công ty quản lý quỹ.')
    """Công ty quản lý quỹ."""

    underlying_index: str | MISSING = Field(MISSING, description='Chỉ số tham chiếu.')
    """Chỉ số tham chiếu."""


class QuoteEtfsCatalogResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteEtfCatalogItem]


class QuoteEtf(BaseModel):
    """
    Quote ETF realtime (shape như cổ phiếu).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã ETF.')
    """Mã ETF."""

    name: str | MISSING = Field(MISSING, description='Tên hiển thị.')
    """Tên hiển thị."""

    exchange: str | MISSING = Field(MISSING, description='Sàn.')
    """Sàn."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    price: float = Field(..., description='Giá hiện tại.')
    """Giá hiện tại."""

    open: float | MISSING = Field(MISSING, description='Mở cửa.')
    """Mở cửa."""

    high: float | MISSING = Field(MISSING, description='Cao nhất.')
    """Cao nhất."""

    low: float | MISSING = Field(MISSING, description='Thấp nhất.')
    """Thấp nhất."""

    reference: float | MISSING = Field(MISSING, description='Tham chiếu.')
    """Tham chiếu."""

    ceiling: float | MISSING = Field(MISSING, description='Giá trần trong ngày.')
    """Giá trần trong ngày."""

    floor: float | MISSING = Field(MISSING, description='Giá sàn trong ngày.')
    """Giá sàn trong ngày."""

    change: float | MISSING = Field(MISSING, description='Thay đổi tuyệt đối.')
    """Thay đổi tuyệt đối."""

    change_percent: float | MISSING = Field(MISSING, description='Thay đổi %.')
    """Thay đổi %."""

    volume: float | MISSING = Field(MISSING, description='Khối lượng khớp.')
    """Khối lượng khớp."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteEtfResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteEtf


class QuoteDealerProductCatalogItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    code: str = Field(..., description='Mã sản phẩm dealer.')
    """Mã sản phẩm dealer."""

    name: str | MISSING = Field(MISSING, description='Tên sản phẩm.')
    """Tên sản phẩm."""

    dealer: str | MISSING = Field(MISSING, description='Nhà cung cấp.')
    """Nhà cung cấp."""


class QuoteDealerProductsResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[QuoteDealerProductCatalogItem]


class QuoteDealerProduct(BaseModel):
    """
    Báo giá 1 sản phẩm dealer nội địa.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã hàng hoá gốc.')
    """Mã hàng hoá gốc."""

    code: str = Field(..., description='Mã sản phẩm dealer.')
    """Mã sản phẩm dealer."""

    name: str | MISSING = Field(MISSING, description='Tên sản phẩm.')
    """Tên sản phẩm."""

    dealer: str | MISSING = Field(MISSING, description='Nhà cung cấp.')
    """Nhà cung cấp."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    buy: float | MISSING = Field(MISSING, description='Giá mua vào.')
    """Giá mua vào."""

    sell: float | MISSING = Field(MISSING, description='Giá bán ra.')
    """Giá bán ra."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class QuoteDealerProductResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteDealerProduct


class QuoteDealerPricePoint(BaseModel):
    """
    1 điểm giá dealer.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    t: int = Field(..., description='Unix timestamp (giây).')
    """Unix timestamp (giây)."""

    price: float = Field(..., description='Giá dealer.')
    """Giá dealer."""


class QuoteDealerPriceSeries(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã định danh (canonical, viết hoa).')
    """Mã định danh (canonical, viết hoa)."""

    code: str | MISSING = Field(MISSING, description='Mã sản phẩm dealer.')
    """Mã sản phẩm dealer."""

    currency: str | MISSING = Field(MISSING, description='Đơn vị tiền tệ.')
    """Đơn vị tiền tệ."""

    series: list[QuoteDealerPricePoint]


class QuoteDealerProductHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: QuoteDealerPriceSeries


class StockSector(BaseModel):
    """
    Ngành của mã (cấp 1).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    slug: str | MISSING = Field(MISSING, description='Slug ngành.')
    """Slug ngành."""

    name: str | MISSING = Field(MISSING, description='Tên ngành.')
    """Tên ngành."""


class StockScreenerItem(BaseModel):
    """
    Một dòng kết quả screener. Chỉ chứa các field được chọn qua `fields` (mặc định `symbol`, `exchange`, `name`, `price`, `change_percent`), cộng thêm field dùng trong `sort`/filter.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    name: str | MISSING = Field(MISSING, description='Tên doanh nghiệp.')
    """Tên doanh nghiệp."""

    exchange: str | MISSING = Field(MISSING, description='Sàn niêm yết.')
    """Sàn niêm yết."""

    sector: StockSector | None | MISSING = MISSING
    price: float | None | MISSING = Field(MISSING, description='Giá hiện tại (VND).')
    """Giá hiện tại (VND)."""

    change_percent: float | None | MISSING = Field(
        MISSING, description='Thay đổi giá so với tham chiếu (%).'
    )
    """Thay đổi giá so với tham chiếu (%)."""

    market_cap: float | None | MISSING = Field(MISSING, description='Vốn hoá (VND).')
    """Vốn hoá (VND)."""

    shares_outstanding: float | None | MISSING = Field(
        MISSING, description='Số cổ phiếu lưu hành.'
    )
    """Số cổ phiếu lưu hành."""

    pe: float | None | MISSING = Field(MISSING, description='P/E.')
    """P/E."""

    pb: float | None | MISSING = Field(MISSING, description='P/B.')
    """P/B."""

    eps: float | None | MISSING = Field(MISSING, description='EPS (VND).')
    """EPS (VND)."""

    volume: float | None | MISSING = Field(
        MISSING, description='Khối lượng khớp trong `window`.'
    )
    """Khối lượng khớp trong `window`."""

    value: float | None | MISSING = Field(
        MISSING, description='Giá trị khớp trong `window` (VND).'
    )
    """Giá trị khớp trong `window` (VND)."""

    foreign_buy_value: float | None | MISSING = Field(
        MISSING, description='Giá trị khối ngoại mua trong `window` (VND).'
    )
    """Giá trị khối ngoại mua trong `window` (VND)."""

    foreign_sell_value: float | None | MISSING = Field(
        MISSING, description='Giá trị khối ngoại bán trong `window` (VND).'
    )
    """Giá trị khối ngoại bán trong `window` (VND)."""

    foreign_net_value: float | None | MISSING = Field(
        MISSING, description='Giá trị khối ngoại mua ròng trong `window` (VND).'
    )
    """Giá trị khối ngoại mua ròng trong `window` (VND)."""

    foreign_net_volume: float | None | MISSING = Field(
        MISSING, description='Khối lượng khối ngoại mua ròng trong `window`.'
    )
    """Khối lượng khối ngoại mua ròng trong `window`."""

    foreign_room_available: float | None | MISSING = Field(
        MISSING, description='Room ngoại còn lại (số cổ phiếu).'
    )
    """Room ngoại còn lại (số cổ phiếu)."""

    foreign_room_available_pct: float | None | MISSING = Field(
        MISSING,
        description='Room ngoại còn lại tính theo % trần sở hữu nước ngoài (0–100). Càng gần 0 là càng kín room.',
    )
    """Room ngoại còn lại tính theo % trần sở hữu nước ngoài (0–100). Càng gần 0 là càng kín room."""

    proprietary_buy_value: float | None | MISSING = Field(
        MISSING, description='Giá trị tự doanh mua trong `window` (VND).'
    )
    """Giá trị tự doanh mua trong `window` (VND)."""

    proprietary_sell_value: float | None | MISSING = Field(
        MISSING, description='Giá trị tự doanh bán trong `window` (VND).'
    )
    """Giá trị tự doanh bán trong `window` (VND)."""

    proprietary_net_value: float | None | MISSING = Field(
        MISSING, description='Giá trị tự doanh mua ròng trong `window` (VND).'
    )
    """Giá trị tự doanh mua ròng trong `window` (VND)."""

    proprietary_net_volume: float | None | MISSING = Field(
        MISSING, description='Khối lượng tự doanh mua ròng trong `window`.'
    )
    """Khối lượng tự doanh mua ròng trong `window`."""

    ma50: float | None | MISSING = Field(
        MISSING,
        description='Trung bình động 50 phiên (VND), cùng thang với `price`. `null` khi mã chưa đủ lịch sử.',
    )
    """Trung bình động 50 phiên (VND), cùng thang với `price`. `null` khi mã chưa đủ lịch sử."""

    ma200: float | None | MISSING = Field(
        MISSING,
        description='Trung bình động 200 phiên (VND), cùng thang với `price`. `null` khi mã chưa đủ lịch sử.',
    )
    """Trung bình động 200 phiên (VND), cùng thang với `price`. `null` khi mã chưa đủ lịch sử."""


class StockScreenerResult(BaseModel):
    """
    Kết quả sàng lọc cổ phiếu, đã phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    window: str | None | MISSING = Field(
        MISSING, description='Cửa sổ luỹ kế đã áp dụng. `null` khi quét theo `date`.'
    )
    """Cửa sổ luỹ kế đã áp dụng. `null` khi quét theo `date`."""

    date: date_aliased | None | MISSING = Field(
        MISSING,
        description='Phiên quá khứ đã quét (`YYYY-MM-DD`). `null` khi quét theo `window`.',
    )
    """Phiên quá khứ đã quét (`YYYY-MM-DD`). `null` khi quét theo `window`."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""

    page: int | MISSING = Field(MISSING, description='Trang hiện tại.')
    """Trang hiện tại."""

    page_size: int | MISSING = Field(MISSING, description='Số mã mỗi trang.')
    """Số mã mỗi trang."""

    total: int | MISSING = Field(MISSING, description='Tổng số mã khớp bộ lọc.')
    """Tổng số mã khớp bộ lọc."""

    items: list[StockScreenerItem] = Field(..., description='Danh sách mã.')
    """Danh sách mã."""


class StockScreenerResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockScreenerResult


class CompanyProfileSectorNode(BaseModel):
    """
    Một cấp trong cây ngành của doanh nghiệp.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    slug: str | MISSING = Field(MISSING, description='Slug ngành.')
    """Slug ngành."""

    name: str | MISSING = Field(MISSING, description='Tên ngành.')
    """Tên ngành."""

    level: int | MISSING = Field(MISSING, description='Cấp ngành (1 là cấp cao nhất).')
    """Cấp ngành (1 là cấp cao nhất)."""


class CompanyProfile(BaseModel):
    """
    Hồ sơ doanh nghiệp.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    name_vn: str | MISSING = Field(MISSING, description='Tên tiếng Việt.')
    """Tên tiếng Việt."""

    name_en: str | None | MISSING = Field(MISSING, description='Tên tiếng Anh.')
    """Tên tiếng Anh."""

    sector: list[CompanyProfileSectorNode] | MISSING = Field(
        MISSING, description='Cây ngành từ cấp cao xuống cấp thấp.'
    )
    """Cây ngành từ cấp cao xuống cấp thấp."""

    about: str | None | MISSING = Field(
        MISSING, description='Mô tả hoạt động kinh doanh.'
    )
    """Mô tả hoạt động kinh doanh."""


class CompanyProfileResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: CompanyProfile


class StockListing(BaseModel):
    """
    Thông tin niêm yết của một mã.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    exchange: str | MISSING = Field(MISSING, description='Sàn niêm yết.')
    """Sàn niêm yết."""

    listing_date: date_aliased | None | MISSING = Field(
        MISSING, description='Ngày niêm yết (`YYYY-MM-DD`).'
    )
    """Ngày niêm yết (`YYYY-MM-DD`)."""

    listing_reference_price: float | None | MISSING = Field(
        MISSING, description='Giá tham chiếu ngày niêm yết (VND).'
    )
    """Giá tham chiếu ngày niêm yết (VND)."""

    listed_shares: float | None | MISSING = Field(
        MISSING, description='Khối lượng cổ phiếu niêm yết.'
    )
    """Khối lượng cổ phiếu niêm yết."""

    outstanding_shares: float | None | MISSING = Field(
        MISSING, description='Khối lượng cổ phiếu lưu hành.'
    )
    """Khối lượng cổ phiếu lưu hành."""

    treasury_shares: float | None | MISSING = Field(
        MISSING, description='Khối lượng cổ phiếu quỹ.'
    )
    """Khối lượng cổ phiếu quỹ."""

    free_float: float | None | MISSING = Field(
        MISSING, description='Khối lượng cổ phiếu tự do chuyển nhượng.'
    )
    """Khối lượng cổ phiếu tự do chuyển nhượng."""

    free_float_pct: float | None | MISSING = Field(
        MISSING, description='Tỷ lệ free-float (%).'
    )
    """Tỷ lệ free-float (%)."""


class StockListingResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockListing


class OwnershipStake(BaseModel):
    """
    Tỷ lệ nắm giữ của một nhóm sở hữu.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    volume: float | None | MISSING = Field(
        MISSING, description='Khối lượng cổ phiếu nắm giữ.'
    )
    """Khối lượng cổ phiếu nắm giữ."""

    pct: float | None | MISSING = Field(MISSING, description='Tỷ lệ nắm giữ (%).')
    """Tỷ lệ nắm giữ (%)."""


class MajorShareholder(BaseModel):
    """
    Một cổ đông lớn.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    name: str | MISSING = Field(MISSING, description='Tên cổ đông.')
    """Tên cổ đông."""

    type: str | MISSING = Field(
        MISSING, description='Loại cổ đông (tổ chức / cá nhân / nhà nước…).'
    )
    """Loại cổ đông (tổ chức / cá nhân / nhà nước…)."""

    volume: float | None | MISSING = Field(MISSING, description='Khối lượng nắm giữ.')
    """Khối lượng nắm giữ."""

    pct: float | None | MISSING = Field(MISSING, description='Tỷ lệ nắm giữ (%).')
    """Tỷ lệ nắm giữ (%)."""

    updated_at: str | None | MISSING = Field(
        MISSING, description='Thời điểm cập nhật tỷ lệ.'
    )
    """Thời điểm cập nhật tỷ lệ."""


class ForeignRoomSummary(BaseModel):
    """
    Tóm tắt room ngoại trong cơ cấu sở hữu.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    max_pct: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (%).'
    )
    """Trần sở hữu nước ngoài (%)."""

    max_volume: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (số cổ phiếu).'
    )
    """Trần sở hữu nước ngoài (số cổ phiếu)."""

    available: float | None | MISSING = Field(
        MISSING, description='Room ngoại còn lại (số cổ phiếu).'
    )
    """Room ngoại còn lại (số cổ phiếu)."""


class Structure(BaseModel):
    """
    Tỷ lệ sở hữu theo nhóm.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    state: OwnershipStake | MISSING = MISSING
    foreign: OwnershipStake | MISSING = MISSING
    other: OwnershipStake | MISSING = MISSING


class StockOwnership(BaseModel):
    """
    Cơ cấu sở hữu hiện tại của một mã.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    structure: Structure | MISSING = Field(
        MISSING, description='Tỷ lệ sở hữu theo nhóm.'
    )
    """Tỷ lệ sở hữu theo nhóm."""

    major_shareholders: list[MajorShareholder] | MISSING = Field(
        MISSING, description='Danh sách cổ đông lớn.'
    )
    """Danh sách cổ đông lớn."""

    foreign_room: ForeignRoomSummary | MISSING = MISSING


class StockOwnershipResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockOwnership


class ForeignRoom(BaseModel):
    """
    Room ngoại của một mã tại một phiên. `owned + available = max_volume`.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    max_pct: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (%).'
    )
    """Trần sở hữu nước ngoài (%)."""

    max_volume: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (số cổ phiếu).'
    )
    """Trần sở hữu nước ngoài (số cổ phiếu)."""

    owned: float | None | MISSING = Field(
        MISSING, description='Khối lượng khối ngoại đang nắm.'
    )
    """Khối lượng khối ngoại đang nắm."""

    available: float | None | MISSING = Field(
        MISSING, description='Room ngoại còn lại (số cổ phiếu).'
    )
    """Room ngoại còn lại (số cổ phiếu)."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class ForeignRoomResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: ForeignRoom


class ForeignRoomBar(BaseModel):
    """
    Room ngoại của một phiên trong chuỗi lịch sử. Mỗi bar mang theo trần sở hữu tại phiên đó vì `max_volume` đổi khi doanh nghiệp phát hành thêm.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    max_pct: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (%).'
    )
    """Trần sở hữu nước ngoài (%)."""

    max_volume: float | None | MISSING = Field(
        MISSING, description='Trần sở hữu nước ngoài (số cổ phiếu).'
    )
    """Trần sở hữu nước ngoài (số cổ phiếu)."""

    owned: float | None | MISSING = Field(
        MISSING, description='Khối lượng khối ngoại đang nắm.'
    )
    """Khối lượng khối ngoại đang nắm."""

    available: float | None | MISSING = Field(
        MISSING, description='Room ngoại còn lại (số cổ phiếu).'
    )
    """Room ngoại còn lại (số cổ phiếu)."""


class ForeignRoomHistory(BaseModel):
    """
    Chuỗi room ngoại theo phiên, đã phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    resolution: str | MISSING = Field(MISSING, description='Độ phân giải của bar.')
    """Độ phân giải của bar."""

    from_: date_aliased | MISSING = Field(
        MISSING, alias='from', description='Ngày bắt đầu khoảng đã áp dụng.'
    )
    """Ngày bắt đầu khoảng đã áp dụng."""

    to: date_aliased | MISSING = Field(
        MISSING, description='Ngày kết thúc khoảng đã áp dụng.'
    )
    """Ngày kết thúc khoảng đã áp dụng."""

    page: int | MISSING = Field(MISSING, description='Trang hiện tại.')
    """Trang hiện tại."""

    page_size: int | MISSING = Field(MISSING, description='Số phiên mỗi trang.')
    """Số phiên mỗi trang."""

    total: int | MISSING = Field(MISSING, description='Tổng số phiên trong khoảng.')
    """Tổng số phiên trong khoảng."""

    items: list[ForeignRoomBar] = Field(..., description='Chuỗi bar theo phiên.')
    """Chuỗi bar theo phiên."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm dữ liệu (ISO 8601 kèm offset)."""


class ForeignRoomHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: ForeignRoomHistory


class StockTechnicalPrice(BaseModel):
    """
    Giá đóng cửa của một phiên trong cửa sổ, để đối chiếu với chỉ báo.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    close: float = Field(..., description='Giá đóng cửa (nghìn đồng).')
    """Giá đóng cửa (nghìn đồng)."""


class StockTechnicalPoint(BaseModel):
    """
    Một phiên trong chuỗi của một chỉ báo: `date` cộng các thành phần mà chính chỉ báo đó sinh ra.

    Tên thành phần theo từng chỉ báo — chỉ báo một đường (SMA, EMA, RSI, ATR, CCI, WILLIAMS_R, OBV, MFI, VOLUME_SMA) trả `value`; `MACD` trả `macd_line`/`signal_line`/`histogram`; `BBANDS` trả `upper`/`middle`/`lower`; `STOCH` trả `k`/`d`; `ADX` trả `value`/`plus_di`/`minus_di`; `SUPERTREND` và `PSAR` trả `value` kèm `direction` (`UP`/`DOWN`); `ICHIMOKU` trả `tenkan`/`kijun`/`senkou_a`/`senkou_b`/`chikou`.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, float | str],
    }
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""


class StockTechnicalSeries(BaseModel):
    """
    Chuỗi của một chỉ báo đã yêu cầu.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    indicator: str = Field(..., description='Tên chỉ báo.')
    """Tên chỉ báo."""

    params: str = Field(
        ..., description='Tham số đã áp dụng, ngăn bởi dấu phẩy (rỗng với `OBV`).'
    )
    """Tham số đã áp dụng, ngăn bởi dấu phẩy (rỗng với `OBV`)."""

    display_name: str = Field(..., description='Ký pháp đầy đủ để hiển thị.')
    """Ký pháp đầy đủ để hiển thị."""

    data: list[StockTechnicalPoint] = Field(
        ...,
        description='Chuỗi theo phiên; đúng 1 phần tử ở chế độ phiên gần nhất. Rỗng khi không tính được — khi đó xem `note`, các chỉ báo khác vẫn trả bình thường.',
    )
    """Chuỗi theo phiên; đúng 1 phần tử ở chế độ phiên gần nhất. Rỗng khi không tính được — khi đó xem `note`, các chỉ báo khác vẫn trả bình thường."""

    note: str | MISSING = Field(
        MISSING,
        description='Lý do `data` rỗng (vd `SUPERTREND`/`PSAR` cần tối thiểu 200 phiên). Chỉ xuất hiện khi có.',
    )
    """Lý do `data` rỗng (vd `SUPERTREND`/`PSAR` cần tối thiểu 200 phiên). Chỉ xuất hiện khi có."""


class StockTechnicals(BaseModel):
    """
    Chỉ báo kỹ thuật của một mã trên cửa sổ đã tính.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    resolution: str = Field(..., description='Khung thời gian của bar; luôn là `1D`.')
    """Khung thời gian của bar; luôn là `1D`."""

    from_: date_aliased = Field(
        ...,
        alias='from',
        description='Phiên đầu tiên thực sự được tính — đã lùi khỏi ngày nghỉ, không phải ngày client gửi lên.',
    )
    """Phiên đầu tiên thực sự được tính — đã lùi khỏi ngày nghỉ, không phải ngày client gửi lên."""

    to: date_aliased = Field(
        ...,
        description='Phiên cuối cùng được tính. Bằng `from` ở chế độ phiên gần nhất.',
    )
    """Phiên cuối cùng được tính. Bằng `from` ở chế độ phiên gần nhất."""

    prices: list[StockTechnicalPrice] = Field(
        ...,
        description='Giá đóng cửa của cửa sổ, liệt kê một lần ở cấp trên thay vì lặp trong từng chỉ báo. Align với chuỗi chỉ báo theo `date`.',
    )
    """Giá đóng cửa của cửa sổ, liệt kê một lần ở cấp trên thay vì lặp trong từng chỉ báo. Align với chuỗi chỉ báo theo `date`."""

    indicators: list[StockTechnicalSeries] = Field(
        ..., description='Mỗi chỉ báo đã yêu cầu một phần tử, theo đúng thứ tự yêu cầu.'
    )
    """Mỗi chỉ báo đã yêu cầu một phần tử, theo đúng thứ tự yêu cầu."""


class StockTechnicalsResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockTechnicals


class TradedAmount(BaseModel):
    """
    Cặp khối lượng / giá trị của một dòng giao dịch.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    volume: float = Field(..., description='Khối lượng (số cổ phiếu).')
    """Khối lượng (số cổ phiếu)."""

    value: float = Field(..., description='Giá trị giao dịch (VND).')
    """Giá trị giao dịch (VND)."""


class StockTrading(BaseModel):
    """
    Giao dịch tổng của một mã trong một phiên (khớp lệnh + thoả thuận).
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    total: TradedAmount
    matched: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần khớp lệnh. `null` khi nguồn không tách được phương thức.',
    )
    """Phần khớp lệnh. `null` khi nguồn không tách được phương thức."""

    put_through: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần thoả thuận. `null` khi nguồn không tách được phương thức.',
    )
    """Phần thoả thuận. `null` khi nguồn không tách được phương thức."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm phiên được ghi lần cuối (ISO 8601 kèm offset).'
    )
    """Thời điểm phiên được ghi lần cuối (ISO 8601 kèm offset)."""


class StockTradingResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockTrading


class StockTradingBar(BaseModel):
    """
    Một phiên trong chuỗi giao dịch tổng.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    total: TradedAmount
    matched: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần khớp lệnh. `null` khi nguồn không tách được phương thức.',
    )
    """Phần khớp lệnh. `null` khi nguồn không tách được phương thức."""

    put_through: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần thoả thuận. `null` khi nguồn không tách được phương thức.',
    )
    """Phần thoả thuận. `null` khi nguồn không tách được phương thức."""


class StockTradingHistory(BaseModel):
    """
    Chuỗi giao dịch tổng theo phiên. Phiên không có giao dịch bị bỏ qua; chưa phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    resolution: str | MISSING = Field(MISSING, description='Độ phân giải của bar.')
    """Độ phân giải của bar."""

    data: list[StockTradingBar] = Field(
        ..., description='Chuỗi bar theo phiên, phiên gần nhất đứng trước.'
    )
    """Chuỗi bar theo phiên, phiên gần nhất đứng trước."""


class StockTradingHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockTradingHistory


class TradingMethodBreakdown(BaseModel):
    """
    Một chiều giao dịch tách theo phương thức: `matched` (khớp lệnh) + `put_through` (thoả thuận) = `total`.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total: TradedAmount
    matched: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần khớp lệnh. `null` khi nguồn không tách được phương thức.',
    )
    """Phần khớp lệnh. `null` khi nguồn không tách được phương thức."""

    put_through: TradedAmount | MISSING = Field(
        MISSING,
        description='Phần thoả thuận. `null` khi nguồn không tách được phương thức.',
    )
    """Phần thoả thuận. `null` khi nguồn không tách được phương thức."""


class TradingFlow(BaseModel):
    """
    Dòng tiền mua / bán / ròng của một nhóm nhà đầu tư trong một phiên.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    buy: TradingMethodBreakdown = Field(..., description='Chiều mua.')
    """Chiều mua."""

    sell: TradingMethodBreakdown = Field(..., description='Chiều bán.')
    """Chiều bán."""

    net: TradingMethodBreakdown = Field(
        ..., description='Ròng = mua − bán. Âm nghĩa là bán ròng.'
    )
    """Ròng = mua − bán. Âm nghĩa là bán ròng."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm trả dữ liệu (ISO 8601 kèm offset).'
    )
    """Thời điểm trả dữ liệu (ISO 8601 kèm offset)."""


class TradingFlowResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: TradingFlow


class TradingFlowBar(BaseModel):
    """
    Một phiên trong chuỗi dòng tiền.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    buy: TradingMethodBreakdown = Field(..., description='Chiều mua.')
    """Chiều mua."""

    sell: TradingMethodBreakdown = Field(..., description='Chiều bán.')
    """Chiều bán."""

    net: TradingMethodBreakdown = Field(
        ..., description='Ròng = mua − bán. Âm nghĩa là bán ròng.'
    )
    """Ròng = mua − bán. Âm nghĩa là bán ròng."""


class TradingFlowHistory(BaseModel):
    """
    Chuỗi dòng tiền theo phiên. Phiên không có giao dịch bị bỏ qua; chưa phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    resolution: str | MISSING = Field(MISSING, description='Độ phân giải của bar.')
    """Độ phân giải của bar."""

    data: list[TradingFlowBar] = Field(
        ..., description='Chuỗi bar theo phiên, phiên gần nhất đứng trước.'
    )
    """Chuỗi bar theo phiên, phiên gần nhất đứng trước."""


class TradingFlowHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: TradingFlowHistory


class OrderSideStatistic(BaseModel):
    """
    Thống kê một chiều lệnh khớp chủ động trong phiên.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_count: float = Field(..., description='Số lệnh khớp về phía này.')
    """Số lệnh khớp về phía này."""

    volume: float = Field(
        ..., description='Tổng khối lượng khớp về phía này (số cổ phiếu).'
    )
    """Tổng khối lượng khớp về phía này (số cổ phiếu)."""

    avg_volume_per_order: float | None | MISSING = Field(
        MISSING,
        description='Khối lượng trung bình mỗi lệnh. `null` khi `order_count = 0` (không có trung bình để tính).',
    )
    """Khối lượng trung bình mỗi lệnh. `null` khi `order_count = 0` (không có trung bình để tính)."""


class StockOrderStatistic(BaseModel):
    """
    Thống kê lệnh mua / bán chủ động của một mã trong một phiên.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    buy: OrderSideStatistic = Field(..., description='Mua chủ động (lifted the offer).')
    """Mua chủ động (lifted the offer)."""

    sell: OrderSideStatistic = Field(..., description='Bán chủ động (hit the bid).')
    """Bán chủ động (hit the bid)."""

    net_volume: float = Field(
        ...,
        description='`buy.volume − sell.volume`. Âm khi bên bán chủ động hơn — đây là số liệu bình thường, không phải lỗi.',
    )
    """`buy.volume − sell.volume`. Âm khi bên bán chủ động hơn — đây là số liệu bình thường, không phải lỗi."""

    updated_at: AwareDatetime | MISSING = Field(
        MISSING, description='Thời điểm phiên được ghi lần cuối (ISO 8601 kèm offset).'
    )
    """Thời điểm phiên được ghi lần cuối (ISO 8601 kèm offset)."""


class StockOrderStatisticResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockOrderStatistic


class StockOrderStatisticBar(BaseModel):
    """
    Một phiên trong chuỗi thống kê lệnh chủ động.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    date: date_aliased = Field(..., description='Ngày của phiên (`YYYY-MM-DD`).')
    """Ngày của phiên (`YYYY-MM-DD`)."""

    buy: OrderSideStatistic = Field(..., description='Mua chủ động.')
    """Mua chủ động."""

    sell: OrderSideStatistic = Field(..., description='Bán chủ động.')
    """Bán chủ động."""

    net_volume: float = Field(..., description='`buy.volume − sell.volume`; có thể âm.')
    """`buy.volume − sell.volume`; có thể âm."""


class StockOrderStatisticHistory(BaseModel):
    """
    Chuỗi thống kê lệnh chủ động theo phiên. Chưa phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str = Field(..., description='Mã cổ phiếu.')
    """Mã cổ phiếu."""

    items: list[StockOrderStatisticBar] = Field(
        ..., description='Chuỗi bar theo phiên.'
    )
    """Chuỗi bar theo phiên."""


class StockOrderStatisticHistoryResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: StockOrderStatisticHistory


class BankInterestRates(BaseModel):
    """
    Lãi suất tiền gửi của các ngân hàng, nhóm theo ngân hàng rồi tới kỳ hạn.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    no_bank: int | MISSING = Field(
        MISSING, description='Số ngân hàng có trong danh sách.'
    )
    """Số ngân hàng có trong danh sách."""

    effective_date: str | MISSING = Field(
        MISSING, description='Ngày áp dụng chung của bảng, định dạng `D/M/YYYY`.'
    )
    """Ngày áp dụng chung của bảng, định dạng `D/M/YYYY`."""

    bank_interest_rates: list[BankInterestRateGroup] = Field(
        ..., description='Mỗi phần tử là một ngân hàng kèm lãi suất theo kỳ hạn.'
    )
    """Mỗi phần tử là một ngân hàng kèm lãi suất theo kỳ hạn."""


class BankInterestRatesResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: BankInterestRates
