# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import EnvelopeBase, OrderType


class OrderBookEntry(BaseModel):
    """
    1 row trong sổ lệnh của ngày. Dùng chung cho
    `/trading/v1/accounts/{subAccountId}/order-book` (array) và
    `/trading/v1/accounts/{subAccountId}/order-book/{orderId}` (đơn lẻ).

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    custodycd: str | MISSING = MISSING
    txdate: str | MISSING = Field(MISSING, description='Transaction date.')
    """Transaction date."""

    custid: str | MISSING = MISSING
    afacctno: str | MISSING = Field(MISSING, description='Account number.')
    """Account number."""

    orderid: str | MISSING = Field(MISSING, description='Order ID.')
    """Order ID."""

    odorderid: str | MISSING = MISSING
    txtime: str | MISSING = Field(MISSING, description='Transaction time.')
    """Transaction time."""

    symbol: str | MISSING = MISSING
    allowcancel: str | MISSING = Field(
        MISSING, description='Whether cancel is allowed.'
    )
    """Whether cancel is allowed."""

    allowamend: str | MISSING = Field(
        MISSING, description='Whether amendment is allowed.'
    )
    """Whether amendment is allowed."""

    side_code: str | MISSING = Field(MISSING, description='Side code (raw).')
    """Side code (raw)."""

    side: str | MISSING = Field(MISSING, description='Side display name (BUY/SELL).')
    """Side display name (BUY/SELL)."""

    price: int | MISSING = MISSING
    pricetype: str | MISSING = Field(MISSING, description='Price type code.')
    """Price type code."""

    via_code: str | MISSING = Field(MISSING, description='Order channel code.')
    """Order channel code."""

    via: str | MISSING = Field(MISSING, description='Order channel name.')
    """Order channel name."""

    qtty: int | MISSING = Field(MISSING, description='Order quantity.')
    """Order quantity."""

    execqtty: int | MISSING = Field(MISSING, description='Executed quantity.')
    """Executed quantity."""

    execamt: int | MISSING = Field(MISSING, description='Executed amount.')
    """Executed amount."""

    execprice: int | MISSING = Field(MISSING, description='Executed price.')
    """Executed price."""

    remainqtty: int | MISSING = Field(MISSING, description='Remaining quantity.')
    """Remaining quantity."""

    remainamt: int | MISSING = Field(MISSING, description='Remaining amount.')
    """Remaining amount."""

    status_code: str | MISSING = Field(MISSING, description='Status code (raw).')
    """Status code (raw)."""

    status: str | MISSING = Field(MISSING, description='Status display name.')
    """Status display name."""

    tlname: str | MISSING = MISSING
    username: str | MISSING = MISSING
    hosesession: str | MISSING = Field(MISSING, description='HOSE session info.')
    """HOSE session info."""

    cancelqtty: int | MISSING = MISSING
    adjustqtty: int | MISSING = MISSING
    isdisposal: str | MISSING = MISSING
    rootorderid: str | MISSING = MISSING
    timetype: str | MISSING = MISSING
    timetypevalue: str | MISSING = MISSING
    feedbackmsg: str | MISSING = Field(
        MISSING, description='Feedback message from exchange.'
    )
    """Feedback message from exchange."""

    quoteqtty: int | MISSING = MISSING
    limitprice: float | MISSING = MISSING
    odtimestamp: str | MISSING = MISSING
    matchtype_code: str | MISSING = MISSING
    producttypename: str | MISSING = MISSING
    afacctno_ext: str | MISSING = MISSING
    side_: str | MISSING = MISSING
    via_: str | MISSING = MISSING
    status_: str | MISSING = MISSING
    matchtype_: str | MISSING = MISSING
    strategy_id: str | None | MISSING = Field(
        MISSING,
        description='Strategy ID if the order is linked to a strategy (only populated for `/order-book/{orderId}` detail).',
    )
    """Strategy ID if the order is linked to a strategy (only populated for `/order-book/{orderId}` detail)."""


class OrderBookResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[OrderBookEntry]


class OrderBookDetailResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: OrderBookEntry


class PortfolioEntry(BaseModel):
    """
    1 stock đang nắm giữ trong portfolio. `close_price` được enrich từ dữ
    liệu realtime. `trade` đã deprecated.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    sub_account_id: str | MISSING = MISSING
    symbol: str | MISSING = MISSING
    securities_type: str | MISSING = Field(
        MISSING, description='Instrument classification (see `StockType` enum).'
    )
    """Instrument classification (see `StockType` enum)."""

    total: int | MISSING = Field(MISSING, description='Total shares held.')
    """Total shares held."""

    available: int | MISSING = Field(MISSING, description='Shares available to sell.')
    """Shares available to sell."""

    blocked: int | MISSING = Field(MISSING, description='Blocked shares.')
    """Blocked shares."""

    mortgage: int | MISSING = Field(MISSING, description='Mortgaged shares.')
    """Mortgaged shares."""

    vsd_mortgage: int | MISSING = Field(MISSING, description='VSD mortgaged shares.')
    """VSD mortgaged shares."""

    restrict: int | MISSING = Field(MISSING, description='Restricted shares.')
    """Restricted shares."""

    receiving_right: int | MISSING = MISSING
    receiving_t0: int | MISSING = Field(MISSING, description='Receiving shares T+0.')
    """Receiving shares T+0."""

    receiving_t1: int | MISSING = Field(MISSING, description='Receiving shares T+1.')
    """Receiving shares T+1."""

    receiving_t2: int | MISSING = Field(MISSING, description='Receiving shares T+2.')
    """Receiving shares T+2."""

    matching_amount: int | MISSING = MISSING
    withdraw: int | MISSING = MISSING
    cost_price: int | MISSING = Field(MISSING, description='Average cost price.')
    """Average cost price."""

    basic_price: int | MISSING = Field(MISSING, description='Basic (reference) price.')
    """Basic (reference) price."""

    is_sellable: bool | MISSING = Field(
        MISSING, description='Whether the stock can be sold.'
    )
    """Whether the stock can be sold."""

    custodycd: str | MISSING = MISSING
    pnl_amount: int | MISSING = Field(MISSING, description='Profit/Loss amount.')
    """Profit/Loss amount."""

    pnl_rate: float | MISSING = Field(
        MISSING, description='Profit/Loss rate (percentage).'
    )
    """Profit/Loss rate (percentage)."""

    close_price: int | MISSING = Field(MISSING, description='Close (current) price.')
    """Close (current) price."""

    cost_price_amount: int | MISSING = Field(MISSING, description='Total cost value.')
    """Total cost value."""

    basic_price_amount: int | MISSING = Field(MISSING, description='Total basic value.')
    """Total basic value."""

    total_pnl: int | MISSING = Field(MISSING, description='Total PnL.')
    """Total PnL."""

    sending_t0: int | MISSING = MISSING
    sending_t1: int | MISSING = MISSING
    sending_t2: int | MISSING = MISSING
    has_newest_news: bool | MISSING = Field(
        MISSING, description='Whether the stock has recent news.'
    )
    """Whether the stock has recent news."""

    trade: int | MISSING = Field(
        MISSING, deprecated=True, description='Deprecated field.'
    )
    """Deprecated field."""


class GetPortfolioResponse(BaseModel):
    """
    Payload portfolio — trường `data` của
    `GET /trading/v2/sub-accounts/{subAccountId}/portfolio`.

    `is_snapshot` cho biết response có phải từ cache hay không.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    portfolio: list[PortfolioEntry] | MISSING = MISSING
    is_snapshot: bool | MISSING = Field(
        MISSING, description='Whether the data is from a cached snapshot.'
    )
    """Whether the data is from a cached snapshot."""


class PortfolioResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: GetPortfolioResponse


class OrderSide(StrEnum):
    """
    Phía của lệnh.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `BUY`  | Lệnh mua |
    | `SELL` | Lệnh bán |

    """

    BUY = 'BUY'
    SELL = 'SELL'


class PlaceOrderKind(StrEnum):
    """
    Kiểu định giá khi đặt lệnh — quyết định field giá nào phải set trong
    request body.

    | Giá trị | Ý nghĩa | Field giá phải set |
    |---------|---------|--------------------|
    | `LIMIT`  | Lệnh giới hạn — khớp tại đúng giá `limit_price` hoặc tốt hơn. | `limit_price` (VND); `market_price` = `null`. |
    | `MARKET` | Lệnh thị trường — khớp theo logic của order type chỉ định. | `market_price` (enum `MarketPriceCode`); `limit_price` = `null`. |

    """

    LIMIT = 'LIMIT'
    MARKET = 'MARKET'


class MarketPriceCode(StrEnum):
    """
    Mã loại lệnh thị trường — set vào field `market_price` khi `type` =
    `MARKET` ở `POST /trading/oa/sub-accounts/{subAccountId}/orders`.

    | Giá trị | Tên | Mô tả |
    |---------|-----|-------|
    | `MP`  | Market Price | Khớp tại giá tốt nhất hiện có (HOSE — ORS auto-convert sang `MTL`). |
    | `ATO` | At The Open | Khớp tại phiên mở cửa. |
    | `ATC` | At The Close | Khớp tại phiên đóng cửa. |
    | `MAK` | Make and Kill | Khớp một phần, phần còn lại huỷ (HNX — ORS auto-convert sang `FAK`). |
    | `MOK` | Make or Kill | Khớp toàn bộ hoặc huỷ (HNX — ORS auto-convert sang `FOK`). |
    | `MTL` | Match To Limit | Khớp theo giá thị trường rồi chuyển phần dư thành limit. |
    | `PLO` | Post Limit Order | Lệnh limit sau phiên ATC (HNX only). |
    | `FOK` | Fill or Kill | Khớp toàn bộ hoặc huỷ — dạng chuẩn hoá của `MOK`. |
    | `FAK` | Fill and Kill | Khớp một phần, huỷ phần còn lại — dạng chuẩn hoá của `MAK`. |

    Hỗ trợ order type theo sàn:
    - HOSE: `LO`, `MP`, `ATO`, `ATC`, `MTL`
    - HNX: `LO`, `MTL`, `MOK`, `MAK`, `PLO`, `ATC`
    - UPCOM / HCX: chỉ `LO`

    """

    MP = 'MP'
    ATO = 'ATO'
    ATC = 'ATC'
    MAK = 'MAK'
    MOK = 'MOK'
    MTL = 'MTL'
    PLO = 'PLO'
    FOK = 'FOK'
    FAK = 'FAK'


class StockTypeOrder(StrEnum):
    """
    Phân loại công cụ tài chính chấp nhận trong request đặt lệnh
    (`POST /trading/oa/sub-accounts/{subAccountId}/orders`). Hẹp hơn
    `StockType` chung — không bao gồm `CW` (đã gộp vào `WARRANT`) và
    `FUTURES` (phái sinh chưa hỗ trợ trên surface này).

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `STOCK`            | Cổ phiếu thường (mặc định nếu bỏ trống) |
    | `BOND`             | Trái phiếu |
    | `FUND_CERTIFICATE` | Chứng chỉ quỹ (mở / đóng) |
    | `WARRANT`          | Chứng quyền có bảo đảm |
    | `ETF`              | Quỹ ETF |

    """

    STOCK = 'STOCK'
    BOND = 'BOND'
    FUND_CERTIFICATE = 'FUND_CERTIFICATE'
    WARRANT = 'WARRANT'
    ETF = 'ETF'


class PlaceOrderRequest(BaseModel):
    """
    Body của request đặt lệnh mới
    (`POST /trading/oa/sub-accounts/{subAccountId}/orders`).

    Quy tắc field giá theo `type`:
    - `type = LIMIT` → set `limit_price` (VND); `market_price` để `null`.
    - `type = MARKET` → set `market_price` (enum `MarketPriceCode`); `limit_price` để `null`.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    sub_account: str = Field(
        ...,
        description='Sub-account ID dạng extended (kèm hậu tố `.1` / `.6` …), khác với\n`subAccountId` ở path param. Lấy từ field `sub_account_ext` của\nresponse `GET /users/v1/users/{userId}/sub-accounts`.\n',
    )
    """
    Sub-account ID dạng extended (kèm hậu tố `.1` / `.6` …), khác với
    `subAccountId` ở path param. Lấy từ field `sub_account_ext` của
    response `GET /users/v1/users/{userId}/sub-accounts`.

    """

    side: OrderSide
    symbol: str = Field(..., description='Mã chứng khoán cần đặt lệnh.')
    """Mã chứng khoán cần đặt lệnh."""

    quantity: int = Field(
        ...,
        description='Số lượng cổ phiếu. Lô chẵn HOSE/HNX là bội số 100. Đặt 1..99 là lô\nlẻ và chỉ chấp nhận `type = LIMIT`.\n',
        ge=1,
    )
    """
    Số lượng cổ phiếu. Lô chẵn HOSE/HNX là bội số 100. Đặt 1..99 là lô
    lẻ và chỉ chấp nhận `type = LIMIT`.

    """

    type: PlaceOrderKind
    limit_price: int | None | MISSING = Field(
        MISSING,
        description='Giá đặt khi `type = LIMIT`, đơn vị **VND** (không nhân 1000). Để\n`null` khi `type = MARKET`.\n',
    )
    """
    Giá đặt khi `type = LIMIT`, đơn vị **VND** (không nhân 1000). Để
    `null` khi `type = MARKET`.

    """

    market_price: MarketPriceCode | None | MISSING = Field(
        MISSING,
        description='Mã loại lệnh thị trường khi `type = MARKET`. Để `null` khi\n`type = LIMIT`.\n',
    )
    """
    Mã loại lệnh thị trường khi `type = MARKET`. Để `null` khi
    `type = LIMIT`.

    """

    stock_type: StockTypeOrder | None = Field(
        'STOCK',
        description='Phân loại công cụ tài chính. Mặc định `STOCK` nếu bỏ trống.\n',
    )
    """
    Phân loại công cụ tài chính. Mặc định `STOCK` nếu bỏ trống.

    """


class OrderStatus(StrEnum):
    """
    Trạng thái lệnh trong vòng đời từ lúc đặt tới khi kết thúc.

    Nhóm chính:

    | Nhóm | Trạng thái |
    |------|------------|
    | Đang xử lý nội bộ | `WAITING_TO_ACTIVATE`, `WAITING_TO_SEND`, `SENDING`, `INTERNAL_SENDING`, `SENDING_TO_CORE`, `WAIT_FOR_ACCEPTING`, `ACCEPTING` |
    | Đã vào sàn / chờ khớp | `SENT`, `ACCEPTED`, `RECEIVED` |
    | Đang sửa / huỷ | `FIXING`, `FIXED`, `CANCELLING` |
    | Khớp | `MATCHED`, `MATCHED_ALL` |
    | Kết thúc thành công | `COMPLETED` |
    | Huỷ / từ chối / lỗi | `CANCELLED`, `INTERNAL_CANCELLED`, `CANCEL_BY_STOCK_EVENT`, `REJECTED`, `REJECTING`, `FAILED`, `EXPIRED`, `EXPIRED_ACTIVATION_TIME`, `EXPIRED_AUTHORIZATION` |

    Sau `place-order`, trạng thái khởi tạo phổ biến là `SENT` (đã đẩy lên
    sàn) hoặc `REJECTED` (sàn từ chối ngay). Sau `modify-order` /
    `cancel-order`, trạng thái phản ánh kết quả thao tác trên phần lệnh
    chưa khớp.

    """

    WAITING_TO_ACTIVATE = 'WAITING_TO_ACTIVATE'
    WAITING_TO_SEND = 'WAITING_TO_SEND'
    SENDING = 'SENDING'
    SENT = 'SENT'
    FIXING = 'FIXING'
    FIXED = 'FIXED'
    CANCELLED = 'CANCELLED'
    CANCELLING = 'CANCELLING'
    MATCHED = 'MATCHED'
    EXPIRED = 'EXPIRED'
    MATCHED_ALL = 'MATCHED_ALL'
    REJECTED = 'REJECTED'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    EXPIRED_ACTIVATION_TIME = 'EXPIRED_ACTIVATION_TIME'
    EXPIRED_AUTHORIZATION = 'EXPIRED_AUTHORIZATION'
    RECEIVED = 'RECEIVED'
    INTERNAL_SENDING = 'INTERNAL_SENDING'
    INTERNAL_CANCELLED = 'INTERNAL_CANCELLED'
    SENDING_TO_CORE = 'SENDING_TO_CORE'
    CANCEL_BY_STOCK_EVENT = 'CANCEL_BY_STOCK_EVENT'
    WAIT_FOR_ACCEPTING = 'WAIT_FOR_ACCEPTING'
    ACCEPTED = 'ACCEPTED'
    ACCEPTING = 'ACCEPTING'
    REJECTING = 'REJECTING'


class LotType(StrEnum):
    """
    Phân loại lô của lệnh — chỉ xuất hiện ở response `OrderExecutionResult`.

    | Giá trị | Ý nghĩa |
    |---------|---------|
    | `EVEN` | Lô chẵn — quantity bội số của lot size (HOSE/HNX: 100). |
    | `ODD`  | Lô lẻ — 1..99 cổ phiếu; chỉ chấp nhận order type `LO`. |

    """

    EVEN = 'EVEN'
    ODD = 'ODD'


class OrderExecutionResult(BaseModel):
    """
    Kết quả thao tác đặt / sửa / huỷ lệnh — phản ánh trạng thái của 1 lệnh
    trên sàn sau khi server xử lý.

    > **Semantic cảnh báo**: HTTP 200 **không** đồng nghĩa với lệnh đã được
    > sàn chấp nhận. Nếu `code` non-null thì sàn từ chối lệnh (`order_status`
    > thường là `REJECTED` hoặc `FAILED`), `rejected_reason` chứa lý do dịch
    > sang ngôn ngữ end-user. Xem bảng `Order-level error codes` trong trang
    > Errors.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    order_id: str = Field(..., description='ID lệnh do sàn cấp.')
    """ID lệnh do sàn cấp."""

    account_id: str = Field(..., description='Sub-account ID dạng extended.')
    """Sub-account ID dạng extended."""

    transaction_date: str = Field(
        ..., description='Ngày giao dịch, định dạng `YYYY-MM-DD`.'
    )
    """Ngày giao dịch, định dạng `YYYY-MM-DD`."""

    symbol: str
    order_side: OrderSide
    order_quantity: int = Field(..., description='Tổng số lượng đã đặt.')
    """Tổng số lượng đã đặt."""

    limit_price: int | None | MISSING = Field(
        MISSING, description='Giá limit (VND), `null` nếu là MARKET order.'
    )
    """Giá limit (VND), `null` nếu là MARKET order."""

    market_price: MarketPriceCode | None | MISSING = Field(
        MISSING, description='Loại giá thị trường, `null` nếu là LIMIT order.'
    )
    """Loại giá thị trường, `null` nếu là LIMIT order."""

    execute_quantity: int | MISSING = Field(
        MISSING, description='Số lượng đã khớp tới hiện tại.'
    )
    """Số lượng đã khớp tới hiện tại."""

    execute_price: int | MISSING = Field(
        MISSING, description='Giá khớp trung bình (VND), `0` nếu chưa khớp.'
    )
    """Giá khớp trung bình (VND), `0` nếu chưa khớp."""

    order_status: OrderStatus
    fee_amount: float | MISSING = Field(MISSING, description='Phí giao dịch (VND).')
    """Phí giao dịch (VND)."""

    tax_amount: float | MISSING = Field(MISSING, description='Thuế (VND).')
    """Thuế (VND)."""

    execute_amount: int | MISSING = Field(
        MISSING,
        description='Giá trị đã khớp = `execute_quantity * execute_price` (VND).',
    )
    """Giá trị đã khớp = `execute_quantity * execute_price` (VND)."""

    order_type: OrderType
    code: str | None | MISSING = Field(
        MISSING,
        description='Mã lỗi cấp lệnh do sàn / ORS trả về. `null` khi lệnh hợp lệ. Khi\nnon-null, đi kèm `rejected_reason` mô tả lý do — xem trang Errors.\n',
    )
    """
    Mã lỗi cấp lệnh do sàn / ORS trả về. `null` khi lệnh hợp lệ. Khi
    non-null, đi kèm `rejected_reason` mô tả lý do — xem trang Errors.

    """

    rejected_reason: str | None | MISSING = Field(
        MISSING,
        description='Lý do lệnh bị từ chối (đã dịch tiếng Việt), `null` khi `code = null`.',
    )
    """Lý do lệnh bị từ chối (đã dịch tiếng Việt), `null` khi `code = null`."""

    lot: LotType


class PlaceOrderResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[OrderExecutionResult] = Field(
        ...,
        description='Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh lệnh\nvừa đặt. Server vẫn trả về dưới dạng array để đồng nhất với\nmodify / cancel.\n',
    )
    """
    Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh lệnh
    vừa đặt. Server vẫn trả về dưới dạng array để đồng nhất với
    modify / cancel.

    """


class ModifyOrderRequest(BaseModel):
    """
    Body của request sửa lệnh
    (`PUT /trading/oa/sub-accounts/{subAccountId}/orders/{orderId}`). Cả 2
    field đều optional nhưng phải có **ít nhất 1**.

    Chỉ sửa được trên phần lệnh **chưa khớp** và khi trạng thái lệnh thuộc
    `SENT` hoặc `WAITING_TO_SEND`. Với lệnh đã khớp một phần, server sẽ
    return `code = -701111` và sửa chỉ áp dụng cho phần unmatched.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    quantity: int | MISSING = Field(
        MISSING, description='Số lượng mới (bội số lot size).', ge=1
    )
    """Số lượng mới (bội số lot size)."""

    price: int | MISSING = Field(
        MISSING, description='Giá limit mới, đơn vị **VND** (không nhân 1000).', ge=1
    )
    """Giá limit mới, đơn vị **VND** (không nhân 1000)."""


class ModifyOrderResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[OrderExecutionResult] = Field(
        ...,
        description='Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh trạng\nthái lệnh sau khi sửa. Khi lệnh đã khớp một phần, server có thể\ntrả `code = -701111` nghĩa là chỉ sửa được phần unmatched.\n',
    )
    """
    Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh trạng
    thái lệnh sau khi sửa. Khi lệnh đã khớp một phần, server có thể
    trả `code = -701111` nghĩa là chỉ sửa được phần unmatched.

    """


class CancelOrderRequest(BaseModel):
    """
    Body của request huỷ lệnh
    (`DELETE /trading/oa/sub-accounts/{subAccountId}/orders/{orderId}`).

    > ⚠️ Đây là DELETE request có body — không chuẩn HTTP nhưng là contract
    > thật của upstream. Client phải tính `X-FH-BODYHASH` từ body này.

    Chỉ huỷ được khi trạng thái lệnh thuộc `SENT`, `WAITING_TO_SEND`,
    `SENDING`. Với lệnh đã khớp một phần, huỷ chỉ áp dụng cho phần
    unmatched.

    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    sub_account: str = Field(
        ...,
        description='Sub-account ID dạng extended (kèm hậu tố `.1` / `.6` …) — cùng giá\ntrị dùng cho `sub_account` trong place-order.\n',
    )
    """
    Sub-account ID dạng extended (kèm hậu tố `.1` / `.6` …) — cùng giá
    trị dùng cho `sub_account` trong place-order.

    """


class CancelOrderResponse(EnvelopeBase):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    result: list[OrderExecutionResult] = Field(
        ...,
        description='Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh trạng\nthái lệnh sau khi huỷ. `order_status` thường là `CANCELLED`\n(huỷ toàn bộ) hoặc giữ nguyên kèm phần `execute_quantity` cũ\nnếu lệnh đã khớp một phần (chỉ huỷ phần unmatched).\n',
    )
    """
    Mảng kết quả — thông thường chứa **đúng 1** entry phản ánh trạng
    thái lệnh sau khi huỷ. `order_status` thường là `CANCELLED`
    (huỷ toàn bộ) hoặc giữ nguyên kèm phần `execute_quantity` cũ
    nếu lệnh đã khớp một phần (chỉ huỷ phần unmatched).

    """
