# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Any, Dict

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING

from .common import (
    MarketType,
    OrderCategory,
    OrderSide,
    OrderStatus,
    OrderType,
    SymbolType,
)


class CorporateActionStatus(StrEnum):
    """
    Trạng thái xử lý sự kiện quyền.

    - `pending`: Đang chờ xử lý hoặc đang được thực hiện
    - `completed`: Đã xử lý hoàn tất
    - `canceled`: Đã hủy thành công
    """

    PENDING = 'pending'
    """Đang chờ xử lý hoặc đang được thực hiện"""

    COMPLETED = 'completed'
    """Đã xử lý hoàn tất"""

    CANCELED = 'canceled'
    """Đã hủy thành công"""


class DerivativeAccountStatus(StrEnum):
    """
    Trạng thái tài khoản phái sinh.

    - `ACTIVE`: Đang hoạt động
    - `INACTIVE`: Ngừng hoạt động
    """

    ACTIVE = 'ACTIVE'
    """Đang hoạt động"""

    INACTIVE = 'INACTIVE'
    """Ngừng hoạt động"""


class PositionStatus(StrEnum):
    """
    Trạng thái vị thế.

    - `OPEN`: Đang mở
    - `PENDING_CLOSE`: Chờ đóng
    - `CLOSED`: Đã đóng
    - `ODD_LOT`: Lô lẻ (cơ sở)
    """

    OPEN = 'OPEN'
    """Đang mở"""

    PENDING_CLOSE = 'PENDING_CLOSE'
    """Chờ đóng"""

    CLOSED = 'CLOSED'
    """Đã đóng"""

    ODD_LOT = 'ODD_LOT'
    """Lô lẻ (cơ sở)"""


class BondBalance(BaseModel):
    """
    Thông tin tài sản trái phiếu
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_value: int | MISSING = Field(
        MISSING, alias='totalValue', description='Tổng giá trị tài sản trái phiếu'
    )
    """Tổng giá trị tài sản trái phiếu"""


class CareBy(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )


class CareByResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    care_by: list[CareBy] | MISSING = Field(MISSING, alias='careBy')
    total: int | MISSING = MISSING


class CashDividend(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID sự kiện quyền')
    """ID sự kiện quyền"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    ca_status: CorporateActionStatus | MISSING = Field(
        MISSING,
        alias='caStatus',
        description='Trạng thái xử lý sự kiện quyền\n- pending: Quyền đang chờ xử lý hoặc đang được thực hiện\n- completed: Quyền đã được xử lý hoàn tất\n- canceled: Quyền đã hủy thành công',
    )
    """
    Trạng thái xử lý sự kiện quyền
    - pending: Quyền đang chờ xử lý hoặc đang được thực hiện
    - completed: Quyền đã được xử lý hoàn tất
    - canceled: Quyền đã hủy thành công
    """

    record_date: str | MISSING = Field(
        MISSING, alias='recordDate', description='Ngày đăng ký cuối cùng sự kiện quyền'
    )
    """Ngày đăng ký cuối cùng sự kiện quyền"""

    process_date: str | MISSING = Field(
        MISSING, alias='processDate', description='Ngày thanh toán dự kiến'
    )
    """Ngày thanh toán dự kiến"""

    holding_quantity: int | MISSING = Field(
        MISSING,
        alias='holdingQuantity',
        description='Số lượng chứng khoán sở hữu tại ngày chốt quyền',
    )
    """Số lượng chứng khoán sở hữu tại ngày chốt quyền"""

    dividend_value: int | MISSING = Field(
        MISSING, alias='dividendValue', description='Giá trị cổ tức trên mỗi cổ phiếu'
    )
    """Giá trị cổ tức trên mỗi cổ phiếu"""

    gross_amount: int | MISSING = Field(
        MISSING, alias='grossAmount', description='Tổng giá trị tiền cổ tức trước thuế'
    )
    """Tổng giá trị tiền cổ tức trước thuế"""

    tax_amount: int | MISSING = Field(
        MISSING, alias='taxAmount', description='Số tiền thuế bị khấu trừ'
    )
    """Số tiền thuế bị khấu trừ"""

    net_amount: int | MISSING = Field(
        MISSING, alias='netAmount', description='Số tiền thực nhận sau thuế'
    )
    """Số tiền thực nhận sau thuế"""


class DerivativeAccount(BaseModel):
    """
    Trạng thái tài khoản phái sinh
    ACTIVE: Đang hoạt động
    INACTIVE: Ngừng hoạt động
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    status: DerivativeAccountStatus | MISSING = Field(
        MISSING, description='Tiểu khoản được phép giao dịch phái sinh hoặc không'
    )
    """Tiểu khoản được phép giao dịch phái sinh hoặc không"""


class DerivativeBalance(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    pending_deposit_withdraw: int | MISSING = Field(
        MISSING,
        alias='pendingDepositWithdraw',
        description='Tiền nộp/rút cọc chờ xử lý',
    )
    """Tiền nộp/rút cọc chờ xử lý"""

    remain_secure: int | MISSING = Field(
        MISSING, alias='remainSecure', description='Cọc còn lại'
    )
    """Cọc còn lại"""

    used_secure: int | MISSING = Field(
        MISSING, alias='usedSecure', description='Cọc đã sử dụng'
    )
    """Cọc đã sử dụng"""

    pending_secure: int | MISSING = Field(
        MISSING, alias='pendingSecure', description='Cọc chờ duyệt'
    )
    """Cọc chờ duyệt"""

    hold_tax_and_fee: int | MISSING = Field(
        MISSING, alias='holdTaxAndFee', description='Thuế và phí tạm giữ'
    )
    """Thuế và phí tạm giữ"""

    total_loan_debt: int | MISSING = Field(
        MISSING, alias='totalLoanDebt', description='Khoản ứng chưa hoàn'
    )
    """Khoản ứng chưa hoàn"""


class EggBalance(BaseModel):
    """
    Thông tin tài sản trứng vàng
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_value: int | MISSING = Field(
        MISSING, alias='totalValue', description='Tổng giá trị tài sản trứng'
    )
    """Tổng giá trị tài sản trứng"""


class ExecutionReport(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID lệnh')
    """ID lệnh"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Chiều giao dịch\n- NB: Mua\n- NS: Bán'
    )
    """
    Chiều giao dịch
    - NB: Mua
    - NS: Bán
    """

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    price: int | MISSING = Field(MISSING, description='Giá đặt lệnh')
    """Giá đặt lệnh"""

    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt lệnh')
    """Khối lượng đặt lệnh"""

    order_type: OrderType | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh\n- LO: Lệnh giới hạn\n- MOK/MAK/MTL: Lệnh thị trường\n- ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa\n- PLO: Lệnh khớp lệnh sau giờ',
    )
    """
    Loại lệnh
    - LO: Lệnh giới hạn
    - MOK/MAK/MTL: Lệnh thị trường
    - ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa
    - PLO: Lệnh khớp lệnh sau giờ
    """

    order_status: OrderStatus | MISSING = Field(
        MISSING,
        alias='orderStatus',
        description='Trạng thái lệnh\n- Pending/PendingNew: Chờ gửi\n- New: Chờ khớp\n- PartiallyFilled: Khớp một phần\n- Filled: Khớp toàn bộ\n- Rejected: Bị từ chối\n- Expired: Hết hạn trong phiên\n- DoneForDay: Lệnh được giải tỏa do không khớp trong phiên',
    )
    """
    Trạng thái lệnh
    - Pending/PendingNew: Chờ gửi
    - New: Chờ khớp
    - PartiallyFilled: Khớp một phần
    - Filled: Khớp toàn bộ
    - Rejected: Bị từ chối
    - Expired: Hết hạn trong phiên
    - DoneForDay: Lệnh được giải tỏa do không khớp trong phiên
    """

    fill_quantity: int | MISSING = Field(
        MISSING, alias='fillQuantity', description='Khối lượng đã khớp'
    )
    """Khối lượng đã khớp"""

    last_quantity: int | MISSING = Field(
        MISSING, alias='lastQuantity', description='Khối lượng khớp gần nhất'
    )
    """Khối lượng khớp gần nhất"""

    last_price: int | MISSING = Field(
        MISSING, alias='lastPrice', description='Giá khớp gần nhất'
    )
    """Giá khớp gần nhất"""

    average_price: int | MISSING = Field(
        MISSING, alias='averagePrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    trans_date: str | MISSING = Field(
        MISSING, alias='transDate', description='Ngày giao dịch'
    )
    """Ngày giao dịch"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm tạo lệnh'
    )
    """Thời điểm tạo lệnh"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật lệnh'
    )
    """Thời điểm cập nhật lệnh"""

    tax_rate: int | MISSING = Field(MISSING, alias='taxRate', description='Tỷ lệ thuế')
    """Tỷ lệ thuế"""

    exchange_fee_rate: int | MISSING = Field(
        MISSING, alias='exchangeFeeRate', description='Tỷ lệ phí trả Sở giao dịch'
    )
    """Tỷ lệ phí trả Sở giao dịch"""

    fee_rate: float | MISSING = Field(
        MISSING, alias='feeRate', description='Tổng tỷ lệ phí của lệnh'
    )
    """Tổng tỷ lệ phí của lệnh"""

    leave_quantity: int | MISSING = Field(
        MISSING, alias='leaveQuantity', description='Khối lượng còn lại chưa khớp'
    )
    """Khối lượng còn lại chưa khớp"""

    canceled_quantity: int | MISSING = Field(
        MISSING, alias='canceledQuantity', description='Khối lượng đã hủy'
    )
    """Khối lượng đã hủy"""

    error: str | MISSING = Field(MISSING, description='Mã lỗi nếu lệnh bị từ chối')
    """Mã lỗi nếu lệnh bị từ chối"""

    price_secure: int | MISSING = Field(
        MISSING,
        alias='priceSecure',
        description='Giá dùng để kiểm tra sức mua/đặt lệnh',
    )
    """Giá dùng để kiểm tra sức mua/đặt lệnh"""

    metadata: str | MISSING = Field(MISSING, description='Thông tin bổ sung của lệnh')
    """Thông tin bổ sung của lệnh"""

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='ID gói vay'
    )
    """ID gói vay"""


class ExecutionsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID lệnh')
    """ID lệnh"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Chiều giao dịch\n- NB: Mua\n- NS: Bán'
    )
    """
    Chiều giao dịch
    - NB: Mua
    - NS: Bán
    """

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    price: int | MISSING = Field(MISSING, description='Giá đặt lệnh')
    """Giá đặt lệnh"""

    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt lệnh')
    """Khối lượng đặt lệnh"""

    order_type: OrderType | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh\n- LO: Lệnh giới hạn\n- MOK/MAK/MTL: Lệnh thị trường\n- ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa\n- PLO: Lệnh khớp lệnh sau giờ',
    )
    """
    Loại lệnh
    - LO: Lệnh giới hạn
    - MOK/MAK/MTL: Lệnh thị trường
    - ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa
    - PLO: Lệnh khớp lệnh sau giờ
    """

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='Mã gói vay'
    )
    """Mã gói vay"""

    order_category: OrderCategory | MISSING = Field(
        MISSING, alias='orderCategory', description='Phân loại lệnh (mặc định NORMAL)'
    )
    """Phân loại lệnh (mặc định NORMAL)"""

    order_status: OrderStatus | MISSING = Field(
        MISSING,
        alias='orderStatus',
        description='Trạng thái lệnh\n- Pending/PendingNew: Chờ gửi\n- New: Chờ khớp\n- PartiallyFilled: Khớp một phần\n- Filled: Khớp toàn bộ\n- Rejected: Bị từ chối\n- Expired: Hết hạn trong phiên\n- DoneForDay: Lệnh được giải tỏa do không khớp trong phiên',
    )
    """
    Trạng thái lệnh
    - Pending/PendingNew: Chờ gửi
    - New: Chờ khớp
    - PartiallyFilled: Khớp một phần
    - Filled: Khớp toàn bộ
    - Rejected: Bị từ chối
    - Expired: Hết hạn trong phiên
    - DoneForDay: Lệnh được giải tỏa do không khớp trong phiên
    """

    fill_quantity: int | MISSING = Field(
        MISSING, alias='fillQuantity', description='Khối lượng đã khớp'
    )
    """Khối lượng đã khớp"""

    last_quantity: int | MISSING = Field(
        MISSING, alias='lastQuantity', description='Khối lượng khớp gần nhất'
    )
    """Khối lượng khớp gần nhất"""

    last_price: int | MISSING = Field(
        MISSING, alias='lastPrice', description='Giá khớp gần nhất'
    )
    """Giá khớp gần nhất"""

    average_price: int | MISSING = Field(
        MISSING, alias='averagePrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    trans_date: str | MISSING = Field(
        MISSING, alias='transDate', description='Ngày giao dịch'
    )
    """Ngày giao dịch"""

    tax_rate: int | MISSING = Field(MISSING, alias='taxRate', description='Tỷ lệ thuế')
    """Tỷ lệ thuế"""

    exchange_fee_rate: float | MISSING = Field(
        MISSING, alias='exchangeFeeRate', description='Tỷ lệ phí trả Sở giao dịch'
    )
    """Tỷ lệ phí trả Sở giao dịch"""

    fee_rate: float | MISSING = Field(
        MISSING, alias='feeRate', description='Tổng tỷ lệ phí của lệnh'
    )
    """Tổng tỷ lệ phí của lệnh"""

    leave_quantity: int | MISSING = Field(
        MISSING, alias='leaveQuantity', description='Khối lượng còn lại chưa khớp'
    )
    """Khối lượng còn lại chưa khớp"""

    canceled_quantity: int | MISSING = Field(
        MISSING, alias='canceledQuantity', description='Khối lượng đã hủy'
    )
    """Khối lượng đã hủy"""

    error: str | MISSING = Field(MISSING, description='Mã lỗi nếu lệnh bị từ chối')
    """Mã lỗi nếu lệnh bị từ chối"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\n- STOCK: Lệnh cơ sở\n- DERIVATIVE: Lệnh phái sinh',
    )
    """
    Loại thị trường
    - STOCK: Lệnh cơ sở
    - DERIVATIVE: Lệnh phái sinh
    """

    price_secure: int | MISSING = Field(
        MISSING,
        alias='priceSecure',
        description='Giá dùng để kiểm tra sức mua/đặt lệnh',
    )
    """Giá dùng để kiểm tra sức mua/đặt lệnh"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm tạo lệnh'
    )
    """Thời điểm tạo lệnh"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật lệnh'
    )
    """Thời điểm cập nhật lệnh"""

    metadata: str | MISSING = Field(MISSING, description='Thông tin bổ sung của lệnh')
    """Thông tin bổ sung của lệnh"""

    reports: list[ExecutionReport] | MISSING = Field(
        MISSING, description='Danh sách trạng thái lệnh theo từng lần cập nhật'
    )
    """Danh sách trạng thái lệnh theo từng lần cập nhật"""


class Loan(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID khoản vay')
    """ID khoản vay"""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    position_id: int | MISSING = Field(
        MISSING, alias='positionId', description='ID vị thế liên kết với khoản vay'
    )
    """ID vị thế liên kết với khoản vay"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    disbursement_date: date | MISSING = Field(
        MISSING, alias='disbursementDate', description='Ngày giải ngân khoản vay'
    )
    """Ngày giải ngân khoản vay"""

    due_date: date | MISSING = Field(
        MISSING, alias='dueDate', description='Ngày đến hạn của khoản vay'
    )
    """Ngày đến hạn của khoản vay"""

    initial_rate: int | MISSING = Field(
        MISSING, alias='initialRate', description='Tỷ lệ cho vay ban đầu'
    )
    """Tỷ lệ cho vay ban đầu"""

    interest_rate: float | MISSING = Field(
        MISSING, alias='interestRate', description='Lãi suất áp dụng cho khoản vay'
    )
    """Lãi suất áp dụng cho khoản vay"""

    overdue_interest_rate: float | MISSING = Field(
        MISSING,
        alias='overdueInterestRate',
        description='Lãi suất áp dụng khi khoản vay quá hạn',
    )
    """Lãi suất áp dụng khi khoản vay quá hạn"""

    preferential_period: int | MISSING = Field(
        MISSING,
        alias='preferentialPeriod',
        description='Thời gian áp dụng lãi suất ưu đãi',
    )
    """Thời gian áp dụng lãi suất ưu đãi"""

    preferential_interest_rate: int | MISSING = Field(
        MISSING,
        alias='preferentialInterestRate',
        description='Lãi suất ưu đãi áp dụng cho khoản vay',
    )
    """Lãi suất ưu đãi áp dụng cho khoản vay"""

    principal: int | MISSING = Field(
        MISSING, description='Giá trị dư nợ gốc ban đầu của khoản vay'
    )
    """Giá trị dư nợ gốc ban đầu của khoản vay"""

    remain_principal: int | MISSING = Field(
        MISSING, alias='remainPrincipal', description='Giá trị dư nợ gốc còn lại'
    )
    """Giá trị dư nợ gốc còn lại"""

    remain_interest: int | MISSING = Field(
        MISSING, alias='remainInterest', description='Giá trị lãi vay còn lại'
    )
    """Giá trị lãi vay còn lại"""


class Pagination(BaseModel):
    """
    Thông tin phân trang của danh sách kết quả.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Chỉ số trang hiện tại, bắt đầu từ 0'
    )
    """Chỉ số trang hiện tại, bắt đầu từ 0"""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi tối đa trên mỗi trang'
    )
    """Số lượng bản ghi tối đa trên mỗi trang"""

    total_records: int | MISSING = Field(
        MISSING, alias='totalRecords', description='Tổng số bản ghi'
    )
    """Tổng số bản ghi"""

    total_pages: int | MISSING = Field(
        MISSING, alias='totalPages', description='Tổng số trang'
    )
    """Tổng số trang"""


class LoansResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    loans: list[Loan] | MISSING = Field(MISSING, description='Danh sách các khoản vay')
    """Danh sách các khoản vay"""

    pagination: Pagination | MISSING = Field(
        MISSING, description='Thông tin phân trang của danh sách kết quả.'
    )
    """Thông tin phân trang của danh sách kết quả."""


class Order(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='Id lệnh giao dịch')
    """Id lệnh giao dịch"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Chiều giao dịch\nNB: Mua\nNS: Bán'
    )
    """
    Chiều giao dịch
    NB: Mua
    NS: Bán
    """

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    price: float | MISSING = Field(MISSING, description='Giá đặt')
    """Giá đặt"""

    price_secure: float | MISSING = Field(
        MISSING,
        alias='priceSecure',
        description='Giá dùng để kiểm tra sức mua/đặt lệnh',
    )
    """Giá dùng để kiểm tra sức mua/đặt lệnh"""

    average_price: float | MISSING = Field(
        MISSING, alias='averagePrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt')
    """Khối lượng đặt"""

    fill_quantity: int | MISSING = Field(
        MISSING, alias='fillQuantity', description='Khối lượng đã khớp'
    )
    """Khối lượng đã khớp"""

    canceled_quantity: int | MISSING = Field(
        MISSING, alias='canceledQuantity', description='Khối lượng đã hủy'
    )
    """Khối lượng đã hủy"""

    leave_quantity: int | MISSING = Field(
        MISSING, alias='leaveQuantity', description='Khối lượng còn lại'
    )
    """Khối lượng còn lại"""

    order_type: OrderType | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh\n- LO: Lệnh giới hạn\n- MOK/MAK/MTL: Lệnh thị trường\n- ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa\n- PLO: Lệnh khớp lệnh sau giờ',
    )
    """
    Loại lệnh
    - LO: Lệnh giới hạn
    - MOK/MAK/MTL: Lệnh thị trường
    - ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa
    - PLO: Lệnh khớp lệnh sau giờ
    """

    order_category: OrderCategory | MISSING = Field(
        MISSING,
        alias='orderCategory',
        description='Phân loại lệnh thường, lệnh điều kiện (mặc định NORMAL)',
    )
    """Phân loại lệnh thường, lệnh điều kiện (mặc định NORMAL)"""

    order_status: OrderStatus | MISSING = Field(
        MISSING,
        alias='orderStatus',
        description='Trạng thái lệnh\n- Pending/PendingNew: Chờ gửi\n- New: Chờ khớp\n- PendingReplace: Chờ sửa\n- PendingCancel: Chờ hủy\n- PartiallyFilled: Khớp một phần\n- Filled: Khớp toàn bộ\n- Canceled: Đã hủy\n- Rejected: Bị từ chối\n- Expired: Hết hạn trong phiên\n- DoneForDay: Lệnh được giải tỏa do không khớp trong phiên',
    )
    """
    Trạng thái lệnh
    - Pending/PendingNew: Chờ gửi
    - New: Chờ khớp
    - PendingReplace: Chờ sửa
    - PendingCancel: Chờ hủy
    - PartiallyFilled: Khớp một phần
    - Filled: Khớp toàn bộ
    - Canceled: Đã hủy
    - Rejected: Bị từ chối
    - Expired: Hết hạn trong phiên
    - DoneForDay: Lệnh được giải tỏa do không khớp trong phiên
    """

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='Gói vay áp dụng cho mã chứng khoán'
    )
    """Gói vay áp dụng cho mã chứng khoán"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\nSTOCK: Lệnh cơ sở\nDERIVATIVE: Lệnh phái sinh\nBOND: Lệnh trái phiếu',
    )
    """
    Loại thị trường
    STOCK: Lệnh cơ sở
    DERIVATIVE: Lệnh phái sinh
    BOND: Lệnh trái phiếu
    """

    trans_date: str | MISSING = Field(
        MISSING, alias='transDate', description='Ngày giao dịch'
    )
    """Ngày giao dịch"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm tạo'
    )
    """Thời điểm tạo"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""


class OrdersHistoryItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: str | MISSING = Field(MISSING, description='ID lệnh trên hệ thống')
    """ID lệnh trên hệ thống"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Chiều giao dịch\nNB: Mua\nNS: Bán'
    )
    """
    Chiều giao dịch
    NB: Mua
    NS: Bán
    """

    order_type: OrderType | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh\n- LO: Lệnh giới hạn\n- MOK/MAK/MTL: Lệnh thị trường\n- ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa\n- PLO: Lệnh khớp lệnh sau giờ',
    )
    """
    Loại lệnh
    - LO: Lệnh giới hạn
    - MOK/MAK/MTL: Lệnh thị trường
    - ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa
    - PLO: Lệnh khớp lệnh sau giờ
    """

    order_status: OrderStatus | MISSING = Field(
        MISSING,
        alias='orderStatus',
        description='Trạng thái lệnh\n- Pending/PendingNew: Chờ gửi\n- New: Chờ khớp\n- PartiallyFilled: Khớp một phần\n- Filled: Khớp toàn bộ\n- Rejected: Bị từ chối\n- Expired: Hết hạn trong phiên\n- DoneForDay: Lệnh được giải tỏa do không khớp trong phiên',
    )
    """
    Trạng thái lệnh
    - Pending/PendingNew: Chờ gửi
    - New: Chờ khớp
    - PartiallyFilled: Khớp một phần
    - Filled: Khớp toàn bộ
    - Rejected: Bị từ chối
    - Expired: Hết hạn trong phiên
    - DoneForDay: Lệnh được giải tỏa do không khớp trong phiên
    """

    price: int | MISSING = Field(MISSING, description='Giá đặt')
    """Giá đặt"""

    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt')
    """Khối lượng đặt"""

    fill_quantity: int | MISSING = Field(
        MISSING, alias='fillQuantity', description='Khối lượng đã khớp'
    )
    """Khối lượng đã khớp"""

    leave_quantity: int | MISSING = Field(
        MISSING, alias='leaveQuantity', description='Khối lượng còn lại'
    )
    """Khối lượng còn lại"""

    canceled_quantity: int | MISSING = Field(
        MISSING, alias='canceledQuantity', description='Khối lượng đã huỷ'
    )
    """Khối lượng đã huỷ"""

    average_price: int | MISSING = Field(
        MISSING, alias='averagePrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='ID gói vay'
    )
    """ID gói vay"""

    trans_date: str | MISSING = Field(
        MISSING, alias='transDate', description='Ngày giao dịch'
    )
    """Ngày giao dịch"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm tạo'
    )
    """Thời điểm tạo"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""


class OrdersHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    fill_quantity: int | MISSING = Field(
        MISSING, alias='fillQuantity', description='Tổng khối lượng đã khớp'
    )
    """Tổng khối lượng đã khớp"""

    total: int | MISSING = Field(MISSING, description='Tổng số bản ghi')
    """Tổng số bản ghi"""

    start: int | MISSING = Field(
        MISSING, description='Vị trí bắt đầu của tập bản ghi được trả về'
    )
    """Vị trí bắt đầu của tập bản ghi được trả về"""

    end: int | MISSING = Field(
        MISSING, description='Vị trí kết thúc của tập bản ghi được trả về'
    )
    """Vị trí kết thúc của tập bản ghi được trả về"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\n- STOCK: Gói vay giao dịch cơ sở\n- DERIVATIVE: Gói vay giao dịch phái sinh',
    )
    """
    Loại thị trường
    - STOCK: Gói vay giao dịch cơ sở
    - DERIVATIVE: Gói vay giao dịch phái sinh
    """

    data: list[OrdersHistoryItem] | MISSING = Field(
        MISSING, description='Danh sách lệnh giao dịch'
    )
    """Danh sách lệnh giao dịch"""


class OrdersResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    orders: list[Order] | MISSING = Field(
        MISSING, description='Danh sách lệnh giao dịch'
    )
    """Danh sách lệnh giao dịch"""

    page_index: int | MISSING = Field(MISSING, alias='pageIndex')
    page_size: int | MISSING = Field(MISSING, alias='pageSize')
    total_pages: int | MISSING = Field(MISSING, alias='totalPages')
    total_records: int | MISSING = Field(MISSING, alias='totalRecords')


class PaginationModel(BaseModel):
    """
    Thông tin phân trang dữ liệu
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    page_index: int | MISSING = Field(
        MISSING, alias='pageIndex', description='Trang hiện tại'
    )
    """Trang hiện tại"""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số lượng bản ghi trên mỗi trang'
    )
    """Số lượng bản ghi trên mỗi trang"""

    total_records: int | MISSING = Field(
        MISSING, alias='totalRecords', description='Tổng số bản ghi'
    )
    """Tổng số bản ghi"""


class Position(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID vị thế')
    """ID vị thế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\nSTOCK: Gói vay giao dịch cơ sở\nDERIVATIVE: Gói vay giao dịch phái sinh',
    )
    """
    Loại thị trường
    STOCK: Gói vay giao dịch cơ sở
    DERIVATIVE: Gói vay giao dịch phái sinh
    """

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    status: PositionStatus | MISSING = Field(
        MISSING,
        description='Trạng thái của vị thế\nOPEN: Đang mở\nPENDING_CLOSE: Chờ đóng\nCLOSED: Đã đóng\nODD_LOT: Lô lẻ (cơ sở)',
    )
    """
    Trạng thái của vị thế
    OPEN: Đang mở
    PENDING_CLOSE: Chờ đóng
    CLOSED: Đã đóng
    ODD_LOT: Lô lẻ (cơ sở)
    """

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='Gói vay cơ sở hoặc phái sinh'
    )
    """Gói vay cơ sở hoặc phái sinh"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Loại vị thế\nNB: Mua\nNS: Bán'
    )
    """
    Loại vị thế
    NB: Mua
    NS: Bán
    """

    accumulate_quantity: int | MISSING = Field(
        MISSING, alias='accumulateQuantity', description='Khối lượng cộng dồn'
    )
    """Khối lượng cộng dồn"""

    trade_quantity: int | MISSING = Field(
        MISSING, alias='tradeQuantity', description='Khối lượng được giao dịch'
    )
    """Khối lượng được giao dịch"""

    closed_quantity: int | MISSING = Field(
        MISSING, alias='closedQuantity', description='Khối lượng đã đóng'
    )
    """Khối lượng đã đóng"""

    open_quantity: int | MISSING = Field(
        MISSING, alias='openQuantity', description='Khối lượng mở'
    )
    """Khối lượng mở"""

    over_night_quantity: int | MISSING = Field(
        MISSING,
        alias='overNightQuantity',
        description='Khối lượng mở qua đêm (dành cho phái sinh)',
    )
    """Khối lượng mở qua đêm (dành cho phái sinh)"""

    cost_price: float | MISSING = Field(
        MISSING, alias='costPrice', description='Giá vốn trung bình của khối lượng mở'
    )
    """Giá vốn trung bình của khối lượng mở"""

    market_price: float | MISSING = Field(
        MISSING, alias='marketPrice', description='Giá thị trường'
    )
    """Giá thị trường"""

    break_even_price: float | MISSING = Field(
        MISSING, alias='breakEvenPrice', description='Giá hòa vốn'
    )
    """Giá hòa vốn"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm mở'
    )
    """Thời điểm mở"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""


class PositionDetail(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID vị thế')
    """ID vị thế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\n- STOCK: Vị thế cơ sở\n- DERIVATIVE: Vị thế phái sinh',
    )
    """
    Loại thị trường
    - STOCK: Vị thế cơ sở
    - DERIVATIVE: Vị thế phái sinh
    """

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    status: PositionStatus | MISSING = Field(
        MISSING,
        description='Trạng thái của vị thế\n- OPEN: Đang mở\n- PENDING_CLOSE: Chờ đóng\n- CLOSED: Đã đóng\n- ODD_LOT: Lô lẻ (cơ sở)',
    )
    """
    Trạng thái của vị thế
    - OPEN: Đang mở
    - PENDING_CLOSE: Chờ đóng
    - CLOSED: Đã đóng
    - ODD_LOT: Lô lẻ (cơ sở)
    """

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='Gói vay cơ sở hoặc phái sinh'
    )
    """Gói vay cơ sở hoặc phái sinh"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Loại vị thế\n- NB: Mua\n- NS: Bán'
    )
    """
    Loại vị thế
    - NB: Mua
    - NS: Bán
    """

    accumulate_quantity: int | MISSING = Field(
        MISSING, alias='accumulateQuantity', description='Khối lượng cộng dồn'
    )
    """Khối lượng cộng dồn"""

    trade_quantity: int | MISSING = Field(
        MISSING, alias='tradeQuantity', description='Khối lượng được giao dịch'
    )
    """Khối lượng được giao dịch"""

    closed_quantity: int | MISSING = Field(
        MISSING, alias='closedQuantity', description='Khối lượng đã đóng'
    )
    """Khối lượng đã đóng"""

    open_quantity: int | MISSING = Field(
        MISSING, alias='openQuantity', description='Khối lượng mở'
    )
    """Khối lượng mở"""

    over_night_quantity: int | None | MISSING = Field(
        MISSING,
        alias='overNightQuantity',
        description='Khối lượng mở qua đêm (dành cho phái sinh)',
    )
    """Khối lượng mở qua đêm (dành cho phái sinh)"""

    cost_price: float | MISSING = Field(
        MISSING, alias='costPrice', description='Giá vốn trung bình của khối lượng mở'
    )
    """Giá vốn trung bình của khối lượng mở"""

    average_cost_price: float | MISSING = Field(
        MISSING, alias='averageCostPrice', description='Giá vốn trung bình'
    )
    """Giá vốn trung bình"""

    average_close_price: float | MISSING = Field(
        MISSING, alias='averageClosePrice', description='Giá đóng trung bình'
    )
    """Giá đóng trung bình"""

    market_price: float | MISSING = Field(
        MISSING, alias='marketPrice', description='Giá thị trường'
    )
    """Giá thị trường"""

    break_even_price: float | MISSING = Field(
        MISSING, alias='breakEvenPrice', description='Giá hòa vốn'
    )
    """Giá hòa vốn"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm mở'
    )
    """Thời điểm mở"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""


class PositionDetailResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: PositionDetail | MISSING = MISSING
    id: int | MISSING = Field(MISSING, description='ID vị thế')
    """ID vị thế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    status: PositionStatus | MISSING = Field(
        MISSING,
        description='Trạng thái của vị thế\n- OPEN: Đang mở\n- PENDING_CLOSE: Chờ đóng\n- CLOSED: Đã đóng\n- ODD_LOT: Lô lẻ (cơ sở)',
    )
    """
    Trạng thái của vị thế
    - OPEN: Đang mở
    - PENDING_CLOSE: Chờ đóng
    - CLOSED: Đã đóng
    - ODD_LOT: Lô lẻ (cơ sở)
    """

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='Gói vay cơ sở hoặc phái sinh'
    )
    """Gói vay cơ sở hoặc phái sinh"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Loại vị thế\n- NB: Mua\n- NS: Bán'
    )
    """
    Loại vị thế
    - NB: Mua
    - NS: Bán
    """

    accumulate_quantity: int | MISSING = Field(
        MISSING, alias='accumulateQuantity', description='Khối lượng cộng dồn'
    )
    """Khối lượng cộng dồn"""

    trade_quantity: int | MISSING = Field(
        MISSING, alias='tradeQuantity', description='Khối lượng được giao dịch'
    )
    """Khối lượng được giao dịch"""

    closed_quantity: int | MISSING = Field(
        MISSING, alias='closedQuantity', description='Khối lượng đã đóng'
    )
    """Khối lượng đã đóng"""

    open_quantity: int | MISSING = Field(
        MISSING, alias='openQuantity', description='Khối lượng mở'
    )
    """Khối lượng mở"""

    cost_price: int | MISSING = Field(
        MISSING, alias='costPrice', description='Giá vốn trung bình của khối lượng mở'
    )
    """Giá vốn trung bình của khối lượng mở"""

    average_cost_price: int | MISSING = Field(
        MISSING, alias='averageCostPrice', description='Giá vốn trung bình'
    )
    """Giá vốn trung bình"""

    average_close_price: int | MISSING = Field(
        MISSING, alias='averageClosePrice', description='Giá đóng trung bình'
    )
    """Giá đóng trung bình"""

    market_price: int | MISSING = Field(
        MISSING, alias='marketPrice', description='Giá thị trường'
    )
    """Giá thị trường"""

    break_even_price: float | MISSING = Field(
        MISSING, alias='breakEvenPrice', description='Giá hòa vốn'
    )
    """Giá hòa vốn"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm mở'
    )
    """Thời điểm mở"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""


class PositionsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    positions: list[Position] | MISSING = Field(MISSING, description='')
    """"""

    page_index: int | MISSING = Field(
        MISSING,
        alias='pageIndex',
        description='Kích thước trang dữ liệu (dành cho phái sinh)',
    )
    """Kích thước trang dữ liệu (dành cho phái sinh)"""

    page_size: int | MISSING = Field(
        MISSING,
        alias='pageSize',
        description='Số bản ghi trên 1 trang (dành cho phái sinh)',
    )
    """Số bản ghi trên 1 trang (dành cho phái sinh)"""

    page_number: int | MISSING = Field(
        MISSING, alias='pageNumber', description='Số trang (chỉ dành cho phái sinh)'
    )
    """Số trang (chỉ dành cho phái sinh)"""

    total: int | MISSING = Field(
        MISSING, description='Tổng số vị thế (chỉ dành cho phái sinh)'
    )
    """Tổng số vị thế (chỉ dành cho phái sinh)"""


class PpseResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    qmax_buy: int | MISSING = Field(
        MISSING, alias='qmaxBuy', description='Khối lượng mua tối đa'
    )
    """Khối lượng mua tối đa"""

    qmax_sell: int | MISSING = Field(
        MISSING, alias='qmaxSell', description='Khối lượng bán tối đa'
    )
    """Khối lượng bán tối đa"""

    pp0_buy: float | MISSING = Field(
        MISSING, alias='pp0Buy', description='Sức mua tối đa'
    )
    """Sức mua tối đa"""

    pp0_short: float | MISSING = Field(
        MISSING, alias='pp0Short', description='Sức bán khống tối đa'
    )
    """Sức bán khống tối đa"""

    price: float | MISSING = Field(MISSING, description='Giá đặt')
    """Giá đặt"""


class ProgressiveDailyCloseTradingFee(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    from_quantity: float | MISSING = Field(
        MISSING, alias='fromQuantity', description='Khối lượng bắt đầu'
    )
    """Khối lượng bắt đầu"""

    to_quantity: float | MISSING = Field(
        MISSING, alias='toQuantity', description='Khối lượng kết thúc'
    )
    """Khối lượng kết thúc"""

    fee: float | MISSING = Field(MISSING, description='Mức phí')
    """Mức phí"""


class ProgressiveTradingFee(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    from_quantity: float | MISSING = Field(
        MISSING, alias='fromQuantity', description='Khối lượng bắt đầu'
    )
    """Khối lượng bắt đầu"""

    to_quantity: float | MISSING = Field(
        MISSING, alias='toQuantity', description='Khối lượng kết thúc'
    )
    """Khối lượng kết thúc"""

    fee: float | MISSING = Field(MISSING, description='Mức phí')
    """Mức phí"""


class RightsOffering(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID sự kiện quyền')
    """ID sự kiện quyền"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    ca_status: CorporateActionStatus | MISSING = Field(
        MISSING,
        alias='caStatus',
        description='Trạng thái xử lý sự kiện quyền\n- pending: Quyền đang chờ xử lý hoặc đang được thực hiện\n- completed: Quyền đã được xử lý hoàn tất\n- canceled: Quyền đã hủy thành công',
    )
    """
    Trạng thái xử lý sự kiện quyền
    - pending: Quyền đang chờ xử lý hoặc đang được thực hiện
    - completed: Quyền đã được xử lý hoàn tất
    - canceled: Quyền đã hủy thành công
    """

    record_date: str | MISSING = Field(
        MISSING,
        alias='recordDate',
        description='Ngày đăng ký cuối cùng sự kiện quyền để xác định quyền mua',
    )
    """Ngày đăng ký cuối cùng sự kiện quyền để xác định quyền mua"""

    process_date: str | MISSING = Field(
        MISSING,
        alias='processDate',
        description='Ngày phân phối cổ phiếu quyền mua dự kiến',
    )
    """Ngày phân phối cổ phiếu quyền mua dự kiến"""

    holding_quantity: int | MISSING = Field(
        MISSING,
        alias='holdingQuantity',
        description='Số lượng chứng khoán sở hữu tại ngày chốt quyền',
    )
    """Số lượng chứng khoán sở hữu tại ngày chốt quyền"""

    ratio: str | MISSING = Field(
        MISSING, description='Tỷ lệ thực hiện quyền mua cổ phiếu'
    )
    """Tỷ lệ thực hiện quyền mua cổ phiếu"""

    right_price: int | MISSING = Field(
        MISSING,
        alias='rightPrice',
        description='Giá đăng ký mua cổ phiếu phát hành thêm',
    )
    """Giá đăng ký mua cổ phiếu phát hành thêm"""

    rights_quantity: int | MISSING = Field(
        MISSING,
        alias='rightsQuantity',
        description='Số lượng quyền mua được phân bổ trên tài khoản',
    )
    """Số lượng quyền mua được phân bổ trên tài khoản"""

    registered_quantity: int | MISSING = Field(
        MISSING,
        alias='registeredQuantity',
        description='Số lượng cổ phiếu phát hành thêm đã đăng ký mua',
    )
    """Số lượng cổ phiếu phát hành thêm đã đăng ký mua"""

    start_date_transfer: str | MISSING = Field(
        MISSING,
        alias='startDateTransfer',
        description='Ngày bắt đầu được phép chuyển nhượng quyền mua',
    )
    """Ngày bắt đầu được phép chuyển nhượng quyền mua"""

    end_date_transfer: str | MISSING = Field(
        MISSING,
        alias='endDateTransfer',
        description='Ngày kết thúc chuyển nhượng quyền mua',
    )
    """Ngày kết thúc chuyển nhượng quyền mua"""

    start_date_subscription: str | MISSING = Field(
        MISSING,
        alias='startDateSubscription',
        description='Ngày bắt đầu đăng ký thực hiện quyền mua',
    )
    """Ngày bắt đầu đăng ký thực hiện quyền mua"""

    end_date_subscription: str | MISSING = Field(
        MISSING,
        alias='endDateSubscription',
        description='Ngày kết thúc đăng ký thực hiện quyền mua',
    )
    """Ngày kết thúc đăng ký thực hiện quyền mua"""


class StockBalance(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    total_cash: int | MISSING = Field(
        MISSING,
        alias='totalCash',
        description='Tổng tiền (Tiền mặt + Lãi tiền gửi + Tiền bán chờ về + Tiền cổ tức chờ về - Tiền mua trong ngày)',
    )
    """Tổng tiền (Tiền mặt + Lãi tiền gửi + Tiền bán chờ về + Tiền cổ tức chờ về - Tiền mua trong ngày)"""

    available_cash: int | MISSING = Field(
        MISSING, alias='availableCash', description='Tiền mặt hiện có'
    )
    """Tiền mặt hiện có"""

    deposit_interest: int | MISSING = Field(
        MISSING, alias='depositInterest', description='Lãi tiền gửi không kỳ hạn'
    )
    """Lãi tiền gửi không kỳ hạn"""

    total_debt: int | MISSING = Field(
        MISSING,
        alias='totalDebt',
        description='Tổng nợ (Nợ margin tạm thu + Nợ margin còn lại)',
    )
    """Tổng nợ (Nợ margin tạm thu + Nợ margin còn lại)"""

    deposit_fee_amount: int | MISSING = Field(
        MISSING, alias='depositFeeAmount', description='Phí lưu ký'
    )
    """Phí lưu ký"""

    secure_amount: int | MISSING = Field(
        MISSING, alias='secureAmount', description='Tổng tiền ký quỹ'
    )
    """Tổng tiền ký quỹ"""

    order_secured: int | MISSING = Field(
        MISSING,
        alias='orderSecured',
        description='Số tiền đang được phong tỏa cho các lệnh giao dịch',
    )
    """Số tiền đang được phong tỏa cho các lệnh giao dịch"""

    withdrawable_cash: int | MISSING = Field(
        MISSING, alias='withdrawableCash', description='Tiền có thể rút'
    )
    """Tiền có thể rút"""

    cash_dividend_receiving: int | MISSING = Field(
        MISSING, alias='cashDividendReceiving', description='Tiền cổ tức chờ về'
    )
    """Tiền cổ tức chờ về"""


class StockBonus(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID sự kiện quyền')
    """ID sự kiện quyền"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    ca_status: CorporateActionStatus | MISSING = Field(
        MISSING,
        alias='caStatus',
        description='Trạng thái xử lý sự kiện quyền\n- pending: Quyền đang chờ xử lý hoặc đang được thực hiện\n- completed: Quyền đã được xử lý hoàn tất\n- canceled: Quyền đã hủy thành công',
    )
    """
    Trạng thái xử lý sự kiện quyền
    - pending: Quyền đang chờ xử lý hoặc đang được thực hiện
    - completed: Quyền đã được xử lý hoàn tất
    - canceled: Quyền đã hủy thành công
    """

    record_date: str | MISSING = Field(
        MISSING, alias='recordDate', description='Ngày đăng ký cuối cùng sự kiện quyền'
    )
    """Ngày đăng ký cuối cùng sự kiện quyền"""

    process_date: str | MISSING = Field(
        MISSING,
        alias='processDate',
        description='Ngày phân phối cổ phiếu thưởng dự kiến',
    )
    """Ngày phân phối cổ phiếu thưởng dự kiến"""

    holding_quantity: int | MISSING = Field(
        MISSING,
        alias='holdingQuantity',
        description='Số lượng chứng khoán sở hữu tại ngày chốt quyền',
    )
    """Số lượng chứng khoán sở hữu tại ngày chốt quyền"""

    ratio: str | MISSING = Field(
        MISSING, description='Tỷ lệ thực hiện quyền nhận cổ phiếu thưởng'
    )
    """Tỷ lệ thực hiện quyền nhận cổ phiếu thưởng"""

    received_quantity: int | MISSING = Field(
        MISSING,
        alias='receivedQuantity',
        description='Số lượng cổ phiếu thưởng khách hàng được nhận',
    )
    """Số lượng cổ phiếu thưởng khách hàng được nhận"""


class StockDividend(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='ID sự kiện quyền')
    """ID sự kiện quyền"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    ca_status: CorporateActionStatus | MISSING = Field(
        MISSING,
        alias='caStatus',
        description='Trạng thái xử lý sự kiện quyền\n- pending: Quyền đang chờ xử lý hoặc đang được thực hiện\n- completed: Quyền đã được xử lý hoàn tất\n- canceled: Quyền đã hủy thành công',
    )
    """
    Trạng thái xử lý sự kiện quyền
    - pending: Quyền đang chờ xử lý hoặc đang được thực hiện
    - completed: Quyền đã được xử lý hoàn tất
    - canceled: Quyền đã hủy thành công
    """

    record_date: str | MISSING = Field(
        MISSING, alias='recordDate', description='Ngày đăng ký cuối cùng sự kiện quyền'
    )
    """Ngày đăng ký cuối cùng sự kiện quyền"""

    process_date: str | MISSING = Field(
        MISSING,
        alias='processDate',
        description='Ngày phân phối cổ phiếu cổ tức dự kiến',
    )
    """Ngày phân phối cổ phiếu cổ tức dự kiến"""

    holding_quantity: int | MISSING = Field(
        MISSING,
        alias='holdingQuantity',
        description='Số lượng chứng khoán sở hữu tại ngày chốt quyền',
    )
    """Số lượng chứng khoán sở hữu tại ngày chốt quyền"""

    ratio: str | MISSING = Field(
        MISSING, description='Tỷ lệ thực hiện quyền nhận cổ tức bằng cổ phiếu'
    )
    """Tỷ lệ thực hiện quyền nhận cổ tức bằng cổ phiếu"""

    received_quantity: int | MISSING = Field(
        MISSING,
        alias='receivedQuantity',
        description='Số lượng cổ phiếu cổ tức được nhận',
    )
    """Số lượng cổ phiếu cổ tức được nhận"""


class TradingFeeSchemaType(StrEnum):
    """
    Loại biểu phí.

    - `FIXED`: Phí cố định
    - `PROGRESSIVE`: Phí lũy tiến
    """

    FIXED = 'FIXED'
    """Phí cố định"""

    PROGRESSIVE = 'PROGRESSIVE'
    """Phí lũy tiến"""


class TradingFee(BaseModel):
    """
    Thông tin biểu phí phái sinh (áp dụng cho DERIVATIVE)
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='Id chính sách phí phái sinh')
    """Id chính sách phí phái sinh"""

    name: str | MISSING = Field(MISSING, description='Tên chính sách phí')
    """Tên chính sách phí"""

    scope: str | MISSING = Field(MISSING, description='Phạm vi áp dụng')
    """Phạm vi áp dụng"""

    channel: str | MISSING = Field(MISSING, description='Kênh áp dụng')
    """Kênh áp dụng"""

    schema_type: TradingFeeSchemaType | MISSING = Field(
        MISSING,
        alias='schemaType',
        description='Loại biểu phí\nFIXED: Phí cố định\nPROGRESSIVE: Phí lũy tiến',
    )
    """
    Loại biểu phí
    FIXED: Phí cố định
    PROGRESSIVE: Phí lũy tiến
    """

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm áp dụng'
    )
    """Thời điểm áp dụng"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật'
    )
    """Thời điểm cập nhật"""

    fixed_trading_fee: int | MISSING = Field(
        MISSING, alias='fixedTradingFee', description='Phí cố định trên 1 hợp đồng'
    )
    """Phí cố định trên 1 hợp đồng"""

    fixed_daily_close_trading_fee: int | MISSING = Field(
        MISSING,
        alias='fixedDailyCloseTradingFee',
        description='Phí đóng vị thế trong ngày',
    )
    """Phí đóng vị thế trong ngày"""

    progress_trading_fee: list[ProgressiveTradingFee] | MISSING = Field(
        MISSING, alias='progressTradingFee', description='Phí giao dịch lũy tiến'
    )
    """Phí giao dịch lũy tiến"""

    progress_daily_close_trading_fee: (
        list[ProgressiveDailyCloseTradingFee] | MISSING
    ) = Field(
        MISSING,
        alias='progressDailyCloseTradingFee',
        description='Phí đóng vị thế trong ngày lũy tiến',
    )
    """Phí đóng vị thế trong ngày lũy tiến"""


class Account(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: str | MISSING = Field(MISSING, description='Số tiểu khoản')
    """Số tiểu khoản"""

    deal_account: bool | MISSING = Field(
        MISSING, alias='dealAccount', description='Tiểu khoản theo DEAL hoặc không'
    )
    """Tiểu khoản theo DEAL hoặc không"""

    derivative_account: bool | MISSING = Field(
        MISSING, alias='derivativeAccount', description=''
    )
    """"""

    derivative: DerivativeAccount | MISSING = MISSING


class BalancesResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    stock: StockBalance | MISSING = MISSING
    derivative: DerivativeBalance | MISSING = MISSING
    bond: BondBalance | MISSING = MISSING
    egg: EggBalance | MISSING = MISSING


class Data(BaseModel):
    """
    Danh sách quyền chứng khoán của tiểu khoản, được phân loại theo từng loại quyền
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, list[dict[str, Any]]],
    }
    cash_dividend: list[CashDividend] | MISSING = Field(
        MISSING,
        alias='cashDividend',
        description='Danh sách quyền trả cổ tức bằng tiền',
    )
    """Danh sách quyền trả cổ tức bằng tiền"""

    stock_dividend: list[StockDividend] | MISSING = Field(
        MISSING,
        alias='stockDividend',
        description='Danh sách quyền trả cổ tức bằng cổ phiếu',
    )
    """Danh sách quyền trả cổ tức bằng cổ phiếu"""

    stock_bonus: list[StockBonus] | MISSING = Field(
        MISSING, alias='stockBonus', description='Danh sách quyền trả cổ phiếu thưởng'
    )
    """Danh sách quyền trả cổ phiếu thưởng"""

    rights_offering: list[RightsOffering] | MISSING = Field(
        MISSING,
        alias='rightsOffering',
        description='Danh sách quyền mua cổ phiếu phát hành thêm',
    )
    """Danh sách quyền mua cổ phiếu phát hành thêm"""


class CorporateActionHistoryResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    data: Data | MISSING = Field(
        MISSING,
        description='Danh sách quyền chứng khoán của tiểu khoản, được phân loại theo từng loại quyền',
    )
    """Danh sách quyền chứng khoán của tiểu khoản, được phân loại theo từng loại quyền"""

    pagination: PaginationModel | MISSING = MISSING


class LoanPackage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: int | MISSING = Field(MISSING, description='Id gói vay')
    """Id gói vay"""

    name: str | MISSING = Field(MISSING, description='Tên gói vay')
    """Tên gói vay"""

    initial_rate: float | MISSING = Field(
        MISSING, alias='initialRate', description='Tỷ lệ ban đầu'
    )
    """Tỷ lệ ban đầu"""

    maintenance_rate: float | MISSING = Field(
        MISSING, alias='maintenanceRate', description='Tỷ lệ duy trì (call margin)'
    )
    """Tỷ lệ duy trì (call margin)"""

    liquid_rate: float | MISSING = Field(
        MISSING, alias='liquidRate', description='Tỷ lệ xử lý (force sell)'
    )
    """Tỷ lệ xử lý (force sell)"""

    trading_fee: TradingFee | MISSING = Field(MISSING, alias='tradingFee')
    interest_rate: float | MISSING = Field(
        MISSING, alias='interestRate', description='Tỷ lệ lãi vay'
    )
    """Tỷ lệ lãi vay"""

    type: str | MISSING = Field(MISSING, description='Loại gói vay')
    """Loại gói vay"""

    broker_firm_buying_fee_rate: float | MISSING = Field(
        MISSING,
        alias='brokerFirmBuyingFeeRate',
        description='Phí giao dịch chiều mua công ty chứng khoán thu',
    )
    """Phí giao dịch chiều mua công ty chứng khoán thu"""

    broker_firm_selling_fee_rate: float | MISSING = Field(
        MISSING,
        alias='brokerFirmSellingFeeRate',
        description='Phí giao dịch chiều bán công ty chứng khoán thu',
    )
    """Phí giao dịch chiều bán công ty chứng khoán thu"""


class LoanPackagesResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol_type: SymbolType | MISSING = Field(
        MISSING,
        alias='symbolType',
        description='Phân loại mã hợp đồng phái sinh theo thời gian đáo hạn (áp dụng cho DERIVATIVE)\n- VN30F1M: HĐTL chỉ số VN30 1 tháng\n- VN30F2M: HĐTL chỉ số VN30 2 tháng\n- VN30F1Q: HĐTL chỉ số VN30 1 quý\n- VN30F2Q: HĐTL chỉ số VN30 2 quý',
    )
    """
    Phân loại mã hợp đồng phái sinh theo thời gian đáo hạn (áp dụng cho DERIVATIVE)
    - VN30F1M: HĐTL chỉ số VN30 1 tháng
    - VN30F2M: HĐTL chỉ số VN30 2 tháng
    - VN30F1Q: HĐTL chỉ số VN30 1 quý
    - VN30F2Q: HĐTL chỉ số VN30 2 quý
    """

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\n- STOCK: Gói vay giao dịch cơ sở\n- DERIVATIVE: Gói vay giao dịch phái sinh\n- BOND: Gói vay giao dịch trái phiếu',
    )
    """
    Loại thị trường
    - STOCK: Gói vay giao dịch cơ sở
    - DERIVATIVE: Gói vay giao dịch phái sinh
    - BOND: Gói vay giao dịch trái phiếu
    """

    loan_packages: list[LoanPackage] | MISSING = Field(
        MISSING, alias='loanPackages', description='Danh sách gói vay'
    )
    """Danh sách gói vay"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""


class AccountsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    name: str | MISSING = Field(MISSING, description='Họ tên khách hàng')
    """Họ tên khách hàng"""

    custody_code: str | MISSING = Field(
        MISSING, alias='custodyCode', description='Số tài khoản lưu ký tại VSD'
    )
    """Số tài khoản lưu ký tại VSD"""

    investor_id: str | MISSING = Field(
        MISSING, alias='investorId', description='Mã định danh khách hàng tại DNSE'
    )
    """Mã định danh khách hàng tại DNSE"""

    accounts: list[Account] | MISSING = MISSING
