# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Dict

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from pydantic.experimental.missing_sentinel import MISSING


class ConditionOperator(StrEnum):
    """
    Điều kiện so sánh để kích hoạt lệnh dừng.

    - `>=`: Kích hoạt khi giá thị trường lớn hơn hoặc bằng giá điều kiện
    - `<=`: Kích hoạt khi giá thị trường nhỏ hơn hoặc bằng giá điều kiện
    """

    GREATER_THAN_OR_EQUAL = '>='
    """Lớn hơn hoặc bằng"""

    LESS_THAN_OR_EQUAL = '<='
    """Nhỏ hơn hoặc bằng"""


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    status: int = Field(..., description='Mã HTTP.')
    """Mã HTTP."""

    code: str = Field(..., description='Mã lỗi DNSE.')
    """Mã lỗi DNSE."""

    message: str = Field(..., description='Thông điệp lỗi.')
    """Thông điệp lỗi."""


class MarketType(StrEnum):
    """
    Loại thị trường.

    - `STOCK`: Giao dịch cơ sở
    - `DERIVATIVE`: Giao dịch phái sinh
    - `BOND`: Giao dịch trái phiếu
    """

    STOCK = 'STOCK'
    """Giao dịch cơ sở"""

    DERIVATIVE = 'DERIVATIVE'
    """Giao dịch phái sinh"""

    BOND = 'BOND'
    """Giao dịch trái phiếu"""


class OrderCategory(StrEnum):
    """
    Phân loại lệnh.

    - `NORMAL`: Lệnh thường
    - `STOP`: Lệnh dừng có điều kiện
    - `OCO`: Lệnh OCO phái sinh
    - `CONDITIONAL`: Lệnh điều kiện
    """

    NORMAL = 'NORMAL'
    """Lệnh thường"""

    STOP = 'STOP'
    """Lệnh dừng có điều kiện"""

    OCO = 'OCO'
    """Lệnh OCO phái sinh"""

    CONDITIONAL = 'CONDITIONAL'
    """Lệnh điều kiện"""


class OrderDurationType(StrEnum):
    """
    Thời hạn hiệu lực của lệnh.

    - `GTD`: Có hiệu lực đến ngày, giờ chỉ định
    - `DAY`: Có hiệu lực trong ngày
    """

    GTD = 'GTD'
    """Có hiệu lực đến ngày, giờ chỉ định"""

    DAY = 'DAY'
    """Có hiệu lực trong ngày"""


class OrderSide(StrEnum):
    """
    Chiều đặt lệnh hoặc vị thế.

    - `NB`: Mua
    - `NS`: Bán
    """

    BUY = 'NB'
    """Mua"""

    SELL = 'NS'
    """Bán"""


class OrderStatus(StrEnum):
    """
    Trạng thái lệnh.

    - `Pending`: Chờ gửi
    - `PendingNew`: Chờ gửi
    - `New`: Chờ khớp hoặc chờ kích hoạt
    - `PendingReplace`: Chờ sửa
    - `PendingCancel`: Chờ hủy
    - `PartiallyFilled`: Khớp một phần
    - `Filled`: Khớp toàn bộ
    - `Canceled`: Đã hủy
    - `Rejected`: Bị từ chối
    - `Expired`: Hết hạn trong phiên
    - `DoneForDay`: Được giải tỏa do không khớp trong phiên
    """

    PENDING = 'Pending'
    """Chờ gửi"""

    PENDING_NEW = 'PendingNew'
    """Chờ gửi"""

    NEW = 'New'
    """Chờ khớp hoặc chờ kích hoạt"""

    PENDING_REPLACE = 'PendingReplace'
    """Chờ sửa"""

    PENDING_CANCEL = 'PendingCancel'
    """Chờ hủy"""

    PARTIALLY_FILLED = 'PartiallyFilled'
    """Khớp một phần"""

    FILLED = 'Filled'
    """Khớp toàn bộ"""

    CANCELED = 'Canceled'
    """Đã hủy"""

    REJECTED = 'Rejected'
    """Bị từ chối"""

    EXPIRED = 'Expired'
    """Hết hạn trong phiên"""

    DONE_FOR_DAY = 'DoneForDay'
    """Được giải tỏa do không khớp trong phiên"""


class OrderType(StrEnum):
    """
    Loại lệnh.

    - `LO`: Lệnh giới hạn
    - `MOK`: Lệnh thị trường khớp toàn bộ hoặc hủy
    - `MAK`: Lệnh thị trường khớp một phần và hủy phần còn lại
    - `MTL`: Lệnh thị trường khớp theo giá thị trường
    - `ATO`: Lệnh phiên định kỳ mở cửa
    - `ATC`: Lệnh phiên định kỳ đóng cửa
    - `PLO`: Lệnh khớp lệnh sau giờ
    """

    LIMIT = 'LO'
    """Lệnh giới hạn"""

    MARKET_OR_CANCEL = 'MOK'
    """Lệnh thị trường khớp toàn bộ hoặc hủy"""

    MARKET_AND_CANCEL = 'MAK'
    """Lệnh thị trường khớp một phần và hủy phần còn lại"""

    MARKET_TO_LIMIT = 'MTL'
    """Lệnh thị trường khớp theo giá thị trường"""

    AT_OPEN = 'ATO'
    """Lệnh phiên định kỳ mở cửa"""

    AT_CLOSE = 'ATC'
    """Lệnh phiên định kỳ đóng cửa"""

    POST_CLOSE = 'PLO'
    """Lệnh khớp lệnh sau giờ"""


class PnlOrderMethod(StrEnum):
    """
    Phương thức đặt lệnh khi điều kiện chốt lời hoặc cắt lỗ được kích hoạt.

    - `FASTEST`: Đặt lệnh với giá trần hoặc sàn
    - `DELTA_PRICE`: Đặt lệnh theo biên độ giá so với giá kích hoạt
    """

    FASTEST = 'FASTEST'
    """Đặt lệnh với giá trần hoặc sàn"""

    DELTA_PRICE = 'DELTA_PRICE'
    """Đặt lệnh theo biên độ giá so với giá kích hoạt"""


class PnlStrategy(StrEnum):
    """
    Chiến lược kích hoạt chốt lời hoặc cắt lỗ.

    - `PNL_RATE`: Kích hoạt theo tỷ lệ phần trăm
    - `DELTA_PRICE`: Kích hoạt theo mức chênh lệch giá
    """

    PNL_RATE = 'PNL_RATE'
    """Kích hoạt theo tỷ lệ phần trăm"""

    DELTA_PRICE = 'DELTA_PRICE'
    """Kích hoạt theo mức chênh lệch giá"""


class PnlConfig(BaseModel):
    """
    Cấu hình chốt lời (Take Profit)
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    enabled: bool | MISSING = Field(MISSING, description='Bật/tắt chức năng chốt lời')
    """Bật/tắt chức năng chốt lời"""

    strategy: PnlStrategy | MISSING = Field(
        MISSING,
        description='Chiến lược kích hoạt chốt lời \n  - PNL_RATE: Kích hoạt theo tỷ lệ %\n  - DELTA_PRICE: Kích hoạt theo mức chênh lệch giá                       ',
    )
    """
    Chiến lược kích hoạt chốt lời 
      - PNL_RATE: Kích hoạt theo tỷ lệ %
      - DELTA_PRICE: Kích hoạt theo mức chênh lệch giá                       
    """

    rate: float | MISSING = Field(
        MISSING,
        description='Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị phải lớn hơn 0',
    )
    """Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị phải lớn hơn 0"""

    delta_price: float | MISSING = Field(
        MISSING,
        alias='deltaPrice',
        description='Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0',
    )
    """Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0"""

    order_method: PnlOrderMethod | MISSING = Field(
        MISSING,
        alias='orderMethod',
        description='Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.\n  - FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua\n  - DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt ',
    )
    """
    Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.
      - FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua
      - DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt 
    """

    order_delta_price: float | MISSING = Field(
        MISSING,
        alias='orderDeltaPrice',
        description='Biên độ giá đặt lệnh so với giá kích hoạt khi orderMethod = DELTA_PRICE. Có thể là số âm, số dương hoặc bằng 0',
    )
    """Biên độ giá đặt lệnh so với giá kích hoạt khi orderMethod = DELTA_PRICE. Có thể là số âm, số dương hoặc bằng 0"""

    trailing_enabled: bool | MISSING = Field(
        MISSING,
        alias='trailingEnabled',
        description='Bật/tắt cơ chế Trailing Stop. Lưu ý cơ chế này chỉ hoạt động khi chức năng cắt lỗ được bật',
    )
    """Bật/tắt cơ chế Trailing Stop. Lưu ý cơ chế này chỉ hoạt động khi chức năng cắt lỗ được bật"""


class TakeProfit(BaseModel):
    """
    Cấu hình chốt lời (Take Profit)
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    enabled: bool | MISSING = Field(MISSING, description='Bật/tắt chức năng chốt lời')
    """Bật/tắt chức năng chốt lời"""

    strategy: PnlStrategy | MISSING = Field(
        MISSING,
        description='Chiến lược kích hoạt chốt lời\n- PNL_RATE: Kích hoạt theo tỷ lệ %\n- DELTA_PRICE: Kích hoạt theo mức chênh lệch giá',
    )
    """
    Chiến lược kích hoạt chốt lời
    - PNL_RATE: Kích hoạt theo tỷ lệ %
    - DELTA_PRICE: Kích hoạt theo mức chênh lệch giá
    """

    rate: float | MISSING = Field(
        MISSING,
        description='Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị phải lớn hơn 0',
    )
    """Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị phải lớn hơn 0"""

    delta_price: float | MISSING = Field(
        MISSING,
        alias='deltaPrice',
        description='Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0',
    )
    """Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0"""

    order_method: PnlOrderMethod | MISSING = Field(
        MISSING,
        alias='orderMethod',
        description='Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.\n- FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua\n- DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt',
    )
    """
    Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.
    - FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua
    - DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt
    """

    order_delta_price: int | MISSING = Field(
        MISSING,
        alias='orderDeltaPrice',
        description='Biên độ giá đặt lệnh khi orderMethod = DELTA_PRICE. Bằng 0 khi orderMethod = FASTEST',
    )
    """Biên độ giá đặt lệnh khi orderMethod = DELTA_PRICE. Bằng 0 khi orderMethod = FASTEST"""


class StopLoss(BaseModel):
    """
    Cấu hình cắt lỗ (Stop Loss)
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    enabled: bool | MISSING = Field(MISSING, description='Bật/tắt chức năng cắt lỗ')
    """Bật/tắt chức năng cắt lỗ"""

    strategy: PnlStrategy | MISSING = Field(
        MISSING,
        description='Chiến lược kích hoạt cắt lỗ\n- PNL_RATE: Kích hoạt theo tỷ lệ %\n- DELTA_PRICE: Kích hoạt theo mức chênh lệch giá.',
    )
    """
    Chiến lược kích hoạt cắt lỗ
    - PNL_RATE: Kích hoạt theo tỷ lệ %
    - DELTA_PRICE: Kích hoạt theo mức chênh lệch giá.
    """

    rate: float | MISSING = Field(
        MISSING,
        description='Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị hợp lệ trong khoảng [-1.0, 0)',
    )
    """Tỷ lệ % so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = PNL_RATE. Giá trị hợp lệ trong khoảng [-1.0, 0)"""

    delta_price: float | MISSING = Field(
        MISSING,
        alias='deltaPrice',
        description='Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0',
    )
    """Mức chênh lệch giá so với giá hòa vốn, dùng để kích hoạt chốt lời khi strategy = DELTA_PRICE. Giá trị phải lớn hơn 0"""

    order_method: PnlOrderMethod | MISSING = Field(
        MISSING,
        alias='orderMethod',
        description='Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.\n- FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua\n- DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt',
    )
    """
    Phương thức đặt lệnh khi điều kiện chốt lời được kích hoạt.
    - FASTEST: Lệnh khớp ngay với giá đặt là giá trần/sàn tùy theo chiều vị thế Bán/Mua
    - DELTA_PRICE: Lệnh đặt theo biên độ giá so với giá kích hoạt
    """

    order_delta_price: float | MISSING = Field(
        MISSING,
        alias='orderDeltaPrice',
        description='Biên độ giá đặt lệnh khi orderMethod = DELTA_PRICE. Bằng 0 khi orderMethod = FASTEST',
    )
    """Biên độ giá đặt lệnh khi orderMethod = DELTA_PRICE. Bằng 0 khi orderMethod = FASTEST"""

    trailing_enabled: bool | MISSING = Field(
        MISSING,
        alias='trailingEnabled',
        description='Bật/tắt cơ chế Trailing Stop. Lưu ý cơ chế này chỉ hoạt động khi chức năng cắt lỗ được bật',
    )
    """Bật/tắt cơ chế Trailing Stop. Lưu ý cơ chế này chỉ hoạt động khi chức năng cắt lỗ được bật"""


class Configs(BaseModel):
    """
    Cấu hình chốt lời và cắt lỗ của vị thế
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, PnlConfig],
    }
    take_profit: TakeProfit | MISSING = Field(
        MISSING, alias='takeProfit', description='Cấu hình chốt lời (Take Profit)'
    )
    """Cấu hình chốt lời (Take Profit)"""

    stop_loss: StopLoss | MISSING = Field(
        MISSING, alias='stopLoss', description='Cấu hình cắt lỗ (Stop Loss)'
    )
    """Cấu hình cắt lỗ (Stop Loss)"""


class PnlConfigsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản chứng khoán'
    )
    """Số tiểu khoản chứng khoán"""

    position_id: int | MISSING = Field(
        MISSING, alias='positionId', description='ID vị thế'
    )
    """ID vị thế"""

    configs: Configs | MISSING = Field(
        MISSING, description='Cấu hình chốt lời và cắt lỗ của vị thế'
    )
    """Cấu hình chốt lời và cắt lỗ của vị thế"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm cấu hình được tạo'
    )
    """Thời điểm cấu hình được tạo"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING,
        alias='modifiedDate',
        description='Thời điểm cập nhật cấu hình gần nhất',
    )
    """Thời điểm cập nhật cấu hình gần nhất"""


class ConfigsModel(BaseModel):
    """
    Cấu hình chốt lời và cắt lỗ của tiểu khoản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    take_profit: PnlConfig | MISSING = Field(MISSING, alias='takeProfit')
    stop_loss: PnlConfig | MISSING = Field(MISSING, alias='stopLoss')


class AccountPnlConfigsResponse(BaseModel):
    """
    Cấu hình chốt lời, cắt lỗ của tiểu khoản.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản chứng khoán.'
    )
    """Số tiểu khoản chứng khoán."""

    configs: ConfigsModel | MISSING = Field(
        MISSING, description='Cấu hình chốt lời và cắt lỗ của tiểu khoản.'
    )
    """Cấu hình chốt lời và cắt lỗ của tiểu khoản."""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm cấu hình được tạo.'
    )
    """Thời điểm cấu hình được tạo."""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING,
        alias='modifiedDate',
        description='Thời điểm cập nhật cấu hình gần nhất.',
    )
    """Thời điểm cập nhật cấu hình gần nhất."""


class PlaceOrderResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    id: str | MISSING = Field(MISSING, description='Id lệnh giao dịch')
    """Id lệnh giao dịch"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    side: OrderSide | MISSING = Field(
        MISSING, description='Chiều đặt lệnh\n- NB: Mua\n- NS: Bán'
    )
    """
    Chiều đặt lệnh
    - NB: Mua
    - NS: Bán
    """

    order_type: OrderType | MISSING = Field(
        MISSING,
        alias='orderType',
        description='Loại lệnh\n- LO: Lệnh giới hạn\n- MOK/MAK/MTL: Lệnh thị trường\n- ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa\n- PLO: Lệnh khớp lệnh sau giờ',
    )
    """
    Loại lệnh
    - LO: Lệnh giới hạn
    - MOK/MAK/MTL: Lệnh thị trường
    - ATO/ATC: Lệnh phiên định kỳ mở cửa/đóng cửa
    - PLO: Lệnh khớp lệnh sau giờ
    """

    order_status: OrderStatus | MISSING = Field(
        MISSING,
        alias='orderStatus',
        description='Trạng thái lệnh khi đặt thành công\n- PendingNew: Chờ gửi (lệnh thường NORMAL)\n- New: Chờ kích hoạt (lệnh STOP/OCO)',
    )
    """
    Trạng thái lệnh khi đặt thành công
    - PendingNew: Chờ gửi (lệnh thường NORMAL)
    - New: Chờ kích hoạt (lệnh STOP/OCO)
    """

    price: float | MISSING = Field(MISSING, description='Giá đặt')
    """Giá đặt"""

    average_price: float | MISSING = Field(MISSING, alias='averagePrice')
    quantity: int | MISSING = Field(MISSING, description='Khối lượng đặt')
    """Khối lượng đặt"""

    fill_quantity: int | MISSING = Field(MISSING, alias='fillQuantity')
    canceled_quantity: int | MISSING = Field(MISSING, alias='canceledQuantity')
    leave_quantity: int | MISSING = Field(MISSING, alias='leaveQuantity')
    account_no: str | MISSING = Field(
        MISSING, alias='accountNo', description='Số tiểu khoản'
    )
    """Số tiểu khoản"""

    market_type: MarketType | MISSING = Field(
        MISSING,
        alias='marketType',
        description='Loại thị trường\n- STOCK: Giao dịch cơ sở\n- DERIVATIVE: Giao dịch phái sinh\n- BOND: Giao dịch trái phiếu',
    )
    """
    Loại thị trường
    - STOCK: Giao dịch cơ sở
    - DERIVATIVE: Giao dịch phái sinh
    - BOND: Giao dịch trái phiếu
    """

    order_category: OrderCategory | MISSING = Field(
        MISSING,
        alias='orderCategory',
        description='Phân loại lệnh\n- NORMAL: Lệnh thường\n- STOP: Lệnh dừng có điều kiện\n- OCO: Lệnh OCO phái sinh',
    )
    """
    Phân loại lệnh
    - NORMAL: Lệnh thường
    - STOP: Lệnh dừng có điều kiện
    - OCO: Lệnh OCO phái sinh
    """

    trans_date: date | MISSING = Field(
        MISSING, alias='transDate', description='Ngày giao dịch'
    )
    """Ngày giao dịch"""

    created_date: AwareDatetime | MISSING = Field(
        MISSING, alias='createdDate', description='Thời điểm tạo lệnh'
    )
    """Thời điểm tạo lệnh"""

    modified_date: AwareDatetime | MISSING = Field(
        MISSING, alias='modifiedDate', description='Thời điểm cập nhật lệnh'
    )
    """Thời điểm cập nhật lệnh"""

    loan_package_id: int | MISSING = Field(
        MISSING, alias='loanPackageId', description='ID gói vay'
    )
    """ID gói vay"""


class SymbolType(StrEnum):
    """
    Phân loại mã hợp đồng phái sinh theo thời gian đáo hạn.

    - ``: Không áp dụng cho mã không phải hợp đồng phái sinh
    - `VN30F1M`: HĐTL chỉ số VN30 1 tháng
    - `VN30F2M`: HĐTL chỉ số VN30 2 tháng
    - `VN30F1Q`: HĐTL chỉ số VN30 1 quý
    - `VN30F2Q`: HĐTL chỉ số VN30 2 quý
    """

    UNSPECIFIED = ''
    """Không áp dụng"""

    VN30_F1_M = 'VN30F1M'
    """HĐTL chỉ số VN30 1 tháng"""

    VN30_F2_M = 'VN30F2M'
    """HĐTL chỉ số VN30 2 tháng"""

    VN30_F1_Q = 'VN30F1Q'
    """HĐTL chỉ số VN30 1 quý"""

    VN30_F2_Q = 'VN30F2Q'
    """HĐTL chỉ số VN30 2 quý"""
