# generated by datamodel-codegen:
#   filename:  input.openapi.json

from __future__ import annotations

from datetime import date
from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from pydantic.experimental.missing_sentinel import MISSING

from .common import SymbolType


class OhlcResponse(BaseModel):
    """
    Dữ liệu biểu đồ nến (OHLCV) theo từng khoảng thời gian.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    t: list[int] = Field(..., description='Danh sách thời gian nến')
    """Danh sách thời gian nến"""

    o: list[float] = Field(
        ..., description='Danh sách giá mở cửa của nến theo thời gian tương ứng'
    )
    """Danh sách giá mở cửa của nến theo thời gian tương ứng"""

    h: list[float] = Field(
        ..., description='Danh sách giá cao nhất trong nến theo thời gian tương ứng'
    )
    """Danh sách giá cao nhất trong nến theo thời gian tương ứng"""

    l: list[float] = Field(
        ..., description='Danh sách giá thấp nhất trong nến theo thời gian tương ứng'
    )
    """Danh sách giá thấp nhất trong nến theo thời gian tương ứng"""

    c: list[float] = Field(
        ..., description='Danh sách giá đóng cửa của nến theo thời gian tương ứng'
    )
    """Danh sách giá đóng cửa của nến theo thời gian tương ứng"""

    v: list[int] = Field(
        ..., description='Danh sách khối lượng giao dịch theo thời gian tương ứng'
    )
    """Danh sách khối lượng giao dịch theo thời gian tương ứng"""

    next_time: int = Field(
        ...,
        alias='nextTime',
        description='Timestamp của cây nến tiếp theo (nếu có), 0 nếu không còn',
    )
    """Timestamp của cây nến tiếp theo (nếu có), 0 nếu không còn"""


class QuoteBidLevel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: float | MISSING = Field(MISSING, description='Giá đặt mua')
    """Giá đặt mua"""

    quantity: int | MISSING = Field(
        MISSING, description='Khối lượng đặt mua tại mức giá tương ứng'
    )
    """Khối lượng đặt mua tại mức giá tương ứng"""


class QuoteBidLevelLatest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: float | MISSING = Field(MISSING, description='Giá đặt mua')
    """Giá đặt mua"""

    quantity: int | MISSING = Field(
        MISSING, description='Khối lượng đặt mua tại mức giá tương ứng'
    )
    """Khối lượng đặt mua tại mức giá tương ứng"""


class QuoteOfferLevel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: float | MISSING = Field(MISSING, description='Giá đặt bán')
    """Giá đặt bán"""

    quantity: int | MISSING = Field(
        MISSING, description='Khối lượng đặt bán tại mức giá tương ứng'
    )
    """Khối lượng đặt bán tại mức giá tương ứng"""


class QuoteOfferLevelLatest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    price: float | MISSING = Field(MISSING, description='Giá đặt bán')
    """Giá đặt bán"""

    quantity: int | MISSING = Field(
        MISSING, description='Khối lượng đặt bán tại mức giá tương ứng'
    )
    """Khối lượng đặt bán tại mức giá tương ứng"""


class WorkingDates(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    working_dates: list[date] | MISSING = Field(MISSING, alias='workingDates')


class MarketIndexHistoryItem(BaseModel):
    """
    Một bản ghi lịch sử chỉ số thị trường.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    index_name: str | MISSING = Field(
        MISSING, alias='indexName', description='Tên chỉ số thị trường.'
    )
    """Tên chỉ số thị trường."""

    value_indexes: float | MISSING = Field(
        MISSING, alias='valueIndexes', description='Giá trị chỉ số.'
    )
    """Giá trị chỉ số."""

    changed_value: float | MISSING = Field(
        MISSING,
        alias='changedValue',
        description='Giá trị tăng hoặc giảm so với giá tham chiếu.',
    )
    """Giá trị tăng hoặc giảm so với giá tham chiếu."""

    changed_ratio: float | MISSING = Field(
        MISSING,
        alias='changedRatio',
        description='Tỷ lệ phần trăm tăng hoặc giảm so với giá tham chiếu.',
    )
    """Tỷ lệ phần trăm tăng hoặc giảm so với giá tham chiếu."""

    fluctuation_steadiness_issue_count: int | MISSING = Field(
        MISSING,
        alias='fluctuationSteadinessIssueCount',
        description='Số lượng mã có giá không đổi.',
    )
    """Số lượng mã có giá không đổi."""

    fluctuation_down_issue_count: int | MISSING = Field(
        MISSING,
        alias='fluctuationDownIssueCount',
        description='Số lượng mã có giá giảm.',
    )
    """Số lượng mã có giá giảm."""

    fluctuation_up_issue_count: int | MISSING = Field(
        MISSING, alias='fluctuationUpIssueCount', description='Số lượng mã có giá tăng.'
    )
    """Số lượng mã có giá tăng."""

    fluctuation_lower_limit_issue_count: int | MISSING = Field(
        MISSING,
        alias='fluctuationLowerLimitIssueCount',
        description='Số lượng mã giảm sàn.',
    )
    """Số lượng mã giảm sàn."""

    fluctuation_upper_limit_issue_count: int | MISSING = Field(
        MISSING,
        alias='fluctuationUpperLimitIssueCount',
        description='Số lượng mã tăng trần.',
    )
    """Số lượng mã tăng trần."""

    fluctuation_down_issue_volume: int | MISSING = Field(
        MISSING,
        alias='fluctuationDownIssueVolume',
        description='Tổng khối lượng giao dịch các mã có giá giảm.',
    )
    """Tổng khối lượng giao dịch các mã có giá giảm."""

    fluctuation_up_issue_volume: int | MISSING = Field(
        MISSING,
        alias='fluctuationUpIssueVolume',
        description='Tổng khối lượng giao dịch các mã có giá tăng.',
    )
    """Tổng khối lượng giao dịch các mã có giá tăng."""

    fluctuation_steadiness_issue_volume: int | MISSING = Field(
        MISSING,
        alias='fluctuationSteadinessIssueVolume',
        description='Tổng khối lượng giao dịch các mã có giá không đổi.',
    )
    """Tổng khối lượng giao dịch các mã có giá không đổi."""

    currency_code: str | MISSING = Field(
        MISSING, alias='currencyCode', description='Đơn vị tiền tệ.'
    )
    """Đơn vị tiền tệ."""

    index_type_code: str | MISSING = Field(
        MISSING, alias='indexTypeCode', description='Mã loại chỉ số.'
    )
    """Mã loại chỉ số."""

    lowest_value_indexes: float | MISSING = Field(
        MISSING,
        alias='lowestValueIndexes',
        description='Giá trị thấp nhất trong phiên.',
    )
    """Giá trị thấp nhất trong phiên."""

    highest_value_indexes: float | MISSING = Field(
        MISSING,
        alias='highestValueIndexes',
        description='Giá trị cao nhất trong phiên.',
    )
    """Giá trị cao nhất trong phiên."""

    prior_value_indexes: float | MISSING = Field(
        MISSING, alias='priorValueIndexes', description='Giá trị tham chiếu.'
    )
    """Giá trị tham chiếu."""

    contauct_acc_trd_val: float | MISSING = Field(
        MISSING,
        alias='contauctAccTrdVal',
        description='Tổng giá trị giao dịch theo phương thức khớp lệnh.',
    )
    """Tổng giá trị giao dịch theo phương thức khớp lệnh."""

    contauct_acc_trd_vol: int | MISSING = Field(
        MISSING,
        alias='contauctAccTrdVol',
        description='Tổng khối lượng giao dịch theo phương thức khớp lệnh.',
    )
    """Tổng khối lượng giao dịch theo phương thức khớp lệnh."""

    blk_trd_acc_trd_val: float | MISSING = Field(
        MISSING,
        alias='blkTrdAccTrdVal',
        description='Tổng giá trị giao dịch theo phương thức thỏa thuận.',
    )
    """Tổng giá trị giao dịch theo phương thức thỏa thuận."""

    blk_trd_acc_trd_vol: int | MISSING = Field(
        MISSING,
        alias='blkTrdAccTrdVol',
        description='Tổng khối lượng giao dịch theo phương thức thỏa thuận.',
    )
    """Tổng khối lượng giao dịch theo phương thức thỏa thuận."""

    gross_trade_amount: float | MISSING = Field(
        MISSING,
        alias='grossTradeAmount',
        description='Tổng giá trị giao dịch trong ngày.',
    )
    """Tổng giá trị giao dịch trong ngày."""

    total_volume_traded: int | MISSING = Field(
        MISSING,
        alias='totalVolumeTraded',
        description='Tổng khối lượng giao dịch trong ngày.',
    )
    """Tổng khối lượng giao dịch trong ngày."""

    market_index_class: int | str | MISSING = Field(
        MISSING, alias='marketIndexClass', description='Phân loại chỉ số.'
    )
    """Phân loại chỉ số."""

    market_id: str | MISSING = Field(
        MISSING, alias='marketId', description='Mã thị trường.'
    )
    """Mã thị trường."""

    trading_session_id: str | MISSING = Field(
        MISSING, alias='tradingSessionId', description='Mã phiên giao dịch.'
    )
    """Mã phiên giao dịch."""

    time: str | MISSING = Field(
        MISSING,
        description='Thời điểm ghi nhận dữ liệu theo định dạng DNSE `YYYY-MM-DD HH:mm:ss.SSS`.',
        pattern='^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?$',
    )
    """Thời điểm ghi nhận dữ liệu theo định dạng DNSE `YYYY-MM-DD HH:mm:ss.SSS`."""


class MarketIndexHistoryResponse(BaseModel):
    """
    Danh sách dữ liệu lịch sử chỉ số thị trường.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[MarketIndexHistoryItem] | MISSING = Field(
        MISSING, description='Danh sách bản ghi lịch sử chỉ số.'
    )
    """Danh sách bản ghi lịch sử chỉ số."""

    next_page_token: str | MISSING = Field(
        MISSING, alias='nextPageToken', description='Token dùng để lấy trang tiếp theo.'
    )
    """Token dùng để lấy trang tiếp theo."""


class BoardId(StrEnum):
    """
    Mã định danh bảng giao dịch.

    - `UNSPECIFIED`: Không xác định
    - `AL`: Tất cả bảng
    - `G1`: Lô chẵn
    - `G3`: Board phiên sau giờ (PLO)
    - `G4`: Lô lẻ
    - `T1`: Thỏa thuận lô chẵn 9h-14h45
    - `T3`: Thỏa thuận lô chẵn 14h45-15h
    - `T4`: Thỏa thuận lô lẻ 9h-14h45
    - `T6`: Thỏa thuận lô lẻ 14h45-15h
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    AL = 'AL'
    """Tất cả bảng"""

    G1 = 'G1'
    """Lô chẵn"""

    G3 = 'G3'
    """Board phiên sau giờ (PLO)"""

    G4 = 'G4'
    """Lô lẻ"""

    T1 = 'T1'
    """Thỏa thuận lô chẵn 9h-14h45"""

    T3 = 'T3'
    """Thỏa thuận lô chẵn 14h45-15h"""

    T4 = 'T4'
    """Thỏa thuận lô lẻ 9h-14h45"""

    T6 = 'T6'
    """Thỏa thuận lô lẻ 14h45-15h"""


class MarketId(StrEnum):
    """
    Mã thị trường.

    - `UNSPECIFIED`: Không xác định
    - `DVX`: Phái sinh sàn HNX
    - `HCX`: Trái phiếu doanh nghiệp sàn HNX
    - `STO`: Cổ phiếu sàn HOSE
    - `STX`: Cổ phiếu sàn HNX
    - `UPX`: Cổ phiếu sàn Upcom
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    DVX = 'DVX'
    """Phái sinh sàn HNX"""

    HCX = 'HCX'
    """Trái phiếu doanh nghiệp sàn HNX"""

    STO = 'STO'
    """Cổ phiếu sàn HOSE"""

    STX = 'STX'
    """Cổ phiếu sàn HNX"""

    UPX = 'UPX'
    """Cổ phiếu sàn Upcom"""


class ProductGrpId(StrEnum):
    """
    Nhóm sản phẩm theo thị trường.

    - `UNSPECIFIED`: Không xác định
    - `FBX`: Hợp đồng tương lai Trái phiếu
    - `FIO`: Hợp đồng tương lai Chỉ số
    - `HCX`: Trái phiếu Doanh nghiệp HNX
    - `STO`: Cổ phiếu sàn HOSE
    - `STX`: Cổ phiếu sàn HNX
    - `UPX`: Cổ phiếu sàn Upcom
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    FBX = 'FBX'
    """Hợp đồng tương lai Trái phiếu"""

    FIO = 'FIO'
    """Hợp đồng tương lai Chỉ số"""

    HCX = 'HCX'
    """Trái phiếu Doanh nghiệp HNX"""

    STO = 'STO'
    """Cổ phiếu sàn HOSE"""

    STX = 'STX'
    """Cổ phiếu sàn HNX"""

    UPX = 'UPX'
    """Cổ phiếu sàn Upcom"""


class SecurityGroupId(StrEnum):
    """
    Định danh nhóm chứng khoán.

    - `UNSPECIFIED`: Không xác định
    - `BS`: Trái phiếu doanh nghiệp
    - `EF`: Quỹ ETF
    - `EW`: Chứng quyền
    - `FU`: Hợp đồng tương lai
    - `SR`: Quyền mua
    - `ST`: Cổ phiếu
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    BS = 'BS'
    """Trái phiếu doanh nghiệp"""

    EF = 'EF'
    """Quỹ ETF"""

    EW = 'EW'
    """Chứng quyền"""

    FU = 'FU'
    """Hợp đồng tương lai"""

    SR = 'SR'
    """Quyền mua"""

    ST = 'ST'
    """Cổ phiếu"""


class SecurityStatus(StrEnum):
    """
    Trạng thái của mã chứng khoán.

    - `HALT`: Ngừng giao dịch
    - `NO_HALT`: Không ngừng giao dịch
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    HALT = 'HALT'
    """Ngừng giao dịch"""

    NO_HALT = 'NO_HALT'
    """Không ngừng giao dịch"""


class SymbolAdminStatusCode(StrEnum):
    """
    Trạng thái quản lý hành chính mã chứng khoán.

    - `UNSPECIFIED`: Không xác định
    - `CR`: Kiểm soát và hạn chế giao dịch
    - `CTR`: Kiểm soát
    - `NRM`: Bình thường
    - `RES`: Hạn chế giao dịch
    - `WFR`: Cảnh báo do vi phạm BCTC
    - `WID`: Cảnh báo do vi phạm CBTT
    - `WOV`: Cảnh báo vi phạm khác
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    CR = 'CR'
    """Kiểm soát và hạn chế giao dịch"""

    CTR = 'CTR'
    """Kiểm soát"""

    NRM = 'NRM'
    """Bình thường"""

    RES = 'RES'
    """Hạn chế giao dịch"""

    WFR = 'WFR'
    """Cảnh báo do vi phạm BCTC"""

    WID = 'WID'
    """Cảnh báo do vi phạm CBTT"""

    WOV = 'WOV'
    """Cảnh báo vi phạm khác"""


class SymbolTradingMethodStatusCode(StrEnum):
    """
    Trạng thái cơ chế giao dịch mã chứng khoán.

    - `UNSPECIFIED`: Không xác định
    - `NRM`: Bình thường
    - `NWE`: Niêm yết mới biên độ đặc biệt
    - `NWN`: Niêm yết mới biên độ thường
    - `SLS`: Giao dịch đặc biệt sau halt
    - `SNE`: Giao dịch đặc biệt
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    NRM = 'NRM'
    """Bình thường"""

    NWE = 'NWE'
    """Niêm yết mới biên độ đặc biệt"""

    NWN = 'NWN'
    """Niêm yết mới biên độ thường"""

    SLS = 'SLS'
    """Giao dịch đặc biệt sau halt"""

    SNE = 'SNE'
    """Giao dịch đặc biệt"""


class SymbolTradingSanctionStatusCode(StrEnum):
    """
    Tình trạng giao dịch của mã chứng khoán.

    - `UNSPECIFIED`: Không xác định
    - `NRM`: Bình thường
    - `SUS`: Tạm ngừng
    - `DTL`: Hủy niêm yết chuyển sàn
    - `TFR`: Ngưng giao dịch do hạn chế
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    NRM = 'NRM'
    """Bình thường"""

    SUS = 'SUS'
    """Tạm ngừng"""

    DTL = 'DTL'
    """Hủy niêm yết chuyển sàn"""

    TFR = 'TFR'
    """Ngưng giao dịch do hạn chế"""


class MarketIndex(StrEnum):
    """
    Tên chỉ số thị trường.

    - `VNINDEX`: Chỉ số sàn HOSE
    - `HNX`: Chỉ số sàn HNX
    - `HNX30`: Chỉ số Top 30 cổ phiếu sàn HNX
    - `VN30`: Chỉ số Top 30 cổ phiếu sàn HOSE
    - `VN100`: Chỉ số Top 100 cổ phiếu sàn HOSE
    - `VNXALLSHARE`: Chỉ số các cổ phiếu chọn lọc sàn HOSE
    - `UPCOM`: Chỉ số sàn UPCOM
    - `VNMITECH`: Chỉ số nhóm cổ phiếu công nghệ
    - `VN50GROWTH`: Chỉ số nhóm 50 cổ phiếu tăng trưởng sàn HOSE
    - `VNDIVIDEND`: Chỉ số nhóm cổ phiếu có tỷ suất cổ tức tăng trưởng
    """

    VNINDEX = 'VNINDEX'
    """Chỉ số sàn HOSE"""

    HNX = 'HNX'
    """Chỉ số sàn HNX"""

    HNX30 = 'HNX30'
    """Chỉ số Top 30 cổ phiếu sàn HNX"""

    VN30 = 'VN30'
    """Chỉ số Top 30 cổ phiếu sàn HOSE"""

    VN100 = 'VN100'
    """Chỉ số Top 100 cổ phiếu sàn HOSE"""

    VNXALLSHARE = 'VNXALLSHARE'
    """Chỉ số các cổ phiếu chọn lọc sàn HOSE"""

    UPCOM = 'UPCOM'
    """Chỉ số sàn UPCOM"""

    VNMITECH = 'VNMITECH'
    """Chỉ số nhóm cổ phiếu công nghệ"""

    VN50_GROWTH = 'VN50GROWTH'
    """Chỉ số nhóm 50 cổ phiếu tăng trưởng sàn HOSE"""

    VNDIVIDEND = 'VNDIVIDEND'
    """Chỉ số nhóm cổ phiếu có tỷ suất cổ tức tăng trưởng"""


class Type(StrEnum):
    """
    Loại nhóm thị trường.

    - `STOCK`: Cổ phiếu
    - `DERIVATIVE`: Phái sinh
    - `INDEX`: Chỉ số
    """

    STOCK = 'STOCK'
    """Cổ phiếu"""

    DERIVATIVE = 'DERIVATIVE'
    """Phái sinh"""

    INDEX = 'INDEX'
    """Chỉ số"""


class Resolution(StrEnum):
    """
    Khung thời gian nến.

    - `1`: 1 phút
    - `3`: 3 phút
    - `5`: 5 phút
    - `15`: 15 phút
    - `30`: 30 phút
    - `1H`: 1 giờ
    - `1D`: 1 ngày
    - `1W`: 1 tuần
    """

    M1 = '1'
    """1 phút"""

    M3 = '3'
    """3 phút"""

    M5 = '5'
    """5 phút"""

    M15 = '15'
    """15 phút"""

    M30 = '30'
    """30 phút"""

    H1 = '1H'
    """1 giờ"""

    D1 = '1D'
    """1 ngày"""

    W1 = '1W'
    """1 tuần"""


class Side(StrEnum):
    """
    Chiều xác định mua/bán chủ động.

    - `UNSPECIFIED`: Không xác định
    - `BUY`: Mua chủ động
    - `SELL`: Bán chủ động
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    BUY = 'BUY'
    """Mua chủ động"""

    SELL = 'SELL'
    """Bán chủ động"""


class TradingSessionId(StrEnum):
    """
    Mã phiên giao dịch theo từng mã.

    - `UNSPECIFIED`: Không xác định
    - `10`: ATO
    - `30`: ATC
    - `40`: Phiên liên tục
    - `80`: PCA mã halt
    - `99`: Đóng bảng
    """

    UNSPECIFIED = 'UNSPECIFIED'
    """Không xác định"""

    V10 = '10'
    """ATO"""

    V30 = '30'
    """ATC"""

    V40 = '40'
    """Phiên liên tục"""

    V80 = '80'
    """PCA mã halt"""

    V99 = '99'
    """Đóng bảng"""


class EventId(StrEnum):
    """
    Mã sự kiện chuyển trạng thái phiên giao dịch.

    - `AA1`: Bắt đầu phiên khớp lệnh định kỳ mở cửa
    - `AB1`: Bắt đầu phiên khớp lệnh liên tục
    - `AB2`: Kết thúc giao dịch của bảng
    - `AC2`: Thực hiện khớp lệnh định kỳ đóng cửa
    - `AD1`: Bắt đầu nhận lệnh
    - `AD2`: Thực hiện khớp lệnh định kỳ
    - `AW8`: Nghỉ trưa
    - `AW9`: Tiếp tục giao dịch sau nghỉ trưa
    - `AX1`: Bảng giao dịch bắt đầu hoạt động
    - `BB1`: Bắt đầu phiên khớp lệnh liên tục cho chứng khoán thông thường
    - `BC1`: Bắt đầu phiên khớp lệnh định kỳ đóng cửa
    - `CC1`: Bắt đầu phiên PCA đóng cửa
    - `CD1`: Bắt đầu phiên PCA
    - `CD3`: Thực hiện khớp lệnh PCA
    """

    AA1 = 'AA1'
    """Bắt đầu phiên khớp lệnh định kỳ mở cửa"""

    AB1 = 'AB1'
    """Bắt đầu phiên khớp lệnh liên tục"""

    AB2 = 'AB2'
    """Kết thúc giao dịch của bảng"""

    AC2 = 'AC2'
    """Thực hiện khớp lệnh định kỳ đóng cửa"""

    AD1 = 'AD1'
    """Bắt đầu nhận lệnh"""

    AD2 = 'AD2'
    """Thực hiện khớp lệnh định kỳ"""

    AW8 = 'AW8'
    """Nghỉ trưa"""

    AW9 = 'AW9'
    """Tiếp tục giao dịch sau nghỉ trưa"""

    AX1 = 'AX1'
    """Bảng giao dịch bắt đầu hoạt động"""

    BB1 = 'BB1'
    """Bắt đầu phiên khớp lệnh liên tục cho chứng khoán thông thường"""

    BC1 = 'BC1'
    """Bắt đầu phiên khớp lệnh định kỳ đóng cửa"""

    CC1 = 'CC1'
    """Bắt đầu phiên PCA đóng cửa"""

    CD1 = 'CD1'
    """Bắt đầu phiên PCA"""

    CD3 = 'CD3'
    """Thực hiện khớp lệnh PCA"""


class ClosePrice(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    isin: str | MISSING = Field(MISSING, description='Mã định danh quốc tế')
    """Mã định danh quốc tế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    close_price: float | MISSING = Field(
        MISSING, alias='closePrice', description='Giá đóng cửa của mã chứng khoán'
    )
    """Giá đóng cửa của mã chứng khoán"""

    time: str | MISSING = Field(
        MISSING, description='Thời gian ghi nhận (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))'
    )
    """Thời gian ghi nhận (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))"""


class ExpectedPrice(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(MISSING, alias='marketId')
    board_id: BoardId | MISSING = Field(MISSING, alias='boardId')
    isin: str | MISSING = Field(
        MISSING, description='Mã định danh quốc tế (ISIN) của chứng khoán.'
    )
    """Mã định danh quốc tế (ISIN) của chứng khoán."""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    close_price: float | MISSING = Field(
        MISSING, alias='closePrice', description='Giá đóng cửa'
    )
    """Giá đóng cửa"""

    expected_trade_price: float | MISSING = Field(
        MISSING, alias='expectedTradePrice', description='Giá khớp dự kiến'
    )
    """Giá khớp dự kiến"""

    expected_trade_quantity: int | MISSING = Field(
        MISSING, alias='expectedTradeQuantity', description='Khối lượng khớp dự kiến'
    )
    """Khối lượng khớp dự kiến"""

    time: str | MISSING = Field(
        MISSING,
        description='Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7).',
    )
    """Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)."""


class ForeignTrading(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    trading_session_id: TradingSessionId | MISSING = Field(
        MISSING,
        alias='tradingSessionId',
        description='Mã phiên giao dịch hiện tại\n- 10: Phiên ATO\n- 30: Phiên ATC\n- 40: Phiên liên tục\n- 80: PCA Mã halt\n- 99: Đóng bảng',
    )
    """
    Mã phiên giao dịch hiện tại
    - 10: Phiên ATO
    - 30: Phiên ATC
    - 40: Phiên liên tục
    - 80: PCA Mã halt
    - 99: Đóng bảng
    """

    sell_volume: int | MISSING = Field(
        MISSING,
        alias='sellVolume',
        description='Khối lượng bán khớp lệnh của nhà đầu tư nước ngoài trong phiên',
    )
    """Khối lượng bán khớp lệnh của nhà đầu tư nước ngoài trong phiên"""

    sell_traded_amount: int | MISSING = Field(
        MISSING,
        alias='sellTradedAmount',
        description='Giá trị bán khớp lệnh của nhà đầu tư nước ngoài trong phiên',
    )
    """Giá trị bán khớp lệnh của nhà đầu tư nước ngoài trong phiên"""

    buy_volume: int | MISSING = Field(
        MISSING,
        alias='buyVolume',
        description='Khối lượng mua khớp lệnh của nhà đầu tư nước ngoài trong phiên',
    )
    """Khối lượng mua khớp lệnh của nhà đầu tư nước ngoài trong phiên"""

    buy_traded_amount: int | MISSING = Field(
        MISSING,
        alias='buyTradedAmount',
        description='Giá trị mua khớp lệnh của nhà đầu tư nước ngoài trong phiên',
    )
    """Giá trị mua khớp lệnh của nhà đầu tư nước ngoài trong phiên"""

    total_sell_volume: int | MISSING = Field(
        MISSING,
        alias='totalSellVolume',
        description='Tổng khối lượng bán lũy kế của nhà đầu tư nước ngoài',
    )
    """Tổng khối lượng bán lũy kế của nhà đầu tư nước ngoài"""

    total_sell_traded_amount: int | MISSING = Field(
        MISSING,
        alias='totalSellTradedAmount',
        description='Tổng giá trị bán lũy kế của nhà đầu tư nước ngoài',
    )
    """Tổng giá trị bán lũy kế của nhà đầu tư nước ngoài"""

    total_buy_volume: int | MISSING = Field(
        MISSING,
        alias='totalBuyVolume',
        description='Tổng khối lượng mua lũy kế của nhà đầu tư nước ngoà',
    )
    """Tổng khối lượng mua lũy kế của nhà đầu tư nước ngoà"""

    total_buy_traded_amount: int | MISSING = Field(
        MISSING,
        alias='totalBuyTradedAmount',
        description='Tổng giá trị mua lũy kế của nhà đầu tư nước ngoài',
    )
    """Tổng giá trị mua lũy kế của nhà đầu tư nước ngoài"""

    foreigner_order_limit_quantity: int | MISSING = Field(
        MISSING,
        alias='foreignerOrderLimitQuantity',
        description='Giới hạn khối lượng sở hữu tối đa dành cho nhà đầu tư nước ngoài',
    )
    """Giới hạn khối lượng sở hữu tối đa dành cho nhà đầu tư nước ngoài"""

    foreigner_buy_possible_quantity: int | MISSING = Field(
        MISSING,
        alias='foreignerBuyPossibleQuantity',
        description='Khối lượng còn lại mà nhà đầu tư nước ngoài được phép mua',
    )
    """Khối lượng còn lại mà nhà đầu tư nước ngoài được phép mua"""

    time: str | MISSING = Field(
        MISSING,
        description='Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7).',
    )
    """Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)."""


class Instrument(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn UPCOM\n- DVX: Phái sinh\n- HCX: Trái phiếu doanh nghiệp',
    )
    """
    Mã thị trường niêm yết
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn UPCOM
    - DVX: Phái sinh
    - HCX: Trái phiếu doanh nghiệp
    """

    security_group_id: SecurityGroupId | MISSING = Field(
        MISSING,
        alias='securityGroupId',
        description='Nhóm chứng khoán\n- ST: Cổ phiếu\n- EF: Quỹ ETF\n- EW: Chứng quyền\n- FU: Hợp đồng tương lai\n- BS: Trái phiếu',
    )
    """
    Nhóm chứng khoán
    - ST: Cổ phiếu
    - EF: Quỹ ETF
    - EW: Chứng quyền
    - FU: Hợp đồng tương lai
    - BS: Trái phiếu
    """

    symbol_type: SymbolType | MISSING = Field(
        MISSING,
        alias='symbolType',
        description='Phân loại mã hợp đồng phái sinh theo thời gian đáo hạn (áp dụng cho DERIVATIVE)\n- VN30F1M: HĐTL chỉ số VN30 1 tháng\n- VN30F2M: HĐTL chỉ số VN30 2 tháng\n- VN30F1Q: HĐTL chỉ số VN30 1 quý\n- VN30F2Q: HĐTL chỉ số VN30 2 quý',
    )
    """
    Phân loại mã hợp đồng phái sinh theo thời gian đáo hạn (áp dụng cho DERIVATIVE)
    - VN30F1M: HĐTL chỉ số VN30 1 tháng
    - VN30F2M: HĐTL chỉ số VN30 2 tháng
    - VN30F1Q: HĐTL chỉ số VN30 1 quý
    - VN30F2Q: HĐTL chỉ số VN30 2 quý
    """

    listed_date: str | MISSING = Field(
        MISSING, alias='listedDate', description='Ngày niêm yết'
    )
    """Ngày niêm yết"""

    short_name: str | MISSING = Field(
        MISSING, alias='shortName', description='Tên viết tắt của tổ chức phát hành'
    )
    """Tên viết tắt của tổ chức phát hành"""

    name: str | MISSING = Field(MISSING, description='Tên đầy đủ của tổ chức phát hành')
    """Tên đầy đủ của tổ chức phát hành"""

    index_name: list[str] | MISSING = Field(
        MISSING,
        alias='indexName',
        description='Danh sách chỉ số mà mã chứng khoán thuộc về (nếu có)',
    )
    """Danh sách chỉ số mà mã chứng khoán thuộc về (nếu có)"""


class InstrumentsResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    data: list[Instrument] | MISSING = Field(
        MISSING, description='Danh sách thông tin mã chứng khoán'
    )
    """Danh sách thông tin mã chứng khoán"""

    total: int | MISSING = Field(MISSING, description='Tổng số bản ghi')
    """Tổng số bản ghi"""

    page: int | MISSING = Field(MISSING, description='Trang hiện tại (bắt đầu từ 1)')
    """Trang hiện tại (bắt đầu từ 1)"""

    page_size: int | MISSING = Field(
        MISSING, alias='pageSize', description='Số bản ghi trên mỗi trang'
    )
    """Số bản ghi trên mỗi trang"""


class ClosePriceResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    prices: list[ClosePrice] | MISSING = Field(
        MISSING, description='Danh sách thông tin giá đóng cửa của các mã chứng khoán.'
    )
    """Danh sách thông tin giá đóng cửa của các mã chứng khoán."""


class ExpectedPriceResponse(BaseModel):
    """
    Danh sách dữ liệu giá khớp dự kiến cùng thông tin phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    expected_prices: list[ExpectedPrice] | MISSING = Field(
        MISSING,
        alias='expectedPrices',
        description='Danh sách dữ liệu giá khớp dự kiến của mã chứng khoán.',
    )
    """Danh sách dữ liệu giá khớp dự kiến của mã chứng khoán."""

    next_page_token: str | None | MISSING = Field(
        MISSING,
        alias='nextPageToken',
        description='Token dùng để lấy trang dữ liệu tiếp theo. Giá trị null nếu không còn dữ liệu.',
    )
    """Token dùng để lấy trang dữ liệu tiếp theo. Giá trị null nếu không còn dữ liệu."""


class ForeignTradingResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    foreigners: list[ForeignTrading] | MISSING = Field(
        MISSING,
        description='Danh sách dữ liệu giao dịch của nhà đầu tư nước ngoài theo mã chứng khoán.',
    )
    """Danh sách dữ liệu giao dịch của nhà đầu tư nước ngoài theo mã chứng khoán."""

    next_page_token: str | MISSING = Field(
        MISSING,
        alias='nextPageToken',
        description='Token dùng để lấy trang dữ liệu tiếp theo. Giá trị null nếu không còn dữ liệu.',
    )
    """Token dùng để lấy trang dữ liệu tiếp theo. Giá trị null nếu không còn dữ liệu."""


class SecdefItem(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    isin: str | MISSING = Field(MISSING, description='Mã định danh quốc tế')
    """Mã định danh quốc tế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    product_grp_id: ProductGrpId | MISSING = Field(
        MISSING,
        alias='productGrpId',
        description='Nhóm sản phẩm theo thị trường\n-FBX: Hợp đồng tương lai Trái phiếu\n-FIO: Hợp đồng tương lai Chỉ số\n-HCX: Trái phiếu Doanh nghiệp HNX\n-STO: Cổ phiếu sàn HOSE\n-STX: Cổ phiếu sàn HNX\n-UPX: Cổ phiếu sàn Upcom',
    )
    """
    Nhóm sản phẩm theo thị trường
    -FBX: Hợp đồng tương lai Trái phiếu
    -FIO: Hợp đồng tương lai Chỉ số
    -HCX: Trái phiếu Doanh nghiệp HNX
    -STO: Cổ phiếu sàn HOSE
    -STX: Cổ phiếu sàn HNX
    -UPX: Cổ phiếu sàn Upcom
    """

    security_group_id: SecurityGroupId | MISSING = Field(
        MISSING,
        alias='securityGroupId',
        description='Nhóm chứng khoán\n- BS: Trái phiếu doanh nghiệp\n- EF: Quỹ ETF\n- EW: Chứng quyền\n- FU: Hợp đồng tương lai\n- ST: Cổ phiếu',
    )
    """
    Nhóm chứng khoán
    - BS: Trái phiếu doanh nghiệp
    - EF: Quỹ ETF
    - EW: Chứng quyền
    - FU: Hợp đồng tương lai
    - ST: Cổ phiếu
    """

    basic_price: float | MISSING = Field(
        MISSING, alias='basicPrice', description='Giá tham chiếu ngày giao dịch'
    )
    """Giá tham chiếu ngày giao dịch"""

    ceiling_price: float | MISSING = Field(
        MISSING, alias='ceilingPrice', description='Giá trần ngày giao dịch'
    )
    """Giá trần ngày giao dịch"""

    floor_price: float | MISSING = Field(
        MISSING, alias='floorPrice', description='Giá sàn ngày giao dịch'
    )
    """Giá sàn ngày giao dịch"""

    security_status: SecurityStatus | MISSING = Field(
        MISSING,
        alias='securityStatus',
        description='Trạng thái giao dịch của mã chứng khoán\n- HALT: Ngừng giao dịch\n- NO_HALT: Không ngừng giao dịch',
    )
    """
    Trạng thái giao dịch của mã chứng khoán
    - HALT: Ngừng giao dịch
    - NO_HALT: Không ngừng giao dịch
    """

    symbol_admin_status_code: SymbolAdminStatusCode | MISSING = Field(
        MISSING,
        alias='symbolAdminStatusCode',
        description='Trạng thái quản lý hành chính mã chứng khoán\n- CR: Kiểm soát và hạn chế giao dịch\n- CTR: Kiểm soát\n- NRM: Bình thường\n- RES: Hạn chế giao dịch\n- WFR: Cảnh báo vi phạm BCTC\n- WID: Cảnh báo vi phạm CBTT\n- WOV: Cảnh báo vi phạm khác',
    )
    """
    Trạng thái quản lý hành chính mã chứng khoán
    - CR: Kiểm soát và hạn chế giao dịch
    - CTR: Kiểm soát
    - NRM: Bình thường
    - RES: Hạn chế giao dịch
    - WFR: Cảnh báo vi phạm BCTC
    - WID: Cảnh báo vi phạm CBTT
    - WOV: Cảnh báo vi phạm khác
    """

    symbol_trading_method_status_code: SymbolTradingMethodStatusCode | MISSING = Field(
        MISSING,
        alias='symbolTradingMethodStatusCode',
        description='Trạng thái cơ chế giao dịch mã chứng khoán\n- NRM: Bình thường\n- NWE: Niêm yết mới (biên độ đặc biệt)\n- NWN: Niêm yết mới (biên độ thường)\n- SLS: Giao dịch đặc biệt sau tạm ngưng\n- SNE: Giao dịch đặc biệt không có giao dịch dài hạn',
    )
    """
    Trạng thái cơ chế giao dịch mã chứng khoán
    - NRM: Bình thường
    - NWE: Niêm yết mới (biên độ đặc biệt)
    - NWN: Niêm yết mới (biên độ thường)
    - SLS: Giao dịch đặc biệt sau tạm ngưng
    - SNE: Giao dịch đặc biệt không có giao dịch dài hạn
    """

    symbol_trading_sanction_status_code: SymbolTradingSanctionStatusCode | MISSING = (
        Field(
            MISSING,
            alias='symbolTradingSanctionStatusCode',
            description='Tình trạng giao dịch của mã chứng khoán\n- NRM: Bình thường\n- SUS: Tạm ngừng giao dịch\n- DTL: Hủy niêm yết để chuyển sàn\n- TFR: Ngưng giao dịch do hạn chế',
        )
    )
    """
    Tình trạng giao dịch của mã chứng khoán
    - NRM: Bình thường
    - SUS: Tạm ngừng giao dịch
    - DTL: Hủy niêm yết để chuyển sàn
    - TFR: Ngưng giao dịch do hạn chế
    """

    final_trade_date: str | None | MISSING = Field(
        MISSING, alias='finalTradeDate', description='Ngày giao dịch cuối cùng (nếu có)'
    )
    """Ngày giao dịch cuối cùng (nếu có)"""

    listing_date: AwareDatetime | MISSING = Field(
        MISSING, alias='listingDate', description='Ngày niêm yế'
    )
    """Ngày niêm yế"""

    time: str | MISSING = Field(
        MISSING, description='Thời gian ghi nhận (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))'
    )
    """Thời gian ghi nhận (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))"""


class SecdefResponse(RootModel[list[SecdefItem]]):
    root: list[SecdefItem] = Field(..., description='')
    """"""


class Quote(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    isin: str | MISSING = Field(
        MISSING, description='Mã định danh quốc tế (ISIN) của chứng khoán.'
    )
    """Mã định danh quốc tế (ISIN) của chứng khoán."""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    bid: list[QuoteBidLevel] | MISSING = Field(
        MISSING, description='Danh sách các mức giá chào mua'
    )
    """Danh sách các mức giá chào mua"""

    offer: list[QuoteOfferLevel] | MISSING = Field(
        MISSING, description='Danh sách các mức giá chào bán'
    )
    """Danh sách các mức giá chào bán"""

    total_offer_qtty: int | MISSING = Field(
        MISSING, alias='totalOfferQtty', description='Tổng khối lượng dư bán'
    )
    """Tổng khối lượng dư bán"""

    total_bid_qtty: int | MISSING = Field(
        MISSING, alias='totalBidQtty', description='Tổng khối lượng dư mua'
    )
    """Tổng khối lượng dư mua"""

    time: str | MISSING = Field(
        MISSING,
        description='Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)',
    )
    """Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)"""


class QuoteLatest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    isin: str | MISSING = Field(
        MISSING, description='Mã định danh quốc tế (ISIN) của chứng khoán.'
    )
    """Mã định danh quốc tế (ISIN) của chứng khoán."""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    bid: list[QuoteBidLevelLatest] | MISSING = Field(
        MISSING, description='Danh sách các mức giá chào mua'
    )
    """Danh sách các mức giá chào mua"""

    offer: list[QuoteOfferLevelLatest] | MISSING = Field(
        MISSING, description='Danh sách các mức giá chào bán'
    )
    """Danh sách các mức giá chào bán"""

    total_offer_qtty: int | MISSING = Field(
        MISSING, alias='totalOfferQtty', description='Tổng khối lượng dư bán'
    )
    """Tổng khối lượng dư bán"""

    total_bid_qtty: int | MISSING = Field(
        MISSING, alias='totalBidQtty', description='Tổng khối lượng dư mua'
    )
    """Tổng khối lượng dư mua"""

    time: str | MISSING = Field(
        MISSING,
        description='Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)',
    )
    """Thời gian ghi nhận. Định dạng: YYYY-MM-DD HH:mm:ss.SSS (GMT+7)"""


class Trade(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING, alias='marketId', description='Mã thị trường'
    )
    """Mã thị trường"""

    board_id: BoardId | MISSING = Field(
        MISSING, alias='boardId', description='Mã bảng giao dịch'
    )
    """Mã bảng giao dịch"""

    isin: str | MISSING = Field(MISSING, description='Mã định danh quốc tế')
    """Mã định danh quốc tế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp gần nhất'
    )
    """Giá khớp gần nhất"""

    match_qtty: int | MISSING = Field(
        MISSING, alias='matchQtty', description='Khối lượng khớp gần nhất'
    )
    """Khối lượng khớp gần nhất"""

    side: Side | MISSING = Field(MISSING, description='Chiều giao dịch')
    """Chiều giao dịch"""

    avg_price: float | MISSING = Field(
        MISSING, alias='avgPrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    total_volume_traded: int | MISSING = Field(
        MISSING,
        alias='totalVolumeTraded',
        description='Tổng khối lượng giao dịch trong ngày',
    )
    """Tổng khối lượng giao dịch trong ngày"""

    gross_trade_amount: float | MISSING = Field(
        MISSING,
        alias='grossTradeAmount',
        description='Tổng giá trị giao dịch trong ngày',
    )
    """Tổng giá trị giao dịch trong ngày"""

    highest_price: float | MISSING = Field(
        MISSING, alias='highestPrice', description='Giá cao nhất trong ngày'
    )
    """Giá cao nhất trong ngày"""

    lowest_price: float | MISSING = Field(
        MISSING, alias='lowestPrice', description='Giá thấp nhất trong ngày'
    )
    """Giá thấp nhất trong ngày"""

    open_price: int | MISSING = Field(
        MISSING, alias='openPrice', description='Giá mở cửa'
    )
    """Giá mở cửa"""

    time: str | MISSING = Field(MISSING, description='Thời gian ghi nhận')
    """Thời gian ghi nhận"""


class TradeLatest(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(
        MISSING,
        alias='marketId',
        description='Mã thị trường niêm yết mã chứng khoán\n- DVX: Phái sinh sàn HNX\n- HCX: Trái phiếu doanh nghiệp HNX\n- STO: Cổ phiếu sàn HOSE\n- STX: Cổ phiếu sàn HNX\n- UPX: Cổ phiếu sàn Upcom',
    )
    """
    Mã thị trường niêm yết mã chứng khoán
    - DVX: Phái sinh sàn HNX
    - HCX: Trái phiếu doanh nghiệp HNX
    - STO: Cổ phiếu sàn HOSE
    - STX: Cổ phiếu sàn HNX
    - UPX: Cổ phiếu sàn Upcom
    """

    board_id: BoardId | MISSING = Field(
        MISSING,
        alias='boardId',
        description='Mã bảng giao dịch\n- G1: Lô chẵn\n- G4: Lô lẻ\n- T1: Thỏa thuận trong giờ (9h - 14h45)\n- T3: Thỏa thuận sau giờ (14h45 - 15h)\n- T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)\n- T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)',
    )
    """
    Mã bảng giao dịch
    - G1: Lô chẵn
    - G4: Lô lẻ
    - T1: Thỏa thuận trong giờ (9h - 14h45)
    - T3: Thỏa thuận sau giờ (14h45 - 15h)
    - T4: Thỏa thuận lô lẻ trong giờ (9h - 14h45)
    - T6: Thỏa thuận lô lẻ sau giờ (14h45 - 15h)
    """

    isin: str | MISSING = Field(MISSING, description='Mã định danh quốc tế')
    """Mã định danh quốc tế"""

    symbol: str | MISSING = Field(MISSING, description='Mã chứng khoán')
    """Mã chứng khoán"""

    match_price: float | MISSING = Field(
        MISSING, alias='matchPrice', description='Giá khớp lệnh của giao dịch'
    )
    """Giá khớp lệnh của giao dịch"""

    match_qtty: int | MISSING = Field(
        MISSING, alias='matchQtty', description='Khối lượng khớp của giao dịch'
    )
    """Khối lượng khớp của giao dịch"""

    side: Side | MISSING = Field(
        MISSING,
        description='Phía giao dịch chủ động\n- BUY: Bên mua chủ động\n- SELL: Bên bán chủ động',
    )
    """
    Phía giao dịch chủ động
    - BUY: Bên mua chủ động
    - SELL: Bên bán chủ động
    """

    avg_price: float | MISSING = Field(
        MISSING, alias='avgPrice', description='Giá khớp trung bình'
    )
    """Giá khớp trung bình"""

    total_volume_traded: int | MISSING = Field(
        MISSING,
        alias='totalVolumeTraded',
        description='Tổng khối lượng đã giao dịch trong ngày',
    )
    """Tổng khối lượng đã giao dịch trong ngày"""

    gross_trade_amount: float | MISSING = Field(
        MISSING,
        alias='grossTradeAmount',
        description='Tổng giá trị giao dịch trong nngày',
    )
    """Tổng giá trị giao dịch trong nngày"""

    highest_price: float | MISSING = Field(
        MISSING, alias='highestPrice', description='Giá khớp cao nhất trong ngày'
    )
    """Giá khớp cao nhất trong ngày"""

    lowest_price: float | MISSING = Field(
        MISSING, alias='lowestPrice', description='Giá khớp thấp nhất trong ngày'
    )
    """Giá khớp thấp nhất trong ngày"""

    open_price: float | MISSING = Field(
        MISSING, alias='openPrice', description='Giá mở cửa'
    )
    """Giá mở cửa"""

    time: str | MISSING = Field(
        MISSING, description='Thời gian khớp lệnh (theo định dạng yyyy-MM-dd HH:mm:ss)'
    )
    """Thời gian khớp lệnh (theo định dạng yyyy-MM-dd HH:mm:ss)"""


class TradingSession(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    market_id: MarketId | MISSING = Field(MISSING, alias='marketId')
    board_id: BoardId | MISSING = Field(MISSING, alias='boardId')
    tsc_prod_grp_id: ProductGrpId | MISSING = Field(MISSING, alias='tscProdGrpId')
    trading_session_id: TradingSessionId | MISSING = Field(
        MISSING, alias='tradingSessionId'
    )
    event_id: EventId | MISSING = Field(MISSING, alias='eventId')
    time: str | MISSING = Field(
        MISSING,
        description='Thời gian ghi nhận định dạng (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))',
    )
    """Thời gian ghi nhận định dạng (YYYY-MM-DD HH:mm:ss.SSS (GMT+7))"""


class TradingSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    trading_sessions: list[TradingSession] | MISSING = Field(
        MISSING, alias='tradingSessions', description=''
    )
    """"""


class QuotesLatestResponse(BaseModel):
    """
    Dữ liệu sổ lệnh (Market Depth) gần nhất
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    quotes: list[QuoteLatest] | MISSING = Field(
        MISSING, description='Dữ liệu sổ lệnh của mã chứng khoán'
    )
    """Dữ liệu sổ lệnh của mã chứng khoán"""


class QuotesResponse(BaseModel):
    """
    Danh sách dữ liệu sổ lệnh (Market Depth) cùng thông tin phân trang.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    quotes: list[Quote] | MISSING = Field(
        MISSING, description='Danh sách dữ liệu sổ lệnh của mã chứng khoán'
    )
    """Danh sách dữ liệu sổ lệnh của mã chứng khoán"""

    next_page_token: str | MISSING = Field(
        MISSING,
        alias='nextPageToken',
        description='Token dùng để lấy trang dữ liệu tiếp theo. Không có hoặc rỗng nếu không còn dữ liệu',
    )
    """Token dùng để lấy trang dữ liệu tiếp theo. Không có hoặc rỗng nếu không còn dữ liệu"""


class TradesLatestResponse(BaseModel):
    """
    Thông tinh giao dịch khớp lệnh.
    """

    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    trades: list[TradeLatest] | MISSING = Field(MISSING, description='')
    """"""


class TradesResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        validate_by_name=True,
    )
    trades: list[Trade] | MISSING = Field(MISSING, description='Danh sách giao dịch')
    """Danh sách giao dịch"""

    next_page_token: str | MISSING = Field(
        MISSING, alias='nextPageToken', description='Token dùng để lấy trang tiếp theo'
    )
    """Token dùng để lấy trang tiếp theo"""
